const std = @import("std");

// C sources that have not been ported to Zig yet. As modules are translated,
// they move out of this list and are referenced from zelda_zig.zig instead.
const c_sources = [_][]const u8{
    "third_party/gl_core/gl_core_3_1.c",
    // Carries the stb_image implementation used by glsl_shader.zig.
    "third_party/stb/stb_image_impl.c",
    "third_party/opus-1.3.1-stripped/opus_decoder_amalgam.c",
};

const c_flags = [_][]const u8{
    "-std=gnu11",
    "-DSYSTEM_VOLUME_MIXER_AVAILABLE=0",
    // The upstream C build used plain clang with no sanitizers. The remaining
    // third-party C reads unaligned uint16s on purpose, which zig's default
    // UBSan traps on; the Zig code uses *align(1) pointers instead, so these
    // flags now only cover third_party/.
    "-fno-sanitize=undefined",
    "-Wno-unused-but-set-variable",
    "-Wno-incompatible-pointer-types",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const exe = b.addExecutable(.{
        .name = "zelda3",
        .root_module = b.createModule(.{
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });

    exe.root_module.addIncludePath(b.path("."));
    exe.root_module.addCSourceFiles(.{
        .files = &c_sources,
        .flags = &c_flags,
    });

    // The ported modules compile to one object that is linked in alongside the
    // remaining C. Each one exports the same symbols its C file used to.
    const zig_obj = b.addObject(.{
        .name = "zelda_zig",
        .root_module = b.createModule(.{
            .root_source_file = b.path("zelda_zig.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    zig_obj.root_module.addIncludePath(b.path("."));
    exe.root_module.addObject(zig_obj);

    const tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("zelda_zig.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    tests.root_module.addIncludePath(b.path("."));
    // Exercise the same C/Zig boundaries as the game while the port is in
    // progress. Real implementations replace the former panic-only stubs.
    tests.root_module.addCSourceFiles(.{
        .files = &c_sources,
        .flags = &c_flags,
    });
    const reference = b.option([]const u8, "ancilla-reference", "Original C oracle generated by other/check_ancilla_parity.py");
    const test_options = b.addOptions();
    test_options.addOption(bool, "ancilla_parity", reference != null);
    tests.root_module.addOptions("build_options", test_options);
    if (reference) |path| {
        // The oracle carries its own headers from the baseline commit, so it
        // needs no include path into the (now header-free) source tree.
        tests.root_module.addCSourceFile(.{ .file = .{ .cwd_relative = path }, .flags = &c_flags });
    }
    const test_step = b.step("test", "Run tests for the ported Zig modules");
    test_step.dependOn(&b.addRunArtifact(tests).step);

    const launcher_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/launcher.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    addSdlIncludes(b, launcher_tests.root_module);
    linkSdlLibs(b, launcher_tests.root_module);
    test_step.dependOn(&b.addRunArtifact(launcher_tests).step);

    // The asset tooling needs no SDL; it is plain byte wrangling. Rooting the
    // test at asset_build.zig picks up rom.zig and asset_pack.zig with it.
    const asset_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/asset_build.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    test_step.dependOn(&b.addRunArtifact(asset_tests).step);

    // Every module that sees SDL headers or symbols, C and Zig alike.
    for ([_]*std.Build.Module{ exe.root_module, zig_obj.root_module, tests.root_module }) |m| {
        addSdlIncludes(b, m);
    }
    linkSdlLibs(b, exe.root_module);
    linkSdlLibs(b, tests.root_module);
    exe.root_module.linkSystemLibrary("m", .{});
    tests.root_module.linkSystemLibrary("m", .{});

    if (target.result.os.tag == .macos) {
        exe.root_module.linkFramework("OpenGL", .{});
    }

    // The launcher is its own binary: it edits zelda3.ini and starts the game,
    // so it stays clear of the game's own startup path.
    const launcher = b.addExecutable(.{
        .name = "zelda3-launcher",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/launcher.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        }),
    });
    addSdlIncludes(b, launcher.root_module);
    linkSdlLibs(b, launcher.root_module);
    b.installArtifact(launcher);

    const launcher_run = b.addRunArtifact(launcher);
    launcher_run.step.dependOn(b.getInstallStep());
    if (b.args) |args| launcher_run.addArgs(args);
    const launcher_step = b.step("launcher", "Build and run the launcher");
    launcher_step.dependOn(&launcher_run.step);

    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Build and run zelda3");
    run_step.dependOn(&run_cmd.step);
}

// SDL3 is a system dependency. It ships no sdl3-config, so the paths come
// from pkg-config, which also covers Homebrew installing outside the default
// search path.
fn addSdlIncludes(b: *std.Build, m: *std.Build.Module) void {
    const cflags = sdl3PkgConfig(b, "--cflags") orelse return;
    var it = std.mem.tokenizeAny(u8, cflags, " \r\n");
    while (it.next()) |arg| {
        if (std.mem.startsWith(u8, arg, "-I")) {
            m.addIncludePath(.{ .cwd_relative = arg[2..] });
        } else if (std.mem.startsWith(u8, arg, "-D")) {
            const body = arg[2..];
            if (std.mem.indexOfScalar(u8, body, '=')) |eq| {
                m.addCMacro(body[0..eq], body[eq + 1 ..]);
            } else {
                m.addCMacro(body, "1");
            }
        }
    }
}

fn linkSdlLibs(b: *std.Build, m: *std.Build.Module) void {
    const libs = sdl3PkgConfig(b, "--libs") orelse {
        m.linkSystemLibrary("SDL3", .{});
        return;
    };
    var it = std.mem.tokenizeAny(u8, libs, " \r\n");
    while (it.next()) |arg| {
        if (std.mem.startsWith(u8, arg, "-L")) {
            m.addLibraryPath(.{ .cwd_relative = arg[2..] });
        } else if (std.mem.startsWith(u8, arg, "-l")) {
            m.linkSystemLibrary(arg[2..], .{});
        }
    }
}

/// Null when pkg-config is missing or knows nothing about sdl3, so the caller
/// can fall back to a plain -lSDL3 and let the linker look in the usual places.
fn sdl3PkgConfig(b: *std.Build, arg: []const u8) ?[]const u8 {
    const exe_path = b.findProgram(&.{"pkg-config"}, &.{}) catch return null;
    // A nonzero exit (no sdl3.pc installed) comes back as an error, not a code.
    var code: u8 = undefined;
    return b.runAllowFail(&.{ exe_path, arg, "sdl3" }, &code, .ignore) catch null;
}
