//! Data tables for ancilla.c, generated by evaluating the C
//! initializers with clang -- macros and enums included. Do not edit by hand.

pub const kAncilla_Pflags = [68]u8{
    0, 8, 12, 16, 16, 4, 16, 24, 8, 8, 8, 0, 20, 0, 16, 40,
    24, 16, 16, 16, 16, 12, 8, 8, 80, 0, 16, 8, 64, 0, 12, 36,
    16, 12, 8, 16, 16, 4, 12, 28, 0, 16, 20, 20, 16, 8, 32, 16,
    16, 16, 4, 0, 128, 16, 4, 48, 20, 16, 0, 16, 0, 0, 8, 0,
    16, 8, 120, 128,
};

pub const kFireRod_Xvel2 = [12]i8{
    0, 0, -40, 40, 0, 0, -48, 48, 0, 0, -64, 64,
};

pub const kFireRod_Yvel2 = [12]i8{
    -40, 40, 0, 0, -48, 48, 0, 0, -64, 64, 0, 0,
};

pub const kTagalongLayerBits = [4]u8{
    32, 16, 48, 32,
};

pub const kBombos_Sfx = [8]u8{
    128, 128, 128, 0, 0, 64, 64, 64,
};

pub const kBomb_Tab0 = [11]u8{
    160, 6, 4, 4, 4, 4, 4, 6, 6, 6, 6,
};

pub const kAncilla_TileColl_Attrs = [256]i8{
    0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 3, 3, 3,
    0, 0, 0, 0, 0, 0, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4,
    1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 3, 3, 3,
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
};

pub const kAncilla_TileColl0_Attrs = [256]u8{
    0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2, 0, 3, 3, 3,
    0, 0, 0, 0, 0, 0, 1, 1, 4, 4, 4, 4, 4, 4, 4, 4,
    1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 3, 3, 3,
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4,
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
};

pub const kBomb_Draw_Tab0 = [12]u8{
    0, 1, 2, 3, 2, 3, 4, 5, 6, 7, 8, 9,
};

pub const kBomb_Draw_Tab2 = [11]u8{
    1, 4, 4, 4, 4, 4, 5, 4, 6, 6, 6,
};

pub const kMagicPowder_Tab0 = [40]u8{
    13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 0, 1, 2,
    3, 4, 5, 6, 16, 17, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8,
    9, 0, 1, 2, 3, 4, 5, 6,
};

pub const kEther_BlitzOrb_Char = [8]u8{
    72, 72, 74, 74, 76, 76, 78, 78,
};

pub const kEther_BlitzOrb_Flags = [8]u8{
    60, 124, 60, 124, 60, 124, 60, 124,
};

pub const kEther_BlitzSegment_Char = [4]u8{
    64, 66, 68, 70,
};

pub const kBombosBlasts_Tab = [72]u8{
    182, 93, 161, 48, 105, 181, 163, 36, 150, 172, 115, 95, 146, 72, 82, 129,
    57, 149, 127, 32, 136, 93, 52, 152, 188, 210, 81, 119, 162, 71, 148, 178,
    52, 218, 48, 98, 159, 118, 81, 70, 152, 92, 155, 97, 88, 149, 76, 186,
    126, 203, 18, 208, 112, 166, 70, 191, 64, 80, 126, 140, 45, 97, 172, 136,
    32, 106, 114, 95, 210, 40, 82, 128,
};

pub const kQuake_Tab1 = [5]u8{
    23, 22, 23, 22, 16,
};

pub const kQuakeDrawGroundBolts_Char = [15]u8{
    64, 66, 68, 70, 72, 74, 76, 78, 96, 98, 100, 102, 104, 106, 99,
};

pub const kQuakeItemPos = [64]u8{
    0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 17, 21, 25, 30,
    36, 42, 48, 53, 57, 60, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72,
    74, 77, 81, 85, 88, 91, 94, 97, 100, 103, 107, 111, 114, 116, 118, 119,
    120, 121, 122, 123, 124, 125, 126, 128, 130, 132, 134, 137, 141, 145, 149, 151,
};

pub const kQuakeItemPos2 = [56]u8{
    0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 18, 19, 20,
    21, 22, 23, 24, 26, 28, 30, 33, 37, 41, 45, 46, 47, 48, 49, 50,
    51, 52, 53, 55, 57, 59, 62, 66, 70, 72, 73, 74, 75, 76, 78, 80,
    82, 84, 87, 91, 95, 99, 101, 104,
};

pub const kReceiveItem_Tab4 = [3]u8{
    9, 5, 5,
};

pub const kReceiveItem_Tab5 = [3]u8{
    36, 37, 38,
};

pub const kReceiveItem_Tab0 = [3]u8{
    5, 1, 4,
};

pub const kReceiveItemMsgs = [76]i16{
    -1, 112, 119, 82, -1, 120, 120, 98,
    97, 102, 105, 83, 82, 86, -1, 100,
    99, 101, 81, 84, 103, 104, 107, 119,
    121, 85, 110, 88, 109, 93, 87, 94,
    -1, 116, 117, 118, -1, 95, 344, -1,
    106, 92, 143, 113, 114, 115, 113, 114,
    115, 106, 108, 96, -1, -1, -1, 89,
    132, 90, -1, -1, -1, -1, -1, 345,
    -1, -1, -1, -1, -1, -1, -1, -1,
    -1, 219, 103, 124,
};

pub const kReceiveItemMsgs2 = [2]i16{
    91, 131,
};

pub const kReceiveItemMsgs3 = [4]i16{
    -1, 341, 342, 343,
};

pub const kTravelBird_DmaStuffs = [4]u8{
    0, 32, 64, 224,
};

pub const kTravelBird_Draw_X = [3]i8{
    0, -9, -9,
};

pub const kTravelBird_Draw_Y = [3]i8{
    0, 12, 20,
};

pub const kTravelBird_Draw_Char = [3]u8{
    14, 0, 2,
};

pub const kTravelBird_Draw_Flags = [3]u8{
    34, 46, 46,
};

pub const kSomarianBlock_Coll_X = [12]i8{
    0, 0, -8, 8, 0, 0, 0, 0, 8, -8, -8, 8,
};

pub const kSomarianBlock_Coll_Y = [12]i8{
    -8, 8, 0, 0, 0, 0, 0, 0, -8, 8, -8, 8,
};

pub const kInitialSpinSpark_Char = [32]u8{
    146, 255, 255, 255, 140, 140, 140, 140, 214, 214, 214, 214, 147, 147, 147, 147,
    214, 214, 214, 214, 215, 255, 255, 255, 128, 255, 255, 255, 34, 255, 255, 255,
};

pub const kInitialSpinSpark_Flags = [29]u8{
    34, 255, 255, 255, 34, 98, 162, 226, 36, 100, 164, 228, 34, 98, 162, 226,
    34, 98, 162, 226, 34, 255, 255, 255, 34, 255, 255, 255, 252,
};

pub const kInitialSpinSpark_Y = [29]i8{
    -4, 0, 0, 0, -8, -8, 0, 0, -8, -8, 0, 0, -8, -8, 0, 0,
    -8, -8, 0, 0, -4, 0, 0, 0, -4, 0, 0, 0, -4,
};

pub const kInitialSpinSpark_X = [29]i16{
    -4, 0, 0, 0, -8, 0, -8, 0,
    -8, 0, -8, 0, -8, 0, -8, 0,
    -8, 0, -8, 0, -4, 0, 0, 0,
    -4, 0, 0, 0, 4517,
};

pub const kAddDashingDust_X = [4]i8{
    4, 4, 6, 0,
};

pub const kAddDashingDust_Y = [4]i8{
    20, 4, 16, 16,
};

pub const kAncilla_Damage = [57]u8{
    6, 1, 11, 0, 0, 0, 0, 8, 0, 6, 0, 12, 1, 0, 0, 0,
    0, 1, 0, 0, 0, 0, 0, 0, 14, 13, 0, 0, 15, 0, 0, 7,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 11,
    0, 1, 1, 1, 1, 1, 1, 1, 1,
};

pub const kFireRod_X = [4]i8{
    0, 0, -8, 16,
};

pub const kFireRod_Y = [4]i8{
    -8, 16, 3, 3,
};

pub const kFireRod_Xvel = [4]i8{
    0, 0, -64, 64,
};

pub const kFireRod_Yvel = [4]i8{
    -64, 64, 0, 0,
};

pub const kSpawnCentrifugalQuad_X = [4]i8{
    -8, -8, -9, -4,
};

pub const kSpawnCentrifugalQuad_Y = [4]i8{
    -15, -4, -8, -8,
};

pub const kIceShotSparkle_X = [16]u8{
    2, 7, 6, 1, 1, 7, 7, 1, 0, 7, 8, 1, 4, 9, 4, 255,
};

pub const kIceShotSparkle_Y = [16]u8{
    2, 3, 8, 7, 1, 1, 7, 7, 1, 0, 7, 8, 255, 4, 9, 4,
};

pub const kIceShotSparkle_Char = [16]u8{
    131, 131, 131, 131, 182, 128, 182, 128, 183, 182, 183, 182, 183, 182, 183, 182,
};

pub const kIceShotSparkle_Xvel = [4]i8{
    0, 0, -4, 4,
};

pub const kIceShotSparkle_Yvel = [4]i8{
    -4, 4, 0, 0,
};

pub const kSomarianBlast_Mask = [6]u8{
    7, 3, 1, 0, 0, 0,
};

pub const kAncilla_FloorFlags = [2]u8{
    32, 16,
};

pub const kSomarianBlast_Flags = [2]u8{
    2, 6,
};

pub const kSomarianBlast_Draw_X0 = [24]i8{
    0, 0, 0, 0, 4, 4, 0, 0, 0, 0, 4, 4, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
};

pub const kSomarianBlast_Draw_X1 = [24]i8{
    8, 8, 8, 8, 4, 4, 8, 8, 8, 8, 4, 4, 0, 0, 0, 0,
    8, 8, 0, 0, 0, 0, 8, 8,
};

pub const kSomarianBlast_Draw_Y0 = [24]u8{
    128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    4, 4, 0, 0, 0, 0, 4, 4,
};

pub const kSomarianBlast_Draw_Y1 = [24]u8{
    0, 0, 0, 0, 8, 8, 128, 0, 0, 0, 8, 8, 128, 8, 8, 8,
    4, 4, 128, 8, 8, 8, 4, 4,
};

pub const kSomarianBlast_Draw_Flags0 = [24]u8{
    192, 192, 192, 192, 128, 192, 64, 64, 64, 64, 0, 64, 64, 64, 64, 64,
    64, 192, 0, 0, 0, 0, 0, 128,
};

pub const kSomarianBlast_Draw_Flags1 = [24]u8{
    128, 128, 128, 128, 128, 192, 0, 0, 0, 0, 0, 64, 192, 192, 192, 192,
    64, 192, 128, 128, 128, 128, 0, 128,
};

pub const kSomarianBlast_Draw_Char0 = [24]u8{
    80, 80, 68, 68, 82, 82, 80, 80, 68, 68, 81, 81, 67, 67, 66, 66,
    65, 65, 67, 67, 66, 66, 64, 64,
};

pub const kSomarianBlast_Draw_Char1 = [24]u8{
    80, 80, 68, 68, 81, 81, 80, 80, 68, 68, 82, 82, 67, 67, 66, 66,
    64, 64, 67, 67, 66, 66, 65, 65,
};

pub const kFireShot_Draw_Char = [3]u8{
    162, 160, 142,
};

pub const kFireShot_Draw_X2 = [16]u8{
    7, 0, 8, 0, 8, 4, 0, 0, 2, 8, 0, 0, 1, 4, 9, 0,
};

pub const kFireShot_Draw_Y2 = [16]u8{
    1, 4, 9, 0, 7, 0, 8, 0, 8, 4, 0, 0, 2, 8, 0, 0,
};

pub const kFireShot_Draw_Char2 = [3]u8{
    141, 157, 156,
};

pub const kAncilla_CheckTileColl0_X = [20]i8{
    8, 8, 0, 16, 4, 4, 0, 16, 4, 4, 4, 12, 12, 12, 4, 12,
    0, 0, 0, 0,
};

pub const kAncilla_CheckTileColl0_Y = [20]i8{
    0, 16, 5, 5, 0, 16, 4, 4, 4, 12, 5, 5, 4, 12, 12, 12,
    0, 0, 0, 0,
};

pub const kAncilla_CheckTileColl_Y = [4]i8{
    -8, 8, 0, 0,
};

pub const kAncilla_CheckTileColl_X = [4]i8{
    0, 0, -8, 8,
};

pub const kBeamHit_X = [16]i8{
    -12, 20, -12, 20, -8, 16, -8, 16, -4, 12, -4, 12, 0, 8, 0, 8,
};

pub const kBeamHit_Y = [16]i8{
    -12, -12, 20, 20, -8, -8, 16, 16, -4, -4, 12, 12, 0, 0, 8, 8,
};

pub const kBeamHit_Char = [16]u8{
    83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 84, 84, 84, 84,
};

pub const kBeamHit_Flags = [16]u8{
    64, 0, 192, 128, 64, 0, 192, 128, 64, 0, 192, 128, 0, 64, 128, 192,
};

pub const kAncilla_CheckSpriteColl_Dir = [4]u8{
    2, 3, 0, 1,
};

pub const kAncilla_CheckSpriteColl_RecoilX = [4]i8{
    0, 0, -64, 64,
};

pub const kAncilla_CheckSpriteColl_RecoilY = [4]i8{
    -64, 64, 0, 0,
};

pub const kAncilla_HitBox_X = [12]i8{
    4, 4, 4, 4, 3, 3, 2, 11, -16, -16, -1, -8,
};

pub const kAncilla_HitBox_Y = [12]i8{
    4, 4, 4, 4, 2, 11, 3, 3, -1, -8, -16, -16,
};

pub const kAncilla_HitBox_W = [12]u8{
    8, 8, 8, 8, 1, 1, 1, 1, 32, 32, 8, 8,
};

pub const kAncilla_HitBox_H = [12]u8{
    8, 8, 8, 8, 1, 1, 1, 1, 8, 8, 32, 32,
};

pub const kRepulseSpark_Flags = [4]u8{
    34, 18, 34, 34,
};

pub const kRepulseSpark_Char = [3]u8{
    147, 130, 129,
};

pub const kBoomerang_X0 = [8]i8{
    0, 0, -8, 8, 8, 8, -8, -8,
};

pub const kBoomerang_Y0 = [8]i8{
    -16, 6, 0, 0, -8, 8, -8, 8,
};

pub const kBoomerang_Flags = [8]u8{
    164, 228, 100, 36, 162, 226, 98, 34,
};

pub const kBoomerang_Draw_XY = [8]i8{
    2, -2, 2, 2, -2, 2, -2, -2,
};

pub const kBoomerang_Draw_OamIdx = [2]u16{
    384, 208,
};

pub const kBoomerang_Draw_Tab0 = [2]u8{
    3, 2,
};

pub const kWallHit_X = [32]i8{
    -4, 0, 0, 0, -4, 0, 0, 0, -8, 0, -8, 0, -8, 0, -8, 0,
    -8, 0, -8, 0, -4, 0, 0, 0, -4, 0, 0, 0, -8, 0, 0, 0,
};

pub const kWallHit_Y = [32]i8{
    -4, 0, 0, 0, -4, 0, 0, 0, -8, -8, 0, 0, -8, -8, 0, 0,
    -8, -8, 0, 0, -4, 0, 0, 0, -4, 0, 0, 0, -8, 0, 0, 0,
};

pub const kWallHit_Char = [32]u8{
    128, 0, 0, 0, 146, 0, 0, 0, 129, 129, 129, 129, 130, 130, 130, 130,
    147, 147, 147, 147, 146, 0, 0, 0, 185, 0, 0, 0, 144, 144, 0, 0,
};

pub const kWallHit_Flags = [32]u8{
    50, 0, 0, 0, 50, 0, 0, 0, 50, 114, 178, 242, 50, 114, 178, 242,
    50, 114, 178, 242, 50, 0, 0, 0, 114, 0, 0, 0, 50, 242, 0, 0,
};

pub const kAncilla_Belt_Xvel = [4]i8{
    0, 0, -8, 8,
};

pub const kAncilla_Belt_Yvel = [4]i8{
    -8, 8, 0, 0,
};

pub const kBomb_Dmg_Speed = [16]u8{
    32, 32, 32, 32, 32, 32, 28, 28, 28, 28, 28, 28, 24, 24, 24, 24,
};

pub const kBomb_Dmg_Zvel = [16]u8{
    16, 16, 16, 16, 16, 16, 12, 12, 12, 12, 8, 8, 8, 8, 8, 8,
};

pub const kBomb_Dmg_Delay = [16]u8{
    32, 32, 32, 32, 32, 32, 24, 24, 24, 24, 24, 24, 16, 16, 16, 16,
};

pub const kBomb_Dmg_ToLink = [3]u8{
    8, 4, 2,
};

pub const kAncilla_Liftable_Delay = [3]u8{
    16, 8, 9,
};

pub const kAncilla_Liftable_Yvel = [4]i8{
    -32, 32, 0, 0,
};

pub const kAncilla_Liftable_Xvel = [4]i8{
    0, 0, -32, 32,
};

pub const kAncilla_Func3_X = [12]i8{
    8, 8, -4, 20, 8, 8, 8, 8, 8, 8, 8, 8,
};

pub const kAncilla_Func3_Y = [12]i8{
    16, 8, 4, 4, 8, 2, -1, -1, 2, 2, -1, -1,
};

pub const kAncilla_Func2_Y = [6]i8{
    -2, -1, 0, -2, -1, 0,
};

pub const kDoorDebris_XY = [64]u16{
    4, 7, 3, 17, 8, 8, 7, 17,
    11, 7, 10, 16, 16, 7, 17, 17,
    20, 7, 21, 17, 16, 8, 17, 17,
    13, 7, 14, 16, 8, 7, 7, 17,
    7, 4, 17, 3, 8, 8, 17, 7,
    7, 11, 16, 10, 7, 16, 17, 17,
    7, 20, 17, 21, 8, 16, 17, 17,
    7, 13, 16, 14, 7, 8, 17, 7,
};

pub const kDoorDebris_CharFlags = [32]u16{
    8286, 57438, 41054, 24670, 8271, 8271, 8271, 8271,
    24670, 24670, 8286, 57438, 24655, 24655, 24655, 24655,
    8286, 57438, 41054, 24670, 8271, 57423, 8271, 8271,
    24670, 24670, 8286, 57438, 24655, 24655, 24655, 24655,
};

pub const kArrow_Y = [4]i8{
    -4, 2, 0, 0,
};

pub const kArrow_X = [4]i8{
    0, 0, -4, 4,
};

pub const kArrow_Draw_Char = [48]u8{
    43, 42, 42, 43, 61, 58, 58, 61, 43, 255, 43, 255, 61, 255, 61, 255,
    60, 44, 60, 42, 60, 44, 60, 42, 44, 60, 42, 60, 44, 60, 42, 60,
    59, 45, 59, 58, 59, 45, 59, 58, 45, 59, 58, 59, 45, 59, 58, 59,
};

pub const kArrow_Draw_Flags = [48]u8{
    164, 164, 36, 36, 100, 100, 36, 36, 164, 255, 36, 255, 100, 255, 36, 255,
    164, 164, 164, 164, 164, 228, 164, 164, 36, 36, 36, 36, 100, 36, 36, 36,
    100, 100, 100, 228, 100, 228, 100, 228, 36, 36, 36, 164, 164, 36, 36, 164,
};

pub const kArrow_Draw_Y = [48]i8{
    0, 8, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8,
    -1, -1, 0, 0, 0, 1, 0, 0, -1, -1, 0, 0, 1, 0, 0, 0,
};

pub const kArrow_Draw_X = [48]i8{
    0, 0, 0, 0, 0, 8, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 0, 0, -1, -2, 0, 0, 1, 1, 0, 0, -2, -1, 0, 0,
    0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8,
};

pub const kIceShotSpread_CharFlags = [16]u8{
    207, 36, 207, 36, 207, 36, 207, 36, 223, 36, 223, 36, 223, 36, 223, 36,
};

pub const kIceShotSpread_XY = [16]u8{
    0, 0, 0, 8, 8, 0, 8, 8, 248, 248, 248, 16, 16, 248, 16, 16,
};

pub const kBomb_DrawExplosion_XY = [108]i8{
    -8, -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -8, -8, -8, 0,
    0, -8, 0, 0, 0, 0, 0, 0, -16, -16, -16, 0, 0, -16, 0, 0,
    0, 0, 0, 0, -16, -16, -16, 0, 0, -16, 0, 0, 0, 0, 0, 0,
    -8, -8, -21, -22, -21, 8, 9, -22, 9, 8, 0, 0, -6, -15, 0, -1,
    -16, -2, -8, -7, 0, 0, 0, 0, -9, -4, -21, -5, -12, -18, -11, 7,
    0, -15, 4, -2, -9, -4, -22, -5, -13, -20, -11, 8, 1, -16, 5, -2,
    -20, 4, -12, -19, -9, 16, -5, -2, 2, -9, 10, 6,
};

pub const kBomb_DrawExplosion_CharFlags = [108]u8{
    110, 38, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 140, 34, 140, 98,
    140, 162, 140, 226, 255, 255, 255, 255, 132, 34, 132, 98, 132, 162, 132, 226,
    255, 255, 255, 255, 136, 34, 136, 98, 136, 162, 136, 226, 255, 255, 255, 255,
    134, 34, 136, 34, 136, 98, 136, 162, 136, 226, 255, 255, 134, 34, 134, 98,
    134, 226, 134, 226, 255, 255, 255, 255, 134, 226, 134, 34, 134, 34, 134, 98,
    134, 162, 134, 162, 138, 162, 138, 98, 138, 34, 138, 98, 138, 98, 138, 226,
    155, 34, 155, 162, 155, 98, 155, 226, 155, 162, 155, 34,
};

pub const kBomb_DrawExplosion_Ext = [54]u8{
    2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 2, 2, 2,
    1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2,
    2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    0, 0, 0, 0, 0, 0,
};

pub const kAncilla_JumpSplash_Char = [2]u8{
    172, 174,
};

pub const kAncilla_HitStars_Char = [2]u8{
    144, 145,
};

pub const kShovelDirt_XY = [8]i8{
    18, -13, -9, 4, 18, 13, -9, -11,
};

pub const kShovelDirt_Char = [2]i8{
    64, 80,
};

pub const kBlastWallFireball_Char = [3]u8{
    157, 156, 141,
};

pub const kEther_BlitzBall_Char = [2]u8{
    104, 106,
};

pub const kEther_SpllittingBlitzSegment_X = [16]i8{
    -8, -16, -24, -16, -8, 0, 8, -16, -8, -16, -24, -16, -8, 0, 8, 0,
};

pub const kEther_SpllittingBlitzSegment_Y = [16]i8{
    8, 0, -8, -16, -24, -16, -8, -16, 8, 0, -8, -16, -24, -16, -8, 0,
};

pub const kEther_SpllittingBlitzSegment_Char = [32]u8{
    64, 66, 102, 100, 98, 96, 100, 102, 66, 64, 102, 100, 96, 98, 100, 102,
    104, 66, 104, 100, 104, 96, 104, 100, 104, 64, 104, 102, 104, 98, 104, 100,
};

pub const kEther_SpllittingBlitzSegment_Flags = [32]u8{
    60, 60, 252, 252, 60, 60, 188, 188, 60, 60, 60, 60, 60, 60, 124, 124,
    60, 124, 60, 60, 60, 188, 60, 124, 60, 124, 60, 252, 60, 188, 60, 188,
};

pub const kBombos_YDelta = [4]i16{
    16, 24, -128, -16,
};

pub const kBombos_XDelta = [4]i16{
    -16, -128, 0, 128,
};

pub const kBombosSpell_FireColumn_X = [39]i8{
    0, -1, -1, 0, 0, -1, 0, 0, -1, 0, 0, -1, 0, 0, -1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    -1, 1, -1, -1, 2, -1, -1,
};

pub const kBombosSpell_FireColumn_Y = [39]i8{
    0, -1, -1, 0, -4, -1, 0, -8, -1, 0, -12, -1, 0, -16, -1, 0,
    -4, -20, 0, -8, -24, 0, -12, -28, 0, -16, -32, 0, -16, -32, -18, -34,
    -1, -35, -1, -1, -36, -1, -1,
};

pub const kBombosSpell_FireColumn_Flags = [39]u8{
    60, 255, 255, 60, 60, 255, 60, 60, 255, 124, 124, 255, 60, 124, 255, 60,
    60, 60, 188, 60, 60, 124, 60, 60, 60, 60, 124, 60, 60, 60, 60, 60,
    255, 60, 255, 255, 60, 255, 255,
};

pub const kBombosSpell_FireColumn_Char = [39]u8{
    64, 255, 255, 66, 68, 255, 66, 68, 255, 66, 68, 255, 66, 68, 255, 64,
    70, 68, 74, 74, 72, 76, 76, 74, 78, 76, 74, 78, 106, 76, 78, 104,
    255, 106, 255, 255, 78, 255, 255,
};

pub const kBombosSpell_DrawBlast_X = [32]i8{
    -8, -1, -1, -1, -12, -4, -12, -4, -16, 0, -16, 0, -16, 0, -16, 0,
    -17, 1, -17, 1, -19, 3, -19, 3, -19, 3, -19, 3, -19, 3, -19, 3,
};

pub const kBombosSpell_DrawBlast_Y = [32]i8{
    -8, -1, -1, -1, -12, -12, -4, -4, -16, -16, 0, 0, -16, -16, 0, 0,
    -17, -17, 1, 1, -19, -19, 3, 3, -19, -19, 3, 3, -19, -19, 3, 3,
};

pub const kBombosSpell_DrawBlast_Flags = [32]u8{
    60, 255, 255, 255, 60, 124, 188, 252, 60, 124, 188, 252, 60, 124, 188, 252,
    60, 124, 188, 252, 60, 124, 188, 252, 60, 124, 188, 252, 60, 124, 188, 252,
};

pub const kBombosSpell_DrawBlast_Char = [32]u8{
    96, 255, 255, 255, 98, 98, 98, 98, 100, 100, 100, 100, 102, 102, 102, 102,
    104, 104, 104, 104, 104, 104, 104, 104, 106, 106, 106, 106, 78, 78, 78, 78,
};

pub const kQuakeDrawGroundBolts_Tab = [5]u8{
    0, 24, 0, 24, 47,
};

pub const kMagicPowder_DrawX = [76]i8{
    -5, -12, 2, -9, -7, -10, -6, -2, -6, -12, 1, -6, -6, -12, 1, -6,
    -6, -12, 1, -6, -6, -12, 1, -6, -6, -12, 1, -6, -17, -23, -14, -19,
    -11, -18, -9, -13, -4, -13, -1, -8, -3, -9, 0, -5, -3, -10, -1, -5,
    -4, -13, -1, -8, -3, -9, 0, -5, -3, -10, -1, -5, -3, -13, -1, -8,
    9, 15, 6, 11, 3, 10, 1, 5, -4, 5, -7, 0,
};

pub const kMagicPowder_DrawY = [76]i8{
    -20, -15, -13, -7, -18, -13, -13, -13, -20, -13, -13, -8, -20, -13, -13, -8,
    -19, -12, -12, -7, -18, -11, -11, -6, -17, -10, -10, -5, -16, -14, -12, -9,
    -17, -14, -12, -8, -18, -14, -13, -6, -33, -31, -29, -26, -28, -25, -23, -19,
    -22, -18, -17, -10, -2, 0, 2, 5, -9, -6, -4, 0, -16, -12, -11, -4,
    -16, -14, -12, -9, -17, -14, -12, -8, -18, -14, -13, -6,
};

pub const kMagicPowder_Draw_Char = [19]u8{
    9, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
    9, 9, 9,
};

pub const kMagicPowder_Draw_Flags = [76]u8{
    104, 36, 162, 40, 104, 226, 40, 164, 104, 226, 164, 40, 34, 164, 232, 98,
    36, 168, 226, 100, 40, 162, 228, 104, 34, 164, 232, 98, 226, 164, 232, 100,
    232, 168, 228, 98, 228, 168, 226, 104, 226, 164, 232, 100, 232, 168, 228, 98,
    228, 168, 226, 104, 226, 164, 232, 100, 232, 168, 228, 98, 228, 168, 226, 104,
    226, 164, 232, 100, 232, 168, 228, 98, 228, 168, 226, 104,
};

pub const kDashDust_Draw_X1 = [4]i8{
    0, 0, 4, -4,
};

pub const kDashDust_Draw_X = [30]i16{
    10, 5, -1, 0, 10, 5, 0, 5,
    -1, 0, -1, -1, 9, -1, -1, 10,
    5, -1, 0, 10, 5, 0, 5, -1,
    0, -1, -1, 9, -1, -1,
};

pub const kDashDust_Draw_Y = [30]i16{
    -2, 0, -1, -3, -2, 0, -3, 0,
    -1, -3, -1, -1, -2, -1, -1, -2,
    0, -1, -3, -2, 0, -3, 0, -1,
    -3, -1, -1, -2, -1, -1,
};

pub const kDashDust_Draw_Char = [30]u8{
    207, 169, 255, 169, 223, 207, 207, 223, 255, 223, 255, 255, 169, 255, 255, 207,
    207, 255, 207, 223, 207, 207, 223, 255, 223, 255, 255, 207, 255, 255,
};

pub const kHookShot_Move_X = [4]i8{
    0, 0, 8, -8,
};

pub const kHookShot_Move_Y = [4]i8{
    8, -9, 0, 0,
};

pub const kHookShot_Draw_Flags = [12]u8{
    0, 0, 255, 128, 128, 255, 64, 255, 64, 0, 255, 0,
};

pub const kHookShot_Draw_Char = [12]u8{
    9, 10, 255, 9, 10, 255, 9, 255, 10, 9, 255, 10,
};

pub const kBedSpread_Char = [8]u8{
    10, 10, 10, 10, 12, 12, 10, 10,
};

pub const kBedSpread_Flags = [8]u8{
    0, 96, 160, 224, 0, 96, 160, 224,
};

pub const kBedSpread_Dma = [3]u8{
    68, 67, 66,
};

pub const kAncilla_VictorySparkle_X = [16]i8{
    16, 0, 0, 0, 8, 16, 8, 16, 9, 15, 0, 0, 12, 0, 0, 0,
};

pub const kAncilla_VictorySparkle_Y = [16]i8{
    -7, 0, 0, 0, -11, -11, -3, -3, -7, -7, 0, 0, -7, 0, 0, 0,
};

pub const kAncilla_VictorySparkle_Char = [16]u8{
    146, 255, 255, 255, 147, 147, 147, 147, 249, 249, 255, 255, 128, 255, 255, 255,
};

pub const kAncilla_VictorySparkle_Flags = [16]u8{
    0, 255, 255, 255, 0, 64, 128, 192, 0, 64, 255, 255, 0, 255, 255, 255,
};

pub const kSwordChargeSpark_Char = [3]u8{
    183, 128, 131,
};

pub const kSwordChargeSpark_Flags = [3]u8{
    4, 4, 132,
};

pub const kSwordCeremony_X = [8]i8{
    -1, 8, -1, 8, 0, 7, 0, 7,
};

pub const kSwordCeremony_Y = [8]i8{
    1, 1, 9, 9, 1, 1, 9, 9,
};

pub const kSwordCeremony_Char = [8]u8{
    134, 134, 150, 150, 135, 135, 151, 151,
};

pub const kSwordCeremony_Flags = [8]u8{
    1, 65, 1, 65, 1, 65, 1, 65,
};

pub const kObjectSplash_Draw_X = [10]i8{
    0, 0, 0, 0, 11, -3, 15, -7, 15, -7,
};

pub const kObjectSplash_Draw_Y = [10]i8{
    0, 0, -6, 0, -13, -8, -17, -4, -17, -4,
};

pub const kObjectSplash_Draw_Char = [10]u8{
    192, 255, 231, 255, 175, 191, 128, 128, 131, 131,
};

pub const kObjectSplash_Draw_Flags = [10]u8{
    0, 255, 0, 255, 64, 0, 64, 0, 192, 128,
};

pub const kObjectSplash_Draw_Ext = [10]u8{
    2, 0, 2, 0, 0, 0, 0, 0, 0, 0,
};

pub const kFlute_Vels = [4]u8{
    24, 16, 10, 0,
};

pub const kWeathervane_Explode_Char = [2]u8{
    78, 79,
};

pub const kTravelBirdIntro_Tab0 = [2]u8{
    64, 0,
};

pub const kTravelBirdIntro_Tab1 = [2]u8{
    28, 60,
};

pub const kMorphPoof_X = [12]i8{
    0, 0, 0, 0, 0, 8, 0, 8, -4, 12, -4, 12,
};

pub const kMorphPoof_Y = [12]i8{
    0, 0, 0, 0, 0, 0, 8, 8, -4, -4, 12, 12,
};

pub const kMorphPoof_Flags = [12]u8{
    0, 255, 255, 255, 64, 0, 192, 128, 0, 64, 128, 192,
};

pub const kMorphPoof_Char = [3]u8{
    134, 169, 155,
};

pub const kMorphPoof_Ext = [3]u8{
    2, 0, 0,
};

pub const kBushPoof_Draw_X = [16]i8{
    0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0, 8, -2, 10, -2, 10,
};

pub const kBushPoof_Draw_Y = [16]i8{
    0, 0, 8, 8, 0, 0, 8, 8, 0, 0, 8, 8, -2, -2, 10, 10,
};

pub const kBushPoof_Draw_Char = [16]u8{
    134, 135, 150, 151, 169, 169, 169, 169, 138, 139, 154, 155, 155, 155, 155, 155,
};

pub const kBushPoof_Draw_Flags = [16]u8{
    0, 0, 0, 0, 0, 64, 128, 192, 0, 0, 0, 0, 192, 128, 64, 0,
};

pub const kSwordSwingSparkle_X = [48]i8{
    5, 10, -1, 5, 10, -4, 5, 10, -4, -4, -1, -1, 0, 5, -1, 0,
    5, 14, 0, 5, 14, 14, -1, -1, -23, -27, -1, -23, -27, -22, -23, -27,
    -22, -22, -1, -1, 32, 35, -1, 32, 35, 30, 32, 35, 30, 30, -1, -1,
};

pub const kSwordSwingSparkle_Y = [48]i8{
    -22, -18, -1, -22, -18, -17, -22, -18, -17, -17, -1, -1, 35, 40, -1, 35,
    40, 37, 35, 40, 37, 37, -1, -1, 2, 7, -1, 2, 7, 19, 2, 7,
    19, 19, -1, -1, 2, 7, -1, 2, 7, 19, 2, 7, 19, 19, -1, -1,
};

pub const kSwordSwingSparkle_Char = [48]u8{
    183, 183, 255, 128, 128, 183, 131, 131, 128, 131, 255, 255, 183, 183, 255, 128,
    128, 183, 131, 131, 128, 131, 255, 255, 183, 183, 255, 128, 128, 183, 131, 131,
    128, 131, 255, 255, 183, 183, 255, 128, 128, 183, 131, 131, 128, 131, 255, 255,
};

pub const kSwordSwingSparkle_Flags = [48]u8{
    0, 0, 255, 0, 0, 0, 128, 128, 0, 128, 255, 255, 0, 0, 255, 0,
    0, 0, 128, 128, 0, 128, 255, 255, 0, 0, 255, 0, 0, 0, 128, 128,
    0, 128, 255, 255, 0, 0, 255, 0, 0, 0, 128, 128, 0, 128, 255, 255,
};

pub const kInitialSpinSpark_Timer = [6]u8{
    4, 2, 3, 3, 2, 1,
};

pub const kTransmuteSpinSpark_Arr = [16]u8{
    33, 32, 31, 30, 3, 2, 1, 0, 18, 17, 16, 15, 49, 48, 47, 46,
};

pub const kTransmuteSpinSpark_X = [4]i8{
    -3, 21, 25, -8,
};

pub const kTransmuteSpinSpark_Y = [4]i8{
    28, -2, 24, 6,
};

pub const kSpinSpark_Char = [4]u8{
    215, 183, 128, 131,
};

pub const kSpinSpark_Char2 = [3]u8{
    183, 128, 131,
};

pub const kInitialCaneSpark_X = [16]i8{
    3, 1, 0, 0, 13, 16, 12, 12, 24, 7, -4, -10, -8, 9, 22, 26,
};

pub const kInitialCaneSpark_Y = [16]i8{
    5, 0, -3, -6, -8, -3, 12, 28, 5, 0, 8, 16, 5, 0, 8, 16,
};

pub const kInitialCaneSpark_Draw_X = [16]i8{
    -4, 0, 0, 0, -8, 0, -8, 0, -8, 0, -8, 0, -8, 0, -8, 0,
};

pub const kInitialCaneSpark_Draw_Y = [16]i8{
    -4, 0, 0, 0, -8, -8, 0, 0, -8, -8, 0, 0, -8, -8, 0, 0,
};

pub const kInitialCaneSpark_Draw_Char = [16]u8{
    146, 255, 255, 255, 140, 140, 140, 140, 214, 214, 214, 214, 147, 147, 147, 147,
};

pub const kInitialCaneSpark_Draw_Flags = [16]u8{
    34, 255, 255, 255, 34, 98, 162, 226, 36, 100, 164, 228, 34, 98, 162, 226,
};

pub const kCaneSpark_Transmute_Tab = [16]u8{
    52, 51, 50, 49, 22, 21, 20, 19, 42, 41, 40, 39, 16, 15, 14, 13,
};

pub const kCaneSpark_Magic = [3]u8{
    4, 2, 1,
};

pub const kCaneSpark_Char = [4]u8{
    215, 183, 128, 131,
};

pub const kSwordBeam_Yvel2 = [4]i8{
    0, 0, -6, -6,
};

pub const kSwordBeam_Xvel2 = [4]i8{
    -8, -10, 0, 0,
};

pub const kSwordBeam_Char = [4]u8{
    215, 183, 128, 131,
};

pub const kSwordBeam_Char2 = [3]u8{
    183, 128, 131,
};

pub const kSwordFullChargeSpark_Y = [4]i8{
    -8, 27, 12, 12,
};

pub const kSwordFullChargeSpark_X = [4]i8{
    4, 4, -13, 20,
};

pub const kSwordFullChargeSpark_Flags = [4]u8{
    32, 16, 48, 32,
};

pub const kCaneOfSomaria_Y = [4]i8{
    -8, 31, 17, 17,
};

pub const kCaneOfSomaria_X = [4]i8{
    8, 8, -8, 23,
};

pub const kSomariaTransitLine_X = [12]i8{
    -8, 0, 8, -8, 0, 8, -16, -16, -16, 16, 16, 16,
};

pub const kSomariaTransitLine_Y = [12]i8{
    -16, -16, -16, 16, 16, 16, -8, 0, 8, -8, 0, 8,
};

pub const kSomarianBlock_Draw_X = [12]i8{
    -8, 0, -8, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

pub const kSomarianBlock_Draw_Y = [12]i8{
    -8, -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

pub const kSomarianBlock_Draw_Flags = [12]u8{
    0, 64, 128, 192, 0, 64, 128, 192, 0, 64, 128, 192,
};

pub const kSomarianBlock_CheckCover_X = [4]i8{
    0, 0, -4, 4,
};

pub const kSomarianBlock_CheckCover_Y = [4]i8{
    -4, 4, 0, 0,
};

pub const kSomariaBlockFizzle_X = [6]i8{
    -4, -1, -8, 0, -6, -2,
};

pub const kSomariaBlockFizzle_Y = [6]i8{
    -4, -1, -4, -4, -4, -4,
};

pub const kSomariaBlockFizzle_Char = [6]u8{
    146, 255, 249, 249, 249, 249,
};

pub const kSomariaBlockFizzle_Flags = [6]u8{
    6, 255, 134, 198, 134, 198,
};

pub const kSomarianPlatformPoof_Tab0 = [4]u8{
    1, 0, 3, 2,
};

pub const kSomarianBlockDivide_X = [16]i8{
    -8, 0, -8, 0, -10, -10, 2, 2, -8, 0, -8, 0, -12, -12, 4, 4,
};

pub const kSomarianBlockDivide_Y = [16]i8{
    -10, -10, 2, 2, -8, 0, -8, 0, -12, -12, 4, 4, -8, 0, -8, 0,
};

pub const kSomarianBlockDivide_Char = [16]u8{
    198, 198, 198, 198, 196, 196, 196, 196, 210, 210, 210, 210, 197, 197, 197, 197,
};

pub const kSomarianBlockDivide_Flags = [16]u8{
    198, 134, 70, 6, 70, 198, 6, 134, 198, 134, 70, 6, 70, 198, 6, 134,
};

pub const kLampFlame_Draw_Char = [12]u8{
    156, 156, 255, 255, 164, 165, 178, 179, 227, 243, 255, 255,
};

pub const kLampFlame_Draw_Y = [12]i8{
    -3, 0, 0, 0, 0, 0, 8, 8, 0, 8, 0, 0,
};

pub const kLampFlame_Draw_X = [12]i8{
    4, 10, 0, 0, 1, 9, 2, 7, 4, 4, 0, 0,
};

pub const kWaterfallSplash_X = [8]i8{
    0, 0, -4, 4, -7, 7, -9, 17,
};

pub const kWaterfallSplash_Y = [8]i8{
    -4, 0, -5, -5, -3, -3, 12, 12,
};

pub const kWaterfallSplash_Char = [8]u8{
    192, 255, 172, 172, 174, 174, 191, 191,
};

pub const kWaterfallSplash_Flags = [8]u8{
    132, 255, 132, 196, 132, 196, 132, 196,
};

pub const kWaterfallSplash_Ext = [8]u8{
    2, 255, 2, 2, 2, 2, 0, 0,
};

pub const kAncilla_Gravestone_Char = [4]u8{
    200, 200, 216, 216,
};

pub const kAncilla_Gravestone_Flags = [4]u8{
    0, 64, 0, 64,
};

pub const kSkullWoodsFire_Draw_Y = [4]i8{
    0, 0, 0, -3,
};

pub const kSkullWoodsFire_Draw_Char = [4]u8{
    142, 160, 162, 164,
};

pub const kSkullWoodsFire_Draw_Ext = [4]u8{
    2, 2, 2, 0,
};

pub const kSkullWoodsFire_Draw2_X = [24]i8{
    -13, -21, -10, -1, -1, -1, -16, -27, -4, -16, -6, -25, -16, -27, -4, -16,
    -6, -25, -13, -5, -27, -11, -22, -3,
};

pub const kSkullWoodsFire_Draw2_Y = [24]i8{
    -31, -24, -22, -1, -1, -1, -37, -32, -32, -23, -16, -14, -37, -32, -32, -23,
    -16, -14, -35, -29, -28, -20, -13, -11,
};

pub const kSkullWoodsFire_Draw2_Char = [24]u8{
    134, 134, 134, 255, 255, 255, 134, 134, 134, 134, 134, 134, 138, 138, 138, 138,
    138, 138, 155, 155, 155, 155, 155, 155,
};

pub const kSkullWoodsFire_Draw2_Flags = [24]u8{
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 128, 64, 64, 128, 64, 0,
};

pub const kSkullWoodsFire_Draw2_Ext = [24]u8{
    2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
    2, 2, 0, 0, 0, 0, 0, 0,
};

pub const kSuperBombExplode_X = [9]i8{
    0, -16, 0, 16, -24, 24, -16, 0, 16,
};

pub const kSuperBombExplode_Y = [9]i8{
    0, -16, -24, -16, 0, 0, 16, 24, 16,
};

pub const kAncilla_RevivalFaerie_Tab0 = [2]u8{
    0, 144,
};

pub const kAncilla_RevivalFaerie_Tab1 = [5]u8{
    75, 77, 73, 71, 73,
};

pub const kGameOverText_Chars = [16]u8{
    64, 80, 65, 81, 66, 82, 67, 83, 68, 84, 69, 85, 67, 83, 70, 86,
};

pub const kAncilla_Coll_Yoffs = [5]i16{
    0, 8, 8, 8, 0,
};

pub const kAncilla_Coll_Xoffs = [5]i16{
    0, 8, 8, 8, 0,
};

pub const kAncilla_Coll_H = [5]i16{
    20, 20, 8, 28, 14,
};

pub const kAncilla_Coll_W = [5]i16{
    20, 3, 8, 24, 14,
};

pub const kAncilla_Coll_LinkYoffs = [5]i16{
    12, 12, 12, 12, 12,
};

pub const kAncilla_Coll_LinkXoffs = [5]i16{
    8, 8, 8, 12, 8,
};

pub const kEntranceTrigger_BaseY = [4]u16{
    3392, 528, 3324, 256,
};

pub const kEntranceTrigger_BaseX = [4]u16{
    3456, 3688, 304, 3856,
};

pub const kEntranceTrigger_SizeY = [4]u8{
    11, 32, 16, 12,
};

pub const kEntranceTrigger_SizeX = [4]u8{
    16, 16, 16, 16,
};

pub const kAncilla_DrawShadow_Char = [14]u8{
    108, 108, 40, 40, 56, 255, 200, 200, 216, 216, 217, 217, 218, 218,
};

pub const kAncilla_DrawShadow_Flags = [14]u8{
    40, 104, 40, 104, 40, 255, 34, 34, 36, 100, 36, 100, 36, 100,
};

pub const kRadialProjection_Tab0 = [64]u8{
    255, 254, 251, 244, 236, 225, 212, 197, 181, 162, 142, 120, 97, 74, 49, 25,
    0, 25, 49, 74, 97, 120, 142, 162, 181, 197, 212, 225, 236, 244, 251, 254,
    255, 254, 251, 244, 236, 225, 212, 197, 181, 162, 142, 120, 97, 74, 49, 25,
    0, 25, 49, 74, 97, 120, 142, 162, 181, 197, 212, 225, 236, 244, 251, 254,
};

pub const kRadialProjection_Tab2 = [64]u8{
    0, 25, 49, 74, 97, 120, 142, 162, 181, 197, 212, 225, 236, 244, 251, 254,
    255, 254, 251, 244, 236, 225, 212, 197, 181, 162, 142, 120, 97, 74, 49, 25,
    0, 25, 49, 74, 97, 120, 142, 162, 181, 197, 212, 225, 236, 244, 251, 254,
    255, 254, 251, 244, 236, 225, 212, 197, 181, 162, 142, 120, 97, 74, 49, 25,
};

pub const kRadialProjection_Tab1 = [64]u8{
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
};

pub const kRadialProjection_Tab3 = [64]u8{
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
};

pub const kShovelHitStars_XY = [12]i8{
    21, -11, 21, 11, 3, -6, 21, 5, 16, -14, 16, 14,
};

pub const kShovelHitStars_X2 = [6]i8{
    -3, 19, 2, 13, -6, 22,
};

pub const kBomb_Place_X0 = [4]i8{
    8, 8, 0, 16,
};

pub const kBomb_Place_Y0 = [4]i8{
    0, 24, 12, 12,
};

pub const kBomb_Place_X1 = [4]i8{
    8, 8, -6, 22,
};

pub const kBomb_Place_Y1 = [4]i8{
    4, 28, 12, 12,
};

pub const kBoomerang_Tab0 = [4]u8{
    32, 24, 48, 40,
};

pub const kBoomerang_Tab1 = [2]u8{
    32, 96,
};

pub const kBoomerang_Tab2 = [2]u8{
    3, 2,
};

pub const kBoomerang_Tab3 = [4]u8{
    8, 4, 2, 1,
};

pub const kBoomerang_Tab4 = [8]u8{
    8, 4, 2, 1, 9, 5, 10, 6,
};

pub const kBoomerang_Tab5 = [8]u8{
    2, 3, 3, 2, 2, 3, 3, 3,
};

pub const kBoomerang_Tab6 = [8]i8{
    -10, -8, -9, -9, -10, -8, -9, -9,
};

pub const kBoomerang_Tab7 = [8]i8{
    -10, 11, 8, -8, -10, 11, 8, -8,
};

pub const kBoomerang_Tab8 = [8]i8{
    -16, 6, 0, 0, -8, 8, -8, 8,
};

pub const kBoomerang_Tab9 = [8]i8{
    0, 0, -8, 8, 8, 8, -8, -8,
};

pub const kWishPondItem_X = [76]u8{
    4, 4, 4, 4, 4, 0, 0, 4, 4, 4, 4, 4, 5, 0, 0, 0,
    0, 0, 0, 4, 0, 4, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 11, 0, 0, 0, 2, 0, 5, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 4, 4, 0, 4, 0, 0, 0, 4, 0, 0,
};

pub const kWishPondItem_Y = [76]i8{
    -13, -13, -13, -13, -13, -12, -12, -13, -13, -12, -12, -12, -10, -12, -12, -12,
    -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12,
    -12, -12, -12, -13, -12, -12, -12, -12, -12, -12, -10, -12, -12, -12, -12, -12,
    -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12,
    -12, -12, -12, -12, -12, -12, -12, -12, -12, -13, -12, -12,
};

pub const kHappinessPond_Start = [4]i8{
    0, 4, 4, 9,
};

pub const kHappinessPond_End = [4]i8{
    -1, 0, -1, -1,
};

pub const kHappinessPond_Xvel = [10]i8{
    0, -12, -6, 6, 12, -9, -5, 0, 5, 9,
};

pub const kHappinessPond_Yvel = [10]i8{
    -40, -40, -40, -40, -40, -32, -32, -32, -32, -32,
};

pub const kHappinessPond_Zvel = [10]i8{
    20, 20, 20, 20, 20, 16, 16, 16, 16, 16,
};

pub const kFallingItem_Type = [7]i8{
    16, 55, 57, 56, 38, 15, 32,
};

pub const kFallingItem_G = [7]i8{
    64, 0, 0, 0, 0, -1, 0,
};

pub const kFallingItem_X = [7]i16{
    120, 120, 120, 120, 120, 128, 120,
};

pub const kFallingItem_Y = [7]i16{
    72, 120, 120, 120, 120, 104, 120,
};

pub const kFallingItem_Z = [7]u8{
    96, 128, 128, 128, 128, 128, 128,
};

pub const kWeathervane_Tab4 = [12]i8{
    8, 10, 9, 4, 11, 12, -10, -8, 4, -6, -10, -4,
};

pub const kWeathervane_Tab5 = [12]i8{
    20, 22, 20, 20, 22, 20, 20, 22, 20, 22, 20, 20,
};

pub const kWeathervane_Tab6 = [12]u8{
    176, 163, 160, 162, 160, 168, 160, 160, 168, 161, 176, 160,
};

pub const kWeathervane_Tab8 = [12]u8{
    0, 2, 4, 6, 3, 8, 14, 8, 12, 7, 10, 8,
};

pub const kWeathervane_Tab10 = [12]u8{
    48, 18, 32, 20, 22, 24, 32, 20, 24, 22, 20, 32,
};

pub const kLampFlame_X = [4]i8{
    0, 0, -20, 18,
};

pub const kLampFlame_Y = [4]i8{
    -16, 24, 4, 4,
};

pub const kBlastWall_XY = [32]i8{
    -64, 0, -22, 42, -38, 38, -42, 22, 0, 64, 22, 42, 38, 38, 42, 22,
    64, 0, 22, -42, 38, -38, 42, -22, 0, -64, -22, -42, -38, -38, -42, -22,
};

pub const kShootBow_X = [4]i8{
    4, 4, 0, 4,
};

pub const kShootBow_Y = [4]i8{
    -4, 3, 4, 4,
};

pub const kShootBow_Xvel = [4]i8{
    0, 0, -48, 48,
};

pub const kShootBow_Yvel = [4]i8{
    -48, 48, 0, 0,
};

pub const kMagicPower_X = [4]i8{
    -2, -2, -12, 12,
};

pub const kMagicPower_Y = [4]i8{
    0, 20, 16, 16,
};

pub const kMagicPower_X1 = [4]i8{
    10, 10, -8, 28,
};

pub const kMagicPower_Y1 = [4]i8{
    1, 40, 22, 22,
};

pub const kWallTapSpark_X = [4]i8{
    11, 10, -12, 29,
};

pub const kWallTapSpark_Y = [4]i8{
    -4, 32, 17, 17,
};

pub const kAddDashTremor_Dir = [4]u8{
    2, 2, 0, 0,
};

pub const kAddDashTremor_Tab = [2]u8{
    128, 120,
};

pub const kBoomerangWallHit_X = [8]i8{
    8, 8, 0, 10, 12, 8, 4, 0,
};

pub const kBoomerangWallHit_Y = [8]i8{
    0, 8, 8, 8, 4, 8, 12, 8,
};

pub const kBoomerangWallHit_Tab0 = [16]u8{
    0, 6, 4, 0, 2, 10, 12, 0, 0, 8, 14, 0, 0, 0, 0, 0,
};

pub const kHookshotWallHit_X = [8]i8{
    8, 8, 0, 10, 12, 8, 4, 0,
};

pub const kHookshotWallHit_Y = [8]i8{
    0, 8, 8, 8, 4, 8, 12, 8,
};

pub const kSpinAttackStartSparkle_Y = [4]i8{
    32, -8, 10, 20,
};

pub const kSpinAttackStartSparkle_X = [4]i8{
    10, 7, 28, -10,
};

pub const kBlastWall_Tab3 = [4]i8{
    -16, 16, 0, 0,
};

pub const kBlastWall_Tab4 = [4]i8{
    0, 0, -16, 16,
};

pub const kBlastWall_Tab5 = [16]i8{
    -8, 0, -8, 16, 16, 0, 16, 16, 0, -8, 16, -8, 0, 16, 16, 16,
};

pub const kSilverArrowSparkle_X = [4]i8{
    -4, -4, 0, 2,
};

pub const kSilverArrowSparkle_Y = [4]i8{
    0, 2, -4, -4,
};

pub const kIceRod_X = [4]i8{
    0, 0, -20, 20,
};

pub const kIceRod_Y = [4]i8{
    -16, 24, 8, 8,
};

pub const kIceRod_Xvel = [4]i8{
    0, 0, -48, 48,
};

pub const kIceRod_Yvel = [4]i8{
    -48, 48, 0, 0,
};

pub const kMoveGravestone_Y = [8]u16{
    1360, 1344, 1328, 1312, 1280, 1248, 1216, 1200,
};

pub const kMoveGravestone_X = [15]u16{
    2224, 2288, 2320, 2384, 2416, 2464, 2128, 2160,
    2224, 2288, 2336, 2384, 2176, 2448, 2112,
};

pub const kMoveGravestone_Y1 = [15]u16{
    1344, 1328, 1328, 1328, 1312, 1312, 1296, 1296,
    1264, 1264, 1264, 1264, 1232, 1200, 1184,
};

pub const kMoveGravestone_X1 = [15]u16{
    2224, 2288, 2320, 2384, 2416, 2464, 2128, 2160,
    2224, 2288, 2336, 2384, 2176, 2448, 2112,
};

pub const kMoveGravestone_Pos = [15]u16{
    2582, 2462, 2466, 2474, 2350, 2356, 2186, 2190,
    1942, 1950, 1956, 1962, 1680, 1458, 1288,
};

pub const kMoveGravestone_Ctr = [15]u8{
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 56, 88,
};

pub const kMoveGravestone_Idx = [9]u8{
    0, 1, 4, 6, 8, 12, 13, 14, 15,
};

pub const kAncilla_Yoffs_Hb = [12]i8{
    8, 0, -8, 8, 16, 24, 8, 8, 8, 8, 8, 8,
};

pub const kAncilla_Xoffs_Hb = [12]i8{
    0, 0, 0, 0, 0, 0, 0, -8, -16, 0, 8, 16,
};

pub const kAncilla_InitialTileColl_Y = [9]i16{
    15, 16, 28, 24, 12, 12, 12, 12,
    8,
};

pub const kAncilla_InitialTileColl_X = [9]i16{
    8, 8, 8, 8, -1, 0, 17, 16,
    19339,
};

pub const kGiveRupeeGift_Tab = [5]u8{
    1, 5, 20, 100, 50,
};

pub const kMotiveDashDust_Draw_Char = [3]u8{
    169, 207, 223,
};

pub const kSwordBeam_X = [4]i8{
    -8, -10, -22, 4,
};

pub const kSwordBeam_Y = [4]i8{
    -24, 8, -6, -6,
};

pub const kSwordBeam_S = [4]i8{
    -8, -8, -8, 8,
};

pub const kSwordBeam_Tab = [16]u8{
    33, 29, 25, 21, 3, 62, 58, 54, 18, 14, 10, 6, 49, 45, 41, 37,
};

pub const kSwordBeam_Yvel = [4]i8{
    -64, 64, 0, 0,
};

pub const kSwordBeam_Xvel = [4]i8{
    0, 0, -64, 64,
};

pub const kSwordChargeSparkle_A = [4]u8{
    0, 0, 7, 7,
};

pub const kSwordChargeSparkle_B = [4]u8{
    112, 112, 0, 0,
};

pub const kSwordChargeSparkle_X = [4]u8{
    0, 3, 4, 5,
};

pub const kSwordChargeSparkle_Y = [4]u8{
    5, 12, 8, 8,
};
