//! The data behind the exported sprite sheets: which tiles each sprite uses,
//! the tables that pick its palette, and the tiny font the sheets are
//! labelled in. Generated from assets/sprite_sheet_info.py, assets/tables.py
//! and other/3x5_font.png when those were ported; the sheets this draws are
//! checked against the Python's, pixel for pixel.

pub const Entry = struct {
    /// "XX: Name", with an LW or DW suffix for sprites that differ by world.
    name: []const u8,
    /// 0 light world, 1 dark world, 2 dungeon, 3 a sheet given directly.
    dungeon_or_ow: u8,
    tileset: u8,
    palset_idx: u8,
    /// Which of the four VRAM sprite slots the tiles sit in.
    ss_idx: u8,
    /// Rows of 16 tiles: 'x' used by this sprite, '.' not.
    matrix: [4]*const [16]u8,
    /// The palette, when the sheet says; otherwise the sprite's own.
    pal_base: ?u8,
};

pub const kEntries = [_]Entry{
    .{ .name = "00: Raven: LW", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 3, .matrix = .{ "....xxxxxx......", "....xxxxxx......", "................", "................" }, .pal_base = null },
    .{ .name = "00: Raven: DW", .dungeon_or_ow = 1, .tileset = 23, .palset_idx = 13, .ss_idx = 3, .matrix = .{ "....xxxxxx......", "....xxxxxx......", "................", "................" }, .pal_base = null },
    .{ .name = "01: Vulture", .dungeon_or_ow = 0, .tileset = 8, .palset_idx = 4, .ss_idx = 2, .matrix = .{ "xxxxxxxx........", "xxxxxxxx........", "................", "................" }, .pal_base = null },
    .{ .name = "04: PullSwitch", .dungeon_or_ow = 2, .tileset = 6, .palset_idx = 29, .ss_idx = 3, .matrix = .{ "..............xx", "..............xx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "07: PullSwitch2", .dungeon_or_ow = 2, .tileset = 4, .palset_idx = 0, .ss_idx = 2, .matrix = .{ "................", "................", "..xxxx..........", "..xxxx.........." }, .pal_base = null },
    .{ .name = "08: Octorok: LW", .dungeon_or_ow = 0, .tileset = 11, .palset_idx = 3, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xxxx.....xxx....", "xxxx....xxxxx..." }, .pal_base = null },
    .{ .name = "08: Octorok: DW", .dungeon_or_ow = 1, .tileset = 22, .palset_idx = 10, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xxxx.....xxx....", "xxxx....xxxxx..." }, .pal_base = null },
    .{ .name = "09: Moldorm", .dungeon_or_ow = 2, .tileset = 12, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxxx........", "xxxxxxxx........" }, .pal_base = 5 },
    .{ .name = "09: Moldorm", .dungeon_or_ow = 2, .tileset = 12, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "........xxxxxxxx", "........xxxxxxxx" }, .pal_base = 6 },
    .{ .name = "0b: Chicken: LW", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "................", "................", "..........xxxx..", "..........xxxx.." }, .pal_base = null },
    .{ .name = "0b: Chicken: DW", .dungeon_or_ow = 1, .tileset = 21, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "................", "................", "..........xxxx..", "..........xxxx.." }, .pal_base = null },
    .{ .name = "0d: Buzzblob", .dungeon_or_ow = 0, .tileset = 7, .palset_idx = 6, .ss_idx = 3, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "xxxxxx..........", "xxxx............" }, .pal_base = null },
    .{ .name = "0e: SnapDragon", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 0, .matrix = .{ "................", "................", "........xxxx....", "........xxxxxxxx" }, .pal_base = null },
    .{ .name = "0e: SnapDragon", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 2, .matrix = .{ "............xxxx", "............xxxx", "..........xxxxxx", "..........xxxxxx" }, .pal_base = null },
    .{ .name = "0f: Octoballon", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 2, .matrix = .{ "......xx....xx..", "......xx....xx..", "............xx..", ".............x.." }, .pal_base = null },
    .{ .name = "11: Hinox", .dungeon_or_ow = 1, .tileset = 19, .palset_idx = 14, .ss_idx = 0, .matrix = .{ "xxxxxxxx....xxxx", "xxxxxxxx....xxxx", "xxxxxx......xxxx", "xxxxxx.........." }, .pal_base = 3 },
    .{ .name = "12: Moblin", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxx....", "xxxxxxxxxxxx....", "xxxxxxxxxx......", "xxxxxxxxxx......" }, .pal_base = null },
    .{ .name = "13: MiniHelmasaur", .dungeon_or_ow = 2, .tileset = 12, .palset_idx = 26, .ss_idx = 1, .matrix = .{ "..............xx", "............x.xx", "....xxxxxxxxxxxx", "....xxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "15: Antifairy", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 10, .ss_idx = 3, .matrix = .{ "................", "................", ".x.x............", "................" }, .pal_base = 1 },
    .{ .name = "16: Elder", .dungeon_or_ow = 2, .tileset = 16, .palset_idx = 28, .ss_idx = 2, .matrix = .{ "................", "................", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "17: Hoarder", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 3, .matrix = .{ "................", "................", "......xxxx......", "......xxxx......" }, .pal_base = null },
    .{ .name = "18: MiniMoldorm", .dungeon_or_ow = 2, .tileset = 19, .palset_idx = 13, .ss_idx = 1, .matrix = .{ ".............x..", ".............x..", "xxxx............", "xxxx............" }, .pal_base = null },
    .{ .name = "19: Poe: LW", .dungeon_or_ow = 0, .tileset = 3, .palset_idx = 2, .ss_idx = 3, .matrix = .{ "................", "................", "......xx........", "......xx........" }, .pal_base = null },
    .{ .name = "19: Poe: DW", .dungeon_or_ow = 1, .tileset = 21, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "................", "................", "......xx........", "......xx........" }, .pal_base = null },
    .{ .name = "1a: Smithy", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 30, .ss_idx = 1, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "1a: Smithy", .dungeon_or_ow = 0, .tileset = 29, .palset_idx = 0, .ss_idx = 3, .matrix = .{ "........xx......", "........xx......", "................", "................" }, .pal_base = null },
    .{ .name = "1c: Statue", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 3, .matrix = .{ "xxx.............", "xx..............", "................", "................" }, .pal_base = null },
    .{ .name = "1e: CrystalSwitch", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 15, .ss_idx = 3, .matrix = .{ "................", "................", "....xx..........", "....xx.........." }, .pal_base = 1 },
    .{ .name = "1f: SickKid", .dungeon_or_ow = 2, .tileset = 13, .palset_idx = 21, .ss_idx = 0, .matrix = .{ "..........xxxx..", "..........xxxx..", "................", "................" }, .pal_base = 6 },
    .{ .name = "1f: SickKid", .dungeon_or_ow = 2, .tileset = 13, .palset_idx = 21, .ss_idx = 0, .matrix = .{ "..............xx", "..............xx", ".......x......xx", ".......x......xx" }, .pal_base = null },
    .{ .name = "20: Sluggula", .dungeon_or_ow = 2, .tileset = 29, .palset_idx = 17, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xx........xxxxxx", "xx........xxxxxx" }, .pal_base = null },
    .{ .name = "21: PushSwitch", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 3, .matrix = .{ "..........xxxx..", "..........xxxx..", "..........xx....", "..........xx...." }, .pal_base = null },
    .{ .name = "22: Ropa", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 0, .matrix = .{ "........xxxx....", "........xxxx....", "......xx........", "......xx........" }, .pal_base = null },
    .{ .name = "23: RedBari", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 15, .ss_idx = 0, .matrix = .{ "................", "................", "xxxx..xx........", "xxxx..xx........" }, .pal_base = null },
    .{ .name = "25: TalkingTree (S27)", .dungeon_or_ow = 1, .tileset = 19, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "................", "................", "........xx......", "........xx......" }, .pal_base = null },
    .{ .name = "25: TalkingTree (S21)", .dungeon_or_ow = 1, .tileset = 21, .palset_idx = 16, .ss_idx = 0, .matrix = .{ "................", "................", "........xx......", "........xx......" }, .pal_base = null },
    .{ .name = "26: HardhatBeetle", .dungeon_or_ow = 2, .tileset = 19, .palset_idx = 13, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxx...", "xxxxxxxxxxxx....", "................", "................" }, .pal_base = null },
    .{ .name = "27: Deadrock", .dungeon_or_ow = 0, .tileset = 16, .palset_idx = 9, .ss_idx = 3, .matrix = .{ "..xxxxxx........", "..xxxxxx........", "..xxxx..........", "..xxxx.........." }, .pal_base = null },
    .{ .name = "28: DarkWorldHintNpc", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 1, .matrix = .{ "..........xx....", "..........xx....", "..............xx", "..............xx" }, .pal_base = 5 },
    .{ .name = "28: DarkWorldHintNpc", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 0, .matrix = .{ "................", "................", "....xx..........", "....xx.........." }, .pal_base = 5 },
    .{ .name = "28: DarkWorldHintNpc", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 0, .matrix = .{ "....xx..........", "....xx..........", "................", "................" }, .pal_base = 4 },
    .{ .name = "28: DarkWorldHintNpc", .dungeon_or_ow = 2, .tileset = 7, .palset_idx = 7, .ss_idx = 0, .matrix = .{ "..............xx", "..............xx", "..............xx", "..............xx" }, .pal_base = 5 },
    .{ .name = "28: DarkWorldHintNpc", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 28, .ss_idx = 1, .matrix = .{ "................", "................", "..........xxxx..", "..........xxxx.." }, .pal_base = 5 },
    .{ .name = "29: Human/Woman", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 35, .ss_idx = 0, .matrix = .{ "............xxxx", "............xxxx", "................", "................" }, .pal_base = null },
    .{ .name = "29: Human/Woman", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 35, .ss_idx = 3, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "................", "................" }, .pal_base = null },
    .{ .name = "29: Human/Thief", .dungeon_or_ow = 2, .tileset = 40, .palset_idx = 7, .ss_idx = 0, .matrix = .{ "xxxxxxxx..xx..xx", "xxxxxxxx..xx..xx", "xxxxxx......xx..", "xxxxxx......xx.." }, .pal_base = 7 },
    .{ .name = "29: Human/Elder", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 35, .ss_idx = 2, .matrix = .{ "....xxxxxx......", "....xxxxxx......", "..xx............", "..xx............" }, .pal_base = null },
    .{ .name = "2a: SweepingLady", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "................", "................" }, .pal_base = null },
    .{ .name = "2b: Hobo", .dungeon_or_ow = 0, .tileset = 12, .palset_idx = 8, .ss_idx = 2, .matrix = .{ "........xxxx....", "........xxxx....", "......xxxxxxx...", "......xxxxxxx..." }, .pal_base = null },
    .{ .name = "2c: LumberJacks", .dungeon_or_ow = 0, .tileset = 26, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "................", "................", "................", "..............xx" }, .pal_base = 4 },
    .{ .name = "2c: LumberJacks", .dungeon_or_ow = 0, .tileset = 26, .palset_idx = 6, .ss_idx = 0, .matrix = .{ "..............xx", "..............xx", "................", "................" }, .pal_base = null },
    .{ .name = "2c: LumberJacks", .dungeon_or_ow = 0, .tileset = 26, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "................", "................", "....xxxxxx......", "....xxxxxx......" }, .pal_base = null },
    .{ .name = "2e: FluteKid: LW", .dungeon_or_ow = 0, .tileset = 15, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "................", "................", "........xxxx...x", "........xxxx..xx" }, .pal_base = null },
    .{ .name = "2e: FluteKid: DW", .dungeon_or_ow = 1, .tileset = 17, .palset_idx = 11, .ss_idx = 3, .matrix = .{ "............xx..", "............xx..", "............xx..", "............xx.." }, .pal_base = 0 },
    .{ .name = "2e: FluteKid: DW", .dungeon_or_ow = 1, .tileset = 17, .palset_idx = 11, .ss_idx = 3, .matrix = .{ "........xxxx....", "........xxxx....", "......xxxx......", "......xxxx......" }, .pal_base = 3 },
    .{ .name = "2f: MazeGameLady", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "xxxx............", "xxxx............", "xxxxxxxxxx......", "xxxxxxxxxx......" }, .pal_base = null },
    .{ .name = "30: MazeGameGuy", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxx............", "xxxx............", "xx..............", "xx.............." }, .pal_base = null },
    .{ .name = "31: FortuneTeller", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 30, .ss_idx = 0, .matrix = .{ "..........xxxx..", "..........xxxx..", "..........x.x...", "................" }, .pal_base = null },
    .{ .name = "31: FortuneTeller", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 30, .ss_idx = 1, .matrix = .{ "................", "................", "......xxxx......", "......xxxx......" }, .pal_base = null },
    .{ .name = "32: QuarrelBros", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 2, .ss_idx = 0, .matrix = .{ "....xx..xxxx....", "....xx..xxxx....", "................", "................" }, .pal_base = null },
    .{ .name = "34: YoungSnitchLady", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "................", "................", "....xxxxxx......", "....xxxxxx......" }, .pal_base = null },
    .{ .name = "34: YoungSnitchLady", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "..xx............", "..xx............", "....xxxxxx......", "....xxxxxx......" }, .pal_base = null },
    .{ .name = "35: InnKeeper", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 5, .ss_idx = 3, .matrix = .{ "....xxxxxxxxxxxx", "....xxxxxxxxxxxx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "36: Witch", .dungeon_or_ow = 0, .tileset = 13, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "......xx........", "......xx........", "................", "................" }, .pal_base = 1 },
    .{ .name = "36: Witch", .dungeon_or_ow = 0, .tileset = 13, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "39: Locksmith", .dungeon_or_ow = 0, .tileset = 10, .palset_idx = 0, .ss_idx = 3, .matrix = .{ "................", "................", "..........xxxx..", "..........xxxx.." }, .pal_base = null },
    .{ .name = "3a: MagicBat", .dungeon_or_ow = 2, .tileset = 9, .palset_idx = 32, .ss_idx = 3, .matrix = .{ "................", "................", "..........xxxx..", "..........xxxx.x" }, .pal_base = null },
    .{ .name = "3b: TreeTop", .dungeon_or_ow = 0, .tileset = 26, .palset_idx = 6, .ss_idx = 0, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxxxxxxx....", "xxxxxxxxxxxx...." }, .pal_base = 0 },
    .{ .name = "3c: TroughBoy", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxx............", "xxxx............", "................", "................" }, .pal_base = 4 },
    .{ .name = "3c: TroughBoy", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "................", "................", "xx........xx....", "xx........xx...." }, .pal_base = 5 },
    .{ .name = "3d: OldSnitchLady", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "xxxx............", "xxxx............", "xxxxxxxxxx......", "xxxxxxxxxx......" }, .pal_base = null },
    .{ .name = "3e: RockCrab", .dungeon_or_ow = 0, .tileset = 10, .palset_idx = 0, .ss_idx = 3, .matrix = .{ "................", "................", "......xxxx......", "......xxxx......" }, .pal_base = 0 },
    .{ .name = "3e: RockCrab (S16)", .dungeon_or_ow = 0, .tileset = 33, .palset_idx = 0, .ss_idx = 3, .matrix = .{ "................", "................", "......xxxx......", "......xxxx......" }, .pal_base = 0 },
    .{ .name = "3f: PalaceGuard", .dungeon_or_ow = 0, .tileset = 2, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xx..............", "xx..............", "......xxxxx.....", "......xxxxx....." }, .pal_base = 4 },
    .{ .name = "3f: PalaceGuard", .dungeon_or_ow = 0, .tileset = 2, .palset_idx = 1, .ss_idx = 1, .matrix = .{ "xxxxxxxx......xx", "xxxxxxxx......xx", "....xx..........", "....xx.........." }, .pal_base = null },
    .{ .name = "40: ElectricBarrier", .dungeon_or_ow = 0, .tileset = 2, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "..........xxxx..", "..........xxxx..", "......xxxx......", "......xxxx......" }, .pal_base = null },
    .{ .name = "41: Soldier", .dungeon_or_ow = 2, .tileset = 3, .palset_idx = 0, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "41: Soldier (DW)", .dungeon_or_ow = 2, .tileset = 36, .palset_idx = 37, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "41: Soldier (DW)", .dungeon_or_ow = 2, .tileset = 36, .palset_idx = 37, .ss_idx = 2, .matrix = .{ "................", "................", "......xxxxxxxxx.", "......xxxxxxxxx." }, .pal_base = null },
    .{ .name = "44: Warrior", .dungeon_or_ow = 2, .tileset = 33, .palset_idx = 38, .ss_idx = 0, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "................", "................" }, .pal_base = null },
    .{ .name = "47: GrassArcher", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 0, .matrix = .{ "................", "................", "xx..............", "xx.............." }, .pal_base = 1 },
    .{ .name = "47: GrassArcher", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 0, .matrix = .{ "..xxxxxxxxxxxxxx", "..xxxxxxxxxxxxxx", "..xxxx..........", "..xxxx.........." }, .pal_base = null },
    .{ .name = "4a: RedBombKnight", .dungeon_or_ow = 0, .tileset = 1, .palset_idx = 3, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxx.", "xxxxxxxxxxxxxxx.", "..xx........xxxx", "..xx........xxx." }, .pal_base = null },
    .{ .name = "4b: GreenKnifeGuard", .dungeon_or_ow = 0, .tileset = 2, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xx....xxxxxxxxxx", "xx....xxxxxxxxxx" }, .pal_base = null },
    .{ .name = "4c: Geldman", .dungeon_or_ow = 0, .tileset = 8, .palset_idx = 4, .ss_idx = 2, .matrix = .{ "................", "................", "xxxxxxxx........", "xxxxxxxxx......." }, .pal_base = null },
    .{ .name = "4d: Toppo", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 3, .matrix = .{ "xxxx............", "xxxx............", "................", "................" }, .pal_base = null },
    .{ .name = "4e: Popo", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 11, .ss_idx = 1, .matrix = .{ "xxxx............", "xxxx............", "................", "................" }, .pal_base = null },
    .{ .name = "51: ArmosStatue", .dungeon_or_ow = 0, .tileset = 5, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "xx..............", "xx..............", "xx..............", "xx.............." }, .pal_base = 5 },
    .{ .name = "52: ZoraKing", .dungeon_or_ow = 0, .tileset = 14, .palset_idx = 8, .ss_idx = 2, .matrix = .{ "........xxxx....", "........xxxx....", "........x.......", "................" }, .pal_base = 2 },
    .{ .name = "52: ZoraKing", .dungeon_or_ow = 0, .tileset = 14, .palset_idx = 8, .ss_idx = 3, .matrix = .{ "....xxxx........", "....xxxx........", "....xxxx........", "....xxxx........" }, .pal_base = 2 },
    .{ .name = "52: ZoraKing", .dungeon_or_ow = 0, .tileset = 14, .palset_idx = 8, .ss_idx = 3, .matrix = .{ "xxxx............", "xxxx............", "xxxx......xx....", "xxxx......xx...." }, .pal_base = null },
    .{ .name = "53: ArmosKnight", .dungeon_or_ow = 2, .tileset = 9, .palset_idx = 11, .ss_idx = 3, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "54: Lanmolas", .dungeon_or_ow = 2, .tileset = 11, .palset_idx = 4, .ss_idx = 3, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "55: FireBallZora: LW", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 2, .matrix = .{ "........xxxx....", "........xxxx....", "........x.......", "................" }, .pal_base = 2 },
    .{ .name = "55: FireBallZora: LW", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 2, .matrix = .{ "................", "................", "....xxxx........", "....xxxx........" }, .pal_base = null },
    .{ .name = "55: FireBallZora: DW", .dungeon_or_ow = 1, .tileset = 22, .palset_idx = 10, .ss_idx = 2, .matrix = .{ "........xxxx....", "........xxxx....", "........x.......", "................" }, .pal_base = 2 },
    .{ .name = "55: FireBallZora: DW", .dungeon_or_ow = 1, .tileset = 22, .palset_idx = 10, .ss_idx = 2, .matrix = .{ "................", "................", "....xxxx........", "....xxxx........" }, .pal_base = null },
    .{ .name = "56: WalkingZora", .dungeon_or_ow = 0, .tileset = 14, .palset_idx = 8, .ss_idx = 3, .matrix = .{ "........xxxxxxxx", "........xxxxxxxx", "........xx..xxxx", "........xx..xxxx" }, .pal_base = null },
    .{ .name = "57: HyliaObstacle", .dungeon_or_ow = 0, .tileset = 8, .palset_idx = 4, .ss_idx = 2, .matrix = .{ "..............xx", "..............xx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "58: Crab", .dungeon_or_ow = 0, .tileset = 4, .palset_idx = 3, .ss_idx = 2, .matrix = .{ "..............xx", "..............xx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "59: LostWoodsBird", .dungeon_or_ow = 0, .tileset = 12, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "................", "................", "...xxxx.........", "...xxxx........." }, .pal_base = null },
    .{ .name = "5a: LostWoodsSquirrel", .dungeon_or_ow = 0, .tileset = 12, .palset_idx = 1, .ss_idx = 3, .matrix = .{ ".....xx.........", ".....xx.........", ".xx.............", ".xx............." }, .pal_base = null },
    .{ .name = "5b: Spark", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 0, .matrix = .{ "................", "................", "........xx......", "........xx......" }, .pal_base = 2 },
    .{ .name = "5d: Roller", .dungeon_or_ow = 2, .tileset = 30, .palset_idx = 24, .ss_idx = 2, .matrix = .{ "........xxx.....", "........xxx.....", "................", "................" }, .pal_base = null },
    .{ .name = "5f: Roller", .dungeon_or_ow = 2, .tileset = 30, .palset_idx = 24, .ss_idx = 2, .matrix = .{ "..............xx", "..............xx", "..............xx", "................" }, .pal_base = null },
    .{ .name = "61: Beamos", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 1, .matrix = .{ "................", "............x...", "................", "................" }, .pal_base = 1 },
    .{ .name = "61: Beamos", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 1, .matrix = .{ "..........xxx...", "..........xx....", "................", "................" }, .pal_base = 5 },
    .{ .name = "61: Beamos", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 1, .matrix = .{ "........xx......", "........xx......", "........xx......", "........xx......" }, .pal_base = null },
    .{ .name = "62: MasterSword", .dungeon_or_ow = 0, .tileset = 12, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxx........", "xxxxxxxx........", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "62: MasterSword", .dungeon_or_ow = 0, .tileset = 12, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "...xx...........", "...xx...........", "x......xx.......", "x......xx......." }, .pal_base = null },
    .{ .name = "63: DebirandoPit", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 0, .matrix = .{ "..xxxx..........", "..xxxx..........", "..xx....xxxx....", "..xx....xxxx...." }, .pal_base = null },
    .{ .name = "64: Debirando", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 0, .matrix = .{ "xx..............", "xx..............", "xx..............", "xx.............." }, .pal_base = 3 },
    .{ .name = "65: ArcherGame", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 30, .ss_idx = 0, .matrix = .{ "..xxxxxxxx......", "..xxxxxxxx......", "..xxxxxxxx.x....", "xxxxxxxxxxxx...." }, .pal_base = 4 },
    .{ .name = "66: Cannon", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 0, .matrix = .{ "................", "................", "....xx..........", "....xx.........." }, .pal_base = 4 },
    .{ .name = "66: Cannon", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 0, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "6a: MorningStar", .dungeon_or_ow = 2, .tileset = 4, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxx.", "xxxxxxxxxxxxxxx.", "..xx......xxxxxx", "..xx......xxxxxx" }, .pal_base = null },
    .{ .name = "6a: MorningStar", .dungeon_or_ow = 2, .tileset = 4, .palset_idx = 1, .ss_idx = 1, .matrix = .{ "......xxxxxxx.xx", "......xxxxxxx.xx", "xxxxxxxxxxx.....", "xxxxxxxxxxx....." }, .pal_base = null },
    .{ .name = "6b: CannonTrooper", .dungeon_or_ow = 2, .tileset = 4, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxx." }, .pal_base = null },
    .{ .name = "6d: Rat", .dungeon_or_ow = 2, .tileset = 1, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "......xxxxxxxxxx", "......xxxxxxxxxx", "..xx............", "..xx............" }, .pal_base = null },
    .{ .name = "6d: Rat (DW)", .dungeon_or_ow = 2, .tileset = 33, .palset_idx = 35, .ss_idx = 2, .matrix = .{ "......xxxxxxxxxx", "......xxxxxxxxxx", "xxxx............", "xxxx............" }, .pal_base = null },
    .{ .name = "6e: Rope", .dungeon_or_ow = 2, .tileset = 1, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "................", "................", "....xxxxxxxx....", "....xxxxxxxx...." }, .pal_base = null },
    .{ .name = "6e: Rope (DW)", .dungeon_or_ow = 2, .tileset = 33, .palset_idx = 35, .ss_idx = 2, .matrix = .{ "................", "................", "....xxxxxxxx....", "....xxxxxxxx...." }, .pal_base = null },
    .{ .name = "6f: Keese", .dungeon_or_ow = 2, .tileset = 1, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "................", "................" }, .pal_base = null },
    .{ .name = "6f: Keese (DW)", .dungeon_or_ow = 2, .tileset = 33, .palset_idx = 35, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "................", "................" }, .pal_base = null },
    .{ .name = "70: KingHelmasaurFireball", .dungeon_or_ow = 2, .tileset = 21, .palset_idx = 16, .ss_idx = 2, .matrix = .{ "................", "................", "............xx..", "............xx.." }, .pal_base = null },
    .{ .name = "70: KingHelmasaurFireball", .dungeon_or_ow = 2, .tileset = 21, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "..........xxxx..", "..........xxxx.x", "................", "................" }, .pal_base = null },
    .{ .name = "71: Leever", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 0, .matrix = .{ "......xxxx......", "......xxxx......", "......xxx.......", "......xxx......." }, .pal_base = null },
    .{ .name = "72: FairyPond", .dungeon_or_ow = 2, .tileset = 7, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "........xxxxxxxx", "........xxxxxxxx", "................", "................" }, .pal_base = null },
    .{ .name = "72: FairyPond", .dungeon_or_ow = 2, .tileset = 7, .palset_idx = 34, .ss_idx = 3, .matrix = .{ "................", "................", ".........xxxxxxx", ".........xxxxxxx" }, .pal_base = null },
    .{ .name = "73: UncleAndPriest", .dungeon_or_ow = 2, .tileset = 6, .palset_idx = 29, .ss_idx = 0, .matrix = .{ "................", "................", "............xxxx", "............xxxx" }, .pal_base = 0 },
    .{ .name = "73: UncleAndPriest", .dungeon_or_ow = 2, .tileset = 6, .palset_idx = 29, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxx....", "xxxxxxxxxxxx...." }, .pal_base = 4 },
    .{ .name = "73: UncleAndPriest", .dungeon_or_ow = 2, .tileset = 13, .palset_idx = 21, .ss_idx = 0, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxx.xxxxxx..", "xxxxxxx.xxxxxx.." }, .pal_base = 4 },
    .{ .name = "74: RunningMan", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "................", "................", "..........xxxxxx", "..........xxxxxx" }, .pal_base = null },
    .{ .name = "74: RunningMan", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "75: BottleVendor", .dungeon_or_ow = 0, .tileset = 6, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "........xx......", "........xx......", "..xx........xx..", "..xx........xx.." }, .pal_base = null },
    .{ .name = "78: MrsSahasrahla", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 2, .ss_idx = 0, .matrix = .{ "................", "................", "........xx......", "........xx......" }, .pal_base = null },
    .{ .name = "78: MrsSahasrahla", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 2, .ss_idx = 2, .matrix = .{ "..............xx", "..............xx", "................", "................" }, .pal_base = null },
    .{ .name = "7a: Agahnim", .dungeon_or_ow = 2, .tileset = 24, .palset_idx = 27, .ss_idx = 0, .matrix = .{ "............xxxx", "............xxxx", "............xxxx", "............xxxx" }, .pal_base = 6 },
    .{ .name = "7a: Agahnim", .dungeon_or_ow = 2, .tileset = 24, .palset_idx = 27, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 6 },
    .{ .name = "7a: Agahnim", .dungeon_or_ow = 2, .tileset = 24, .palset_idx = 27, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 6 },
    .{ .name = "7a: Agahnim", .dungeon_or_ow = 2, .tileset = 24, .palset_idx = 27, .ss_idx = 3, .matrix = .{ "xxxxxx..xxxx...x", "xxxxxx..xxxx..xx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 6 },
    .{ .name = "7b: AgahnimBalls", .dungeon_or_ow = 2, .tileset = 24, .palset_idx = 27, .ss_idx = 3, .matrix = .{ "......xx....xxx.", "......xx....xx..", "................", "................" }, .pal_base = 2 },
    .{ .name = "7c: StalfosHead", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 11, .ss_idx = 0, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "................", "................" }, .pal_base = null },
    .{ .name = "7d: BigSpikeBlock", .dungeon_or_ow = 2, .tileset = 12, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "....xx..........", "....xx..........", "................", "................" }, .pal_base = null },
    .{ .name = "7e: FireBlade", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 0, .matrix = .{ "................", "................", "........xx......", "........xx......" }, .pal_base = null },
    .{ .name = "81: WaterBug", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "................", "................" }, .pal_base = null },
    .{ .name = "83: GreenEyegore", .dungeon_or_ow = 2, .tileset = 10, .palset_idx = 9, .ss_idx = 2, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxx.." }, .pal_base = null },
    .{ .name = "83: GreenEyegore", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 39, .ss_idx = 1, .matrix = .{ "....xxxx......xx", "....xxxx......xx", "..xxxxxx..xxxxxx", "..xxxxxx..xxxxxx" }, .pal_base = null },
    .{ .name = "85: YellowStalfos", .dungeon_or_ow = 2, .tileset = 25, .palset_idx = 15, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "....xx....xxxxxx", "....xx....xxxxxx" }, .pal_base = null },
    .{ .name = "86: Kodongo", .dungeon_or_ow = 2, .tileset = 25, .palset_idx = 6, .ss_idx = 2, .matrix = .{ "............xx..", "............xx..", "xxxxxxxxxxxxxx..", "xxxxxxxxxxxxxx.." }, .pal_base = null },
    .{ .name = "88: Mothula", .dungeon_or_ow = 2, .tileset = 26, .palset_idx = 14, .ss_idx = 2, .matrix = .{ "xxxxxxxxxx.xxxxx", "xxxxxxxxxx.xxxxx", "xxxxxxxxxx..xxxx", "xxxxxxxxxx..xxxx" }, .pal_base = null },
    .{ .name = "89: MothulaRing", .dungeon_or_ow = 2, .tileset = 26, .palset_idx = 14, .ss_idx = 2, .matrix = .{ "..........x.....", "..........x.....", "..........xx....", "..........xx...." }, .pal_base = null },
    .{ .name = "8a: SpikeBlock", .dungeon_or_ow = 2, .tileset = 8, .palset_idx = 15, .ss_idx = 3, .matrix = .{ "................", "................", "......xx........", "......xx........" }, .pal_base = null },
    .{ .name = "8b: Gibdo", .dungeon_or_ow = 2, .tileset = 19, .palset_idx = 13, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "8c: Arrghus", .dungeon_or_ow = 2, .tileset = 20, .palset_idx = 8, .ss_idx = 2, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxxxxx......" }, .pal_base = null },
    .{ .name = "8e: TerrorPin", .dungeon_or_ow = 2, .tileset = 25, .palset_idx = 15, .ss_idx = 2, .matrix = .{ "..........xx..xx", "..........xx..xx", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "8f: Blob", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 8, .ss_idx = 1, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "x...............", "x..............." }, .pal_base = null },
    .{ .name = "90: WallMaster", .dungeon_or_ow = 2, .tileset = 19, .palset_idx = 13, .ss_idx = 2, .matrix = .{ "................", "................", "......xxxxxxxxxx", "......xxxxxxxxxx" }, .pal_base = null },
    .{ .name = "91: StalfosKnight", .dungeon_or_ow = 2, .tileset = 28, .palset_idx = 19, .ss_idx = 1, .matrix = .{ "......xxxxxxxx..", "......xxxxxxxx..", ".xxxxxxxxxx.....", ".xxxxxxxxxx....." }, .pal_base = null },
    .{ .name = "92: HelmasaurKing", .dungeon_or_ow = 2, .tileset = 21, .palset_idx = 16, .ss_idx = 2, .matrix = .{ "................", "................", "..............xx", "..............xx" }, .pal_base = 6 },
    .{ .name = "92: HelmasaurKing", .dungeon_or_ow = 2, .tileset = 21, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxx............", "xxxx............" }, .pal_base = 6 },
    .{ .name = "92: HelmasaurKing", .dungeon_or_ow = 2, .tileset = 21, .palset_idx = 16, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxx..", "xxxxxxxxxxxxxx.." }, .pal_base = 5 },
    .{ .name = "92: HelmasaurKing", .dungeon_or_ow = 2, .tileset = 21, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "....xxxxxxxxxxxx", "....xxxxxxxxxxxx" }, .pal_base = 5 },
    .{ .name = "93: Bumper", .dungeon_or_ow = 2, .tileset = 12, .palset_idx = 26, .ss_idx = 3, .matrix = .{ "................", "................", "............xx..", "............xx.." }, .pal_base = null },
    .{ .name = "94: Pirogusu", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 2, .matrix = .{ ".......x....xxxx", ".......x....xxxx", "..........xxxxxx", "..........xxxxxx" }, .pal_base = null },
    .{ .name = "95: LaserEye", .dungeon_or_ow = 2, .tileset = 29, .palset_idx = 17, .ss_idx = 3, .matrix = .{ "................", "..x.............", "................", "...x............" }, .pal_base = 2 },
    .{ .name = "95: LaserEye", .dungeon_or_ow = 2, .tileset = 29, .palset_idx = 17, .ss_idx = 3, .matrix = .{ "......xxxx......", "......xxxx......", "................", "................" }, .pal_base = null },
    .{ .name = "99: Pengator", .dungeon_or_ow = 2, .tileset = 28, .palset_idx = 19, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "9a: Kyameron", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 2, .matrix = .{ "......x.xxxx....", "......x.xxxx....", "xxxxxxxxxx......", "xxxxxxxxxx......" }, .pal_base = null },
    .{ .name = "9b: Wizzrobe", .dungeon_or_ow = 2, .tileset = 29, .palset_idx = 17, .ss_idx = 2, .matrix = .{ "......xxxxxxxxxx", "......xxxxxxxxxx", "....xx..........", "..xxxx.........." }, .pal_base = null },
    .{ .name = "9b: Wizzrobe (DW)", .dungeon_or_ow = 2, .tileset = 36, .palset_idx = 37, .ss_idx = 2, .matrix = .{ "......xxxxxxxxxx", "......xxxxxxxxxx", "....xx..........", "..xxxx.........." }, .pal_base = null },
    .{ .name = "9c: Babasu", .dungeon_or_ow = 2, .tileset = 17, .palset_idx = 10, .ss_idx = 1, .matrix = .{ "..............xx", "..............xx", "...........xxxxx", "...........xxxxx" }, .pal_base = 1 },
    .{ .name = "9e: HauntedGroveOstrich", .dungeon_or_ow = 0, .tileset = 15, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xxxxxx..........", "xxxxxx.........." }, .pal_base = null },
    .{ .name = "9f: HauntedGroveRabbit", .dungeon_or_ow = 0, .tileset = 15, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "........xxxxxx..", "........xxxxxx..", "......xx........", "......xx........" }, .pal_base = null },
    .{ .name = "A0: HauntedGroveBird", .dungeon_or_ow = 0, .tileset = 15, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "......xx......xx", "......xx......xx", "............xxx.", "............xx.." }, .pal_base = null },
    .{ .name = "A1: Freezor", .dungeon_or_ow = 2, .tileset = 28, .palset_idx = 19, .ss_idx = 2, .matrix = .{ "................", "................", "......xxxxxxxxxx", "......xxxxxxxxxx" }, .pal_base = null },
    .{ .name = "A2: Kholdstare", .dungeon_or_ow = 2, .tileset = 22, .palset_idx = 20, .ss_idx = 2, .matrix = .{ "xxxxxxxx....xx..", "xxxxxxxx....xx..", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "A4: FallingIce", .dungeon_or_ow = 2, .tileset = 22, .palset_idx = 20, .ss_idx = 2, .matrix = .{ "........xxxx..xx", "........xxxx..xx", "................", "................" }, .pal_base = null },
    .{ .name = "A5: Zazak", .dungeon_or_ow = 2, .tileset = 27, .palset_idx = 23, .ss_idx = 2, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxxxxx......", "xxxxxxxxxx......" }, .pal_base = null },
    .{ .name = "A8: GreenZirro", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 3, .matrix = .{ "................", "................", "................", "...............x" }, .pal_base = 7 },
    .{ .name = "A8: GreenZirro", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 3, .matrix = .{ "xxxxxxxx........", "xxxxxxxx........", "xxxxxxxx........", "xxxxxxxx........" }, .pal_base = null },
    .{ .name = "AA: Pikit", .dungeon_or_ow = 0, .tileset = 19, .palset_idx = 14, .ss_idx = 3, .matrix = .{ "........xxxxxxxx", "........xxxxxxxx", "..........xxxxx.", "..........xxxxx." }, .pal_base = null },
    .{ .name = "AD: OldMan", .dungeon_or_ow = 2, .tileset = 1, .palset_idx = 7, .ss_idx = 2, .matrix = .{ "................", "................", "............xxxx", "............xxxx" }, .pal_base = null },
    .{ .name = "B4: PurpleChest", .dungeon_or_ow = 0, .tileset = 21, .palset_idx = 16, .ss_idx = 0, .matrix = .{ "................", "................", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "B4: PurpleChest", .dungeon_or_ow = 0, .tileset = 21, .palset_idx = 16, .ss_idx = 3, .matrix = .{ "................", "................", "..............xx", "..............xx" }, .pal_base = null },
    .{ .name = "B5: BombShop", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 31, .ss_idx = 1, .matrix = .{ "................", "..............xx", "................", "................" }, .pal_base = 4 },
    .{ .name = "B5: BombShop", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 31, .ss_idx = 1, .matrix = .{ "........xx..xxxx", "........xx..xx..", "................", "................" }, .pal_base = 1 },
    .{ .name = "B6: Kiki", .dungeon_or_ow = 0, .tileset = 23, .palset_idx = 13, .ss_idx = 3, .matrix = .{ "..........xxx.xx", "..........xxxxxx", "............xxxx", "............xxxx" }, .pal_base = null },
    .{ .name = "B9: BullyAndPinkBall", .dungeon_or_ow = 1, .tileset = 20, .palset_idx = 12, .ss_idx = 3, .matrix = .{ "....xx..........", "....xx..........", "xxxx............", "xxxx............" }, .pal_base = 6 },
    .{ .name = "B9: BullyAndPinkBall", .dungeon_or_ow = 1, .tileset = 20, .palset_idx = 12, .ss_idx = 3, .matrix = .{ "xxxx............", "xxxx............", "................", "................" }, .pal_base = null },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 0, .matrix = .{ "xxxx............", "xxxx............", "xxxx............", "xxxx............" }, .pal_base = 5 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "xx..............", "xx..............", "................", "................" }, .pal_base = 1 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "....xx........xx", "....xx........xx", "........xx......", "........xx......" }, .pal_base = 2 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "............xx..", "............xx..", "................", "................" }, .pal_base = 4 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 31, .ss_idx = 1, .matrix = .{ "......xx........", "......xx........", "................", "................" }, .pal_base = 6 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 40, .palset_idx = 5, .ss_idx = 0, .matrix = .{ "xxxxxxxx..xx..xx", "xxxxxxxx..xx..xx", "xxxxxx......xx..", "xxxxxx......xx.." }, .pal_base = 6 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 5, .ss_idx = 0, .matrix = .{ "xxxx............", "xxxx............", "xx..............", "xx.............." }, .pal_base = 6 },
    .{ .name = "BB: Shopkeeper", .dungeon_or_ow = 2, .tileset = 42, .palset_idx = 32, .ss_idx = 0, .matrix = .{ "xxxxxxxx..xx..xx", "xxxxxxxx..xx..xx", "xxxxxx..........", "xxxxxx.........." }, .pal_base = 6 },
    .{ .name = "BC: Drunkard", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 5, .ss_idx = 0, .matrix = .{ "......xx........", "......xx........", "..xx............", "..xx............" }, .pal_base = 4 },
    .{ .name = "BC: Drunkard", .dungeon_or_ow = 2, .tileset = 15, .palset_idx = 5, .ss_idx = 2, .matrix = .{ "................", "................", "..............xx", "................" }, .pal_base = 4 },
    .{ .name = "BD: Viterous", .dungeon_or_ow = 2, .tileset = 22, .palset_idx = 18, .ss_idx = 3, .matrix = .{ "xxxxxxxxxxxx....", "xxxxxxxxxxxx....", "xxxxxxxxxxxx....", "xxxxxxxxxxxx...." }, .pal_base = null },
    .{ .name = "BF: ViterousLightning", .dungeon_or_ow = 2, .tileset = 22, .palset_idx = 18, .ss_idx = 3, .matrix = .{ "............xxxx", "............xxxx", "............xxxx", "............xxxx" }, .pal_base = null },
    .{ .name = "C0: Catfish", .dungeon_or_ow = 0, .tileset = 22, .palset_idx = 10, .ss_idx = 2, .matrix = .{ "......xxxxxxxxx.", "......xxxxxxxxx.", "........x...xxx.", ".............xx." }, .pal_base = null },
    .{ .name = "C1: CutsceneAgahnim", .dungeon_or_ow = 2, .tileset = 18, .palset_idx = 12, .ss_idx = 3, .matrix = .{ "..............x.", "................", "................", "................" }, .pal_base = 2 },
    .{ .name = "C1: CutsceneAgahnim", .dungeon_or_ow = 2, .tileset = 18, .palset_idx = 12, .ss_idx = 0, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xxxxxxxx........", "xxxxxxx........." }, .pal_base = 5 },
    .{ .name = "C1: CutsceneAgahnim", .dungeon_or_ow = 2, .tileset = 18, .palset_idx = 12, .ss_idx = 2, .matrix = .{ "xxxx............", "xxxx............", "xxxx............", "xxxx............" }, .pal_base = 5 },
    .{ .name = "C1: CutsceneAgahnim", .dungeon_or_ow = 2, .tileset = 18, .palset_idx = 12, .ss_idx = 3, .matrix = .{ "................", "...............x", "............xxxx", "............xxxx" }, .pal_base = 5 },
    .{ .name = "C3: Gibo", .dungeon_or_ow = 2, .tileset = 27, .palset_idx = 23, .ss_idx = 2, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "..........xxxxxx", "..........xxxxxx" }, .pal_base = null },
    .{ .name = "C7: Pokey", .dungeon_or_ow = 2, .tileset = 30, .palset_idx = 24, .ss_idx = 2, .matrix = .{ "xxxx............", "xxxx............", "xxxx............", "xxxx............" }, .pal_base = null },
    .{ .name = "C8: BigFairy", .dungeon_or_ow = 2, .tileset = 7, .palset_idx = 7, .ss_idx = 2, .matrix = .{ "..........xxxxxx", "..........xxxxxx", "..........xxxxxx", "..........xxxxxx" }, .pal_base = null },
    .{ .name = "C9: Tektite", .dungeon_or_ow = 1, .tileset = 5, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "........xxxx....", "........xxxx....", "..........xx....", "..........xx...." }, .pal_base = 4 },
    .{ .name = "CA: ChainChomp", .dungeon_or_ow = 2, .tileset = 30, .palset_idx = 24, .ss_idx = 2, .matrix = .{ "......xx...xxx..", "......xx....xx..", "......xxxxxx....", "......xxxxxx...." }, .pal_base = null },
    .{ .name = "CB: Trinexx", .dungeon_or_ow = 2, .tileset = 23, .palset_idx = 25, .ss_idx = 0, .matrix = .{ "....xx..xx......", "....xx..xx......", "....xx..........", "....xx.........." }, .pal_base = 5 },
    .{ .name = "CB: Trinexx", .dungeon_or_ow = 2, .tileset = 23, .palset_idx = 25, .ss_idx = 0, .matrix = .{ "xxxx..xx..xxxxxx", "xxxx..xx..xxxxxx", "xxxx..xxxxxxxxxx", "xxxx..xxxxxxxxxx" }, .pal_base = null },
    .{ .name = "CB: Trinexx", .dungeon_or_ow = 2, .tileset = 23, .palset_idx = 25, .ss_idx = 3, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "CE: Blind", .dungeon_or_ow = 2, .tileset = 32, .palset_idx = 23, .ss_idx = 2, .matrix = .{ "..............xx", "..............xx", "xxxxxx......xxxx", "xxxxxx......xxxx" }, .pal_base = 6 },
    .{ .name = "CE: Blind", .dungeon_or_ow = 2, .tileset = 32, .palset_idx = 23, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxx..", "xxxxxxxxxxxxxx..", "......xxxxxx....", "......xxxxxx...." }, .pal_base = 5 },
    .{ .name = "CF: Swamola", .dungeon_or_ow = 0, .tileset = 22, .palset_idx = 15, .ss_idx = 3, .matrix = .{ "xxxx............", "xxxx............", "xxxxxxxxxxxx....", "xxxxxxxxxxxx...." }, .pal_base = null },
    .{ .name = "D0: Lynel", .dungeon_or_ow = 0, .tileset = 20, .palset_idx = 12, .ss_idx = 3, .matrix = .{ "......xxxxxxxxxx", "......xxxxxxxxxx", "....xxxxxxxxxxxx", "....xxxxxxxxxxxx" }, .pal_base = null },
    .{ .name = "D5: DigGameGuy", .dungeon_or_ow = 0, .tileset = 27, .palset_idx = 18, .ss_idx = 1, .matrix = .{ "xxxxxxx.........", "xxxxxxx.........", "................", "................" }, .pal_base = 5 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 1, .matrix = .{ "....xx..........", "....xx..........", "xxxxxx..........", "xxxxxx.........." }, .pal_base = 4 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 0, .matrix = .{ "..xxxx........xx", "..xxxx........xx", "..xxxx..........", "..xxxx.........." }, .pal_base = 5 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 1, .matrix = .{ "..............xx", "..............xx", "..............xx", "..............xx" }, .pal_base = 5 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 2, .matrix = .{ "....xx..........", "....xx..........", "....xx..........", "....xx.........." }, .pal_base = 5 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 3, .matrix = .{ "......xxxx....xx", "......xxxx....xx", "......xxxx....xx", "......xxxx....xx" }, .pal_base = 5 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 0, .matrix = .{ "xx....xxxxxxxx..", "xx....xxxxxxxx..", "xx....xxxxxxxxxx", "xx....xxxxxxxxxx" }, .pal_base = 6 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 1, .matrix = .{ "xxxx..xxxxxxxx..", "xxxx..xxxxxxxx..", "......xxxxxxxx..", "......xxxxxxxx.." }, .pal_base = 6 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 2, .matrix = .{ "xxxx..xxxxxxxxxx", "xxxx..xxxxxxxxxx", "xxxx..xxxxxxxxxx", "xxxx..xxxxxxxxxx" }, .pal_base = 6 },
    .{ .name = "D6: Ganon", .dungeon_or_ow = 2, .tileset = 34, .palset_idx = 33, .ss_idx = 3, .matrix = .{ "xxxxxx....xxxx..", "xxxxxx....xxxx..", "xxxxxx....xxxx..", "xxxxxx....xxxx.." }, .pal_base = 6 },
    .{ .name = "E7: Mushroom", .dungeon_or_ow = 0, .tileset = 7, .palset_idx = 5, .ss_idx = 3, .matrix = .{ "................", "................", "..............xx", "..............xx" }, .pal_base = 3 },
    .{ .name = "E8: FakeSword", .dungeon_or_ow = 0, .tileset = 7, .palset_idx = 5, .ss_idx = 3, .matrix = .{ "................", "................", "................", "....xx.........." }, .pal_base = null },
    .{ .name = "E9: PotionShop", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 5, .ss_idx = 3, .matrix = .{ "................", "................", "......xx........", "......xx........" }, .pal_base = 2 },
    .{ .name = "ED: SomariaPlatform", .dungeon_or_ow = 2, .tileset = 30, .palset_idx = 24, .ss_idx = 2, .matrix = .{ "................", "................", "............xx..", "............xx.." }, .pal_base = null },
    .{ .name = "EE: MovableMantle", .dungeon_or_ow = 2, .tileset = 3, .palset_idx = 0, .ss_idx = 0, .matrix = .{ "............xxxx", "............xxxx", "............xxxx", "............xxxx" }, .pal_base = null },
    .{ .name = "F2: MedallionTablet", .dungeon_or_ow = 0, .tileset = 8, .palset_idx = 4, .ss_idx = 2, .matrix = .{ "..........xxxx..", "..........xxxx..", "..........xxxx..", "..........xxxx.." }, .pal_base = null },
    .{ .name = "F4: FallingRocks", .dungeon_or_ow = 0, .tileset = 5, .palset_idx = 7, .ss_idx = 3, .matrix = .{ "............xxxx", "............xxxx", "............xxxx", "............xxxx" }, .pal_base = null },
    .{ .name = "XX: Unknown Sheet 00", .dungeon_or_ow = 3, .tileset = 0, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 01", .dungeon_or_ow = 3, .tileset = 1, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 02", .dungeon_or_ow = 3, .tileset = 2, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 03", .dungeon_or_ow = 3, .tileset = 3, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 04", .dungeon_or_ow = 3, .tileset = 4, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 05", .dungeon_or_ow = 3, .tileset = 5, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 06", .dungeon_or_ow = 3, .tileset = 6, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 07", .dungeon_or_ow = 3, .tileset = 7, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 08", .dungeon_or_ow = 3, .tileset = 8, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 09", .dungeon_or_ow = 3, .tileset = 9, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 10", .dungeon_or_ow = 3, .tileset = 10, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 11", .dungeon_or_ow = 3, .tileset = 11, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 14", .dungeon_or_ow = 0, .tileset = 37, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "........xx..xx..", "........xx..xx..", "........xxxx..xx", "........xxxx..xx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 15", .dungeon_or_ow = 0, .tileset = 26, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "..........xxxx..", "..........xxxx..", "............xxxx", "............xxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 21", .dungeon_or_ow = 0, .tileset = 21, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "............xx..", "............xx..", "................", "................" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 27", .dungeon_or_ow = 0, .tileset = 25, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "................", "................", "...............x", "................" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 37", .dungeon_or_ow = 0, .tileset = 93, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "................", "................", "..xx..xxxx......", "......xxxx......" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 39", .dungeon_or_ow = 0, .tileset = 94, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "....xx..........", "....xx.....x....", "....xx..........", "....xx........xx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 41", .dungeon_or_ow = 2, .tileset = 36, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxx..........", "xxxxxx..........", "xxxx...........x", "xx.............x" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 42", .dungeon_or_ow = 0, .tileset = 107, .palset_idx = 1, .ss_idx = 2, .matrix = .{ ".......xxx......", ".......xxx......", "................", "................" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 43", .dungeon_or_ow = 2, .tileset = 16, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 44", .dungeon_or_ow = 0, .tileset = 72, .palset_idx = 1, .ss_idx = 1, .matrix = .{ ".............x..", ".............x..", "xx..............", "xx.............." }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 45", .dungeon_or_ow = 0, .tileset = 45, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 46", .dungeon_or_ow = 0, .tileset = 73, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxx......", "xxxxxxxxxx......", "................", "..............xx" }, .pal_base = 4 },
    .{ .name = "XX: Intro Sheet 50", .dungeon_or_ow = 3, .tileset = 50, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Ending Sheet 52", .dungeon_or_ow = 3, .tileset = 52, .palset_idx = 1, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Ending Sheet 53", .dungeon_or_ow = 3, .tileset = 53, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 54", .dungeon_or_ow = 0, .tileset = 40, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "xxx....x........", "xxx....x........", "................", "................" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 55", .dungeon_or_ow = 0, .tileset = 12, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "............xxxx", "............xxxx", ".............xxx", ".............xxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 72", .dungeon_or_ow = 0, .tileset = 2, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "................", "................", "...........xxxxx", "...........xxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 75", .dungeon_or_ow = 0, .tileset = 27, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "................", "................", ".............x..", "............xx.." }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 76", .dungeon_or_ow = 0, .tileset = 13, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "..............xx", "..............xx", "..........xx....", "..........xx...." }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 82", .dungeon_or_ow = 2, .tileset = 19, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "xxxx......xxxx..", "xx.x......xxxx..", "x.x.....xxxx....", "xxx.....xxxx...." }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 83", .dungeon_or_ow = 2, .tileset = 38, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "...xxxxxxx....xx", "..xxxxxxxx....xx", "xxxxxxxxxx..xxxx", "xxxxxxxxxx..xxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 84", .dungeon_or_ow = 3, .tileset = 84, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 85", .dungeon_or_ow = 2, .tileset = 63, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "......xxxxxx....", "......xxxxxx....", "........xxxx....", ".......xxxxx...." }, .pal_base = 4 },
    .{ .name = "XX: Map Sheet 86", .dungeon_or_ow = 3, .tileset = 86, .palset_idx = 1, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Map Sheet 87", .dungeon_or_ow = 3, .tileset = 87, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 88", .dungeon_or_ow = 3, .tileset = 88, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Tagalong S89", .dungeon_or_ow = 3, .tileset = 89, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 90", .dungeon_or_ow = 2, .tileset = 5, .palset_idx = 1, .ss_idx = 3, .matrix = .{ "..xx..xxxxxx....", "..xx..xxxxxx....", "xxxxxx....xxxxxx", "xxxxxx....xxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 91", .dungeon_or_ow = 3, .tileset = 91, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 92", .dungeon_or_ow = 3, .tileset = 92, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 93", .dungeon_or_ow = 0, .tileset = 43, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxx....", "xxxxxxxxxxxx....", "xxxxxxxxxxxx....", "xxxxxxxxxxxx...." }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 94", .dungeon_or_ow = 3, .tileset = 94, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 95", .dungeon_or_ow = 3, .tileset = 95, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Unknown Sheet 96", .dungeon_or_ow = 3, .tileset = 96, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Map Sheet 97", .dungeon_or_ow = 3, .tileset = 97, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Map Sheet 98", .dungeon_or_ow = 3, .tileset = 98, .palset_idx = 1, .ss_idx = 1, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Map Sheet 99", .dungeon_or_ow = 3, .tileset = 99, .palset_idx = 1, .ss_idx = 2, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Tagalong S100", .dungeon_or_ow = 3, .tileset = 100, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Tagalong S101", .dungeon_or_ow = 3, .tileset = 101, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
    .{ .name = "XX: Tagalong S102", .dungeon_or_ow = 3, .tileset = 102, .palset_idx = 1, .ss_idx = 0, .matrix = .{ "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxx" }, .pal_base = 4 },
};

/// Four sprite sheets for each sprite graphics set, overworld then dungeon.
pub const kSpriteTilesets = [_][4]u8{
    .{ 0, 73, 0, 0 },
    .{ 70, 73, 12, 29 },
    .{ 72, 73, 19, 29 },
    .{ 70, 73, 19, 14 },
    .{ 72, 73, 12, 17 },
    .{ 72, 73, 12, 16 },
    .{ 79, 73, 74, 80 },
    .{ 14, 73, 74, 17 },
    .{ 70, 73, 18, 0 },
    .{ 0, 73, 0, 80 },
    .{ 0, 73, 0, 17 },
    .{ 72, 73, 12, 0 },
    .{ 0, 0, 55, 54 },
    .{ 72, 73, 76, 17 },
    .{ 93, 44, 12, 68 },
    .{ 0, 0, 78, 0 },
    .{ 15, 0, 18, 16 },
    .{ 0, 0, 0, 76 },
    .{ 0, 13, 23, 0 },
    .{ 22, 13, 23, 27 },
    .{ 22, 13, 23, 20 },
    .{ 21, 13, 23, 21 },
    .{ 22, 13, 24, 25 },
    .{ 22, 13, 23, 25 },
    .{ 22, 13, 0, 0 },
    .{ 22, 13, 24, 27 },
    .{ 15, 73, 74, 17 },
    .{ 75, 42, 92, 21 },
    .{ 22, 73, 23, 29 },
    .{ 0, 0, 0, 21 },
    .{ 22, 13, 23, 16 },
    .{ 22, 73, 18, 0 },
    .{ 22, 73, 12, 17 },
    .{ 0, 0, 18, 16 },
    .{ 22, 13, 0, 17 },
    .{ 22, 73, 12, 0 },
    .{ 22, 13, 76, 17 },
    .{ 14, 13, 74, 17 },
    .{ 22, 26, 23, 27 },
    .{ 79, 52, 74, 80 },
    .{ 53, 77, 101, 54 },
    .{ 74, 52, 78, 0 },
    .{ 14, 52, 74, 17 },
    .{ 81, 52, 93, 89 },
    .{ 75, 73, 76, 17 },
    .{ 45, 0, 0, 0 },
    .{ 93, 0, 18, 89 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 71, 73, 43, 45 },
    .{ 70, 73, 28, 82 },
    .{ 0, 73, 28, 82 },
    .{ 93, 73, 0, 82 },
    .{ 70, 73, 19, 82 },
    .{ 75, 77, 74, 90 },
    .{ 71, 73, 28, 82 },
    .{ 75, 77, 57, 54 },
    .{ 31, 44, 46, 82 },
    .{ 31, 44, 46, 29 },
    .{ 47, 44, 46, 82 },
    .{ 47, 44, 46, 49 },
    .{ 31, 30, 48, 82 },
    .{ 81, 73, 19, 0 },
    .{ 79, 73, 19, 80 },
    .{ 79, 77, 74, 80 },
    .{ 75, 73, 76, 43 },
    .{ 31, 32, 34, 83 },
    .{ 85, 61, 66, 67 },
    .{ 31, 30, 35, 82 },
    .{ 31, 30, 57, 58 },
    .{ 31, 30, 58, 62 },
    .{ 31, 30, 60, 61 },
    .{ 64, 30, 39, 63 },
    .{ 85, 26, 66, 67 },
    .{ 31, 30, 42, 82 },
    .{ 31, 30, 56, 82 },
    .{ 31, 32, 40, 82 },
    .{ 31, 32, 38, 82 },
    .{ 31, 44, 37, 82 },
    .{ 31, 32, 39, 82 },
    .{ 31, 30, 41, 82 },
    .{ 31, 44, 59, 82 },
    .{ 70, 73, 36, 82 },
    .{ 33, 65, 69, 51 },
    .{ 31, 44, 40, 49 },
    .{ 31, 13, 41, 82 },
    .{ 31, 30, 39, 82 },
    .{ 31, 32, 39, 83 },
    .{ 72, 73, 19, 82 },
    .{ 14, 30, 74, 80 },
    .{ 31, 32, 38, 83 },
    .{ 21, 0, 0, 0 },
    .{ 31, 0, 42, 82 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 0, 0, 0, 0 },
    .{ 50, 0, 0, 8 },
    .{ 93, 73, 0, 82 },
    .{ 85, 73, 66, 67 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 86, 87, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 86, 87, 80 },
    .{ 97, 86, 99, 80 },
    .{ 97, 86, 87, 80 },
    .{ 97, 86, 51, 80 },
    .{ 97, 86, 87, 80 },
    .{ 97, 98, 99, 80 },
    .{ 97, 98, 99, 80 },
};

/// A dungeon's main palette and three sprite palettes.
pub const kDungPalinfos = [_][4]u8{
    .{ 0, 0, 3, 1 },
    .{ 2, 0, 3, 1 },
    .{ 4, 0, 10, 1 },
    .{ 6, 0, 1, 7 },
    .{ 10, 2, 2, 7 },
    .{ 4, 4, 3, 10 },
    .{ 12, 5, 8, 20 },
    .{ 14, 0, 3, 10 },
    .{ 2, 0, 15, 20 },
    .{ 10, 2, 0, 7 },
    .{ 2, 0, 15, 12 },
    .{ 6, 0, 6, 7 },
    .{ 0, 0, 14, 18 },
    .{ 18, 5, 5, 11 },
    .{ 18, 0, 2, 12 },
    .{ 16, 5, 10, 7 },
    .{ 16, 0, 16, 12 },
    .{ 22, 7, 2, 7 },
    .{ 22, 0, 7, 15 },
    .{ 8, 0, 4, 12 },
    .{ 8, 0, 4, 9 },
    .{ 4, 0, 3, 1 },
    .{ 20, 0, 4, 4 },
    .{ 20, 0, 20, 12 },
    .{ 24, 5, 7, 11 },
    .{ 24, 6, 16, 12 },
    .{ 26, 5, 8, 20 },
    .{ 26, 2, 0, 7 },
    .{ 6, 0, 3, 10 },
    .{ 28, 0, 3, 1 },
    .{ 30, 0, 11, 17 },
    .{ 4, 0, 11, 17 },
    .{ 14, 0, 0, 2 },
    .{ 32, 8, 19, 13 },
    .{ 10, 0, 3, 10 },
    .{ 20, 0, 4, 4 },
    .{ 26, 2, 2, 7 },
    .{ 26, 10, 0, 0 },
    .{ 0, 0, 3, 2 },
    .{ 14, 0, 3, 7 },
    .{ 26, 5, 5, 11 },
};

/// Two sprite palettes for each overworld palette set; -1 for none.
pub const kOwSprPalInfo = [_]i8{ -1, -1, 3, 10, 3, 6, 3, 1, 0, 2, 3, 14, 3, 2, 19, 1, 11, 12, 17, 1, 7, 5, 17, 0, 9, 11, 15, 5, 3, 5, 3, 7, 15, 2, 10, 2, 5, 1, 12, 14 };

/// Each sprite's third init flags byte, whose bits 1 to 3 pick its palette.
pub const kSpriteInit_Flags3 = [_]u8{ 25, 11, 27, 75, 65, 65, 65, 77, 29, 1, 29, 25, 141, 27, 9, 157, 61, 1, 9, 17, 64, 1, 77, 25, 7, 29, 89, 128, 77, 64, 1, 73, 27, 65, 3, 19, 21, 65, 24, 27, 65, 71, 15, 73, 75, 77, 65, 71, 73, 77, 73, 64, 77, 71, 73, 65, 116, 71, 91, 88, 81, 73, 29, 93, 3, 25, 27, 23, 25, 23, 25, 27, 23, 23, 23, 27, 13, 9, 25, 25, 73, 93, 91, 73, 13, 3, 19, 65, 27, 91, 93, 67, 67, 77, 77, 77, 77, 77, 73, 1, 0, 65, 77, 77, 77, 77, 29, 9, 196, 13, 13, 9, 3, 3, 75, 71, 71, 73, 73, 65, 71, 54, 139, 73, 29, 73, 67, 67, 67, 11, 65, 13, 7, 11, 29, 67, 13, 67, 13, 29, 77, 77, 27, 27, 10, 11, 0, 5, 13, 1, 1, 1, 1, 11, 5, 1, 1, 1, 7, 23, 25, 13, 13, 128, 77, 25, 23, 25, 11, 9, 13, 74, 18, 73, 195, 195, 195, 195, 118, 64, 89, 65, 88, 79, 115, 91, 68, 65, 81, 10, 11, 11, 75, 0, 64, 91, 13, 0, 0, 13, 75, 11, 89, 65, 11, 13, 1, 13, 13, 0, 80, 76, 68, 81, 1, 1, 242, 248, 244, 242, 212, 212, 212, 248, 248, 244, 244, 216, 248, 216, 223, 200, 105, 193, 210, 210, 220, 199, 193, 199, 199, 199, 193 };

/// other/3x5_font.png as bits, 128 by 24: a 1 is ink. Characters sit in a
/// 32 by 4 grid of 4 by 6 cells, by ASCII code.
pub const kFont3x5 = [24][16]u8{
    .{ 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee },
    .{ 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xae },
    .{ 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xae },
    .{ 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xae },
    .{ 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee, 0xee },
    .{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
    .{ 0x04, 0xaa, 0x68, 0xc4, 0x28, 0xa0, 0x00, 0x02, 0x64, 0xcc, 0xae, 0x6e, 0xee, 0x00, 0x20, 0x8e },
    .{ 0x04, 0xae, 0xc2, 0xc4, 0x44, 0x44, 0x00, 0x02, 0xac, 0x22, 0xa8, 0x82, 0xaa, 0x44, 0x4e, 0x42 },
    .{ 0x04, 0x0a, 0x64, 0xe0, 0x44, 0xae, 0x0e, 0x04, 0xa4, 0x44, 0xec, 0xe4, 0xee, 0x00, 0x80, 0x24 },
    .{ 0x00, 0x0e, 0xc8, 0xa0, 0x44, 0x04, 0x40, 0x08, 0xa4, 0x82, 0x22, 0xa8, 0xa2, 0x44, 0x4e, 0x40 },
    .{ 0x04, 0x0a, 0x42, 0x60, 0x28, 0x00, 0x80, 0x48, 0xc4, 0xec, 0x2c, 0xe8, 0xec, 0x08, 0x20, 0x84 },
    .{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
    .{ 0x44, 0xc6, 0xce, 0xe6, 0xae, 0x2a, 0x8a, 0xa4, 0xc4, 0xc6, 0xea, 0xaa, 0xaa, 0xee, 0x0e, 0x40 },
    .{ 0xaa, 0xa8, 0xa8, 0x88, 0xa4, 0x2a, 0x8e, 0xea, 0xaa, 0xa8, 0x4a, 0xaa, 0xaa, 0x28, 0x82, 0xa0 },
    .{ 0xee, 0xc8, 0xae, 0xee, 0xe4, 0x2c, 0x8e, 0xea, 0xca, 0xe4, 0x4a, 0xae, 0x44, 0x48, 0x42, 0x00 },
    .{ 0x8a, 0xa8, 0xa8, 0x8a, 0xa4, 0xaa, 0x8a, 0xea, 0x8e, 0xc2, 0x4a, 0x4e, 0xa4, 0x88, 0x22, 0x00 },
    .{ 0x6a, 0xc6, 0xce, 0x86, 0xae, 0x4a, 0xea, 0xa4, 0x86, 0xac, 0x46, 0x4a, 0xa4, 0xee, 0x0e, 0x0e },
    .{ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
    .{ 0x80, 0x80, 0x20, 0x20, 0x84, 0x28, 0xc0, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x06, 0x4c, 0x6e },
    .{ 0x4c, 0xc6, 0x66, 0x46, 0xc0, 0x0a, 0x4e, 0xc4, 0xc6, 0x66, 0xea, 0xaa, 0xaa, 0xe4, 0x44, 0xce },
    .{ 0x06, 0xa8, 0xaa, 0xea, 0xa4, 0x2c, 0x4e, 0xaa, 0xaa, 0x8c, 0x4a, 0xae, 0x4a, 0x68, 0x02, 0x0e },
    .{ 0x0a, 0xa8, 0xac, 0x4e, 0xa4, 0x2c, 0x4e, 0xaa, 0xaa, 0x86, 0x4a, 0xee, 0x46, 0xc4, 0x44, 0x0e },
    .{ 0x0e, 0xc6, 0x66, 0x42, 0xa4, 0xaa, 0xea, 0xa4, 0xc6, 0x8c, 0x66, 0x4e, 0xa2, 0xe6, 0x4c, 0x0e },
    .{ 0x00, 0x00, 0x00, 0x04, 0x00, 0x40, 0x00, 0x00, 0x82, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00 },
};
