//! The dialogue tables of every language the tools can read, generated from
//! the old assets/text_compression.py so not one accented letter got retyped
//! by hand.
//!
//! Each language says how its ROM stores text: the byte where commands
//! start, the byte that jumps to the second block, the byte that ends the
//! lot, where dictionary references begin, and which way commands are
//! encoded when the text is compressed again. The US, English Europe and the
//! fan translations keep the original scheme; German, French and Portuguese
//! use the newer one that frees up more bytes for letters.
const Language = @import("rom.zig").Language;

pub const Encoder = enum { org, new };

pub const Lang = struct {
    /// The name the game and the file names use, like "fr-c".
    code: []const u8,
    alphabet: []const []const u8,
    dictionary: []const []const u8,
    command_names: []const []const u8,
    command_lengths: []const u8,
    rom_addrs: [2]u32,
    command_start: u8,
    switch_bank: u8,
    finish: u8,
    dict_base_enc: u8,
    dict_base_dec: u8,
    /// A byte meaning "the next byte is a letter", for alphabets too big for
    /// the space below the commands.
    escape: ?u8,
    encoder: Encoder,
};

/// The language a code like "fr-c" names; underscores work too, as in the
/// file names.
pub fn fromCode(code: []const u8) ?Language {
    inline for (@typeInfo(Language).@"enum".fields) |f| {
        const lang: Language = @enumFromInt(f.value);
        if (eqlLoose(get(lang).code, code)) return lang;
    }
    return null;
}

fn eqlLoose(a: []const u8, b: []const u8) bool {
    if (a.len != b.len) return false;
    for (a, b) |x, y| {
        const xn = if (x == '_') '-' else x;
        const yn = if (y == '_') '-' else y;
        if (xn != yn) return false;
    }
    return true;
}

pub fn get(lang: Language) *const Lang {
    return switch (lang) {
        .us => &k_us,
        .de => &k_de,
        .fr => &k_fr,
        .fr_c => &k_fr_c,
        .en => &k_en,
        .es => &k_es,
        .pl => &k_pl,
        .pt => &k_pt,
        .redux => &k_redux,
        .nl => &k_nl,
        .sv => &k_sv,
    };
}

const k_us = Lang{
    .code = "us",
    .alphabet = &kAlphabet0,
    .dictionary = &kDictionary0,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};
const k_de = Lang{
    .code = "de",
    .alphabet = &kAlphabet1,
    .dictionary = &kDictionary1,
    .command_names = &kCommandNames1,
    .command_lengths = &kCommandLengths1,
    .rom_addrs = .{ 0x9c8000, 0x8ceb00 },
    .command_start = 0x70,
    .switch_bank = 0x88,
    .finish = 0x8f,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x90,
    .escape = null,
    .encoder = .new,
};
const k_fr = Lang{
    .code = "fr",
    .alphabet = &kAlphabet2,
    .dictionary = &kDictionary2,
    .command_names = &kCommandNames1,
    .command_lengths = &kCommandLengths1,
    .rom_addrs = .{ 0x9c8000, 0x8ce800 },
    .command_start = 0x70,
    .switch_bank = 0x88,
    .finish = 0x8f,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x90,
    .escape = null,
    .encoder = .new,
};
const k_fr_c = Lang{
    .code = "fr-c",
    .alphabet = &kAlphabet2,
    .dictionary = &kDictionary2,
    .command_names = &kCommandNames1,
    .command_lengths = &kCommandLengths1,
    .rom_addrs = .{ 0x9c8000, 0x8cf150 },
    .command_start = 0x70,
    .switch_bank = 0x88,
    .finish = 0x8f,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x90,
    .escape = null,
    .encoder = .new,
};
const k_en = Lang{
    .code = "en",
    .alphabet = &kAlphabet1,
    .dictionary = &kDictionary0,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf60 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};
const k_es = Lang{
    .code = "es",
    .alphabet = &kAlphabet3,
    .dictionary = &kDictionary3,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};
const k_pl = Lang{
    .code = "pl",
    .alphabet = &kAlphabet4,
    .dictionary = &kDictionary4,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};
const k_pt = Lang{
    .code = "pt",
    .alphabet = &kAlphabet5,
    .dictionary = &kDictionary5,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = 0x62,
    .encoder = .new,
};
const k_redux = Lang{
    .code = "redux",
    .alphabet = &kAlphabet0,
    .dictionary = &kDictionary0,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};
const k_nl = Lang{
    .code = "nl",
    .alphabet = &kAlphabet0,
    .dictionary = &kDictionary0,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};
const k_sv = Lang{
    .code = "sv",
    .alphabet = &kAlphabet6,
    .dictionary = &kDictionary6,
    .command_names = &kCommandNames0,
    .command_lengths = &kCommandLengths0,
    .rom_addrs = .{ 0x9c8000, 0x8edf40 },
    .command_start = 0x67,
    .switch_bank = 0x80,
    .finish = 0xff,
    .dict_base_enc = 0x88,
    .dict_base_dec = 0x88,
    .escape = null,
    .encoder = .org,
};

const kAlphabet0 = [_][]const u8{
    "A",         "B",       "C",         "D",         "E",         "F",         "G",         "H",
    "I",         "J",       "K",         "L",         "M",         "N",         "O",         "P",
    "Q",         "R",       "S",         "T",         "U",         "V",         "W",         "X",
    "Y",         "Z",       "a",         "b",         "c",         "d",         "e",         "f",
    "g",         "h",       "i",         "j",         "k",         "l",         "m",         "n",
    "o",         "p",       "q",         "r",         "s",         "t",         "u",         "v",
    "w",         "x",       "y",         "z",         "0",         "1",         "2",         "3",
    "4",         "5",       "6",         "7",         "8",         "9",         "!",         "?",
    "-",         ".",       ",",         "[...]",     ">",         "(",         ")",         "[Ankh]",
    "[Waves]",   "[Snake]", "[LinkL]",   "[LinkR]",   "\"",        "[Up]",      "[Down]",    "[Left]",
    "[Right]",   "'",       "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]", "[4HeartL]",
    "[4HeartR]", " ",       "<",         "[A]",       "[B]",       "[X]",       "[Y]",
};

const kDictionary0 = [_][]const u8{
    "    ", "   ",  "  ",    "'s ",  "and ", "are ", "all ", "ain",
    "and",  "at ",  "ast",   "an",   "at",   "ble",  "ba",   "be",
    "bo",   "can ", "che",   "com",  "ck",   "des",  "di",   "do",
    "en ",  "er ",  "ear",   "ent",  "ed ",  "en",   "er",   "ev",
    "for",  "fro",  "give ", "get",  "go",   "have", "has",  "her",
    "hi",   "ha",   "ight ", "ing ", "in",   "is",   "it",   "just",
    "know", "ly ",  "la",    "lo",   "man",  "ma",   "me",   "mu",
    "n't ", "non",  "not",   "open", "ound", "out ", "of",   "on",
    "or",   "per",  "ple",   "pow",  "pro",  "re ",  "re",   "some",
    "se",   "sh",   "so",    "st",   "ter ", "thin", "ter",  "tha",
    "the",  "thi",  "to",    "tr",   "up",   "ver",  "with", "wa",
    "we",   "wh",   "wi",    "you",  "Her",  "Tha",  "The",  "Thi",
    "You",
};

const kCommandNames0 = [_][]const u8{
    "NextPic", "Choose",       "Item",    "Name",    "Window",      "Number",       "Position",     "ScrollSpd",
    "Selchg",  "Unused_Crash", "Choose3", "Choose2", "Scroll",      "1",            "2",            "3",
    "Color",   "Wait",         "Sound",   "Speed",   "Unused_Mark", "Unused_Mark2", "Unused_Clear", "Waitkey",
};

const kCommandLengths0 = [_]u8{ 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1 };

const kAlphabet1 = [_][]const u8{
    "A",         "B",       "C",         "D",         "E",         "F",         "G",         "H",
    "I",         "J",       "K",         "L",         "M",         "N",         "O",         "P",
    "Q",         "R",       "S",         "T",         "U",         "V",         "W",         "X",
    "Y",         "Z",       "a",         "b",         "c",         "d",         "e",         "f",
    "g",         "h",       "i",         "j",         "k",         "l",         "m",         "n",
    "o",         "p",       "q",         "r",         "s",         "t",         "u",         "v",
    "w",         "x",       "y",         "z",         "0",         "1",         "2",         "3",
    "4",         "5",       "6",         "7",         "8",         "9",         "!",         "?",
    "-",         ".",       ",",         "[...]",     ">",         "(",         ")",         "[Ankh]",
    "[Waves]",   "[Snake]", "[LinkL]",   "[LinkR]",   "\"",        "[UpL]",     "[UpR]",     "[LeftL]",
    "[LeftR]",   "'",       "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]", "[4HeartL]",
    "[4HeartR]", " ",
    "ö",
    "[A]",       "[B]",     "[X]",       "[Y]",
    "ü",
    "ß",
    ":",         "[DownL]", "[DownR]",   "[RightL]",  "[RightR]",
    "è",
    "é",
    "ê",
    "à",
    "ù",
    "ç",
    "Ä",
    "Ö",
    "Ü",
    "ä",
};

const kDictionary1 = [_][]const u8{
    "    ", "   ",    "                                          ", "-Knopf", " ich ",   " Sch",   " Ver",   " zu ",
    " es ", "aber",   "alle",                                       "auch",   "ang",     "aus",    "auf",    "an",
    "bist", "bin",    "bei",                                        "der ",   "die ",    "das ",   "den ",   "dem ",
    "daß",
    "der",  "die",    "das",                                        "den",    "da",      "etwas",  "ein ",   "ein",
    "en ",  "er ",    "es ",                                        "en",     "er",      "es",     "ei",
    "für",
    "fe",   "habe",   "hier",                                       "hast",   "her",     "ich ",   "icht",   "ich",
    "ist",  "ie ",    "im",                                         "ie",     "kannst ", "kannst", "kommen", "kann ",
    "ll",   "mich",   "mein",                                       "mit",    "mal",     "mir",    "nicht ", "nicht",
    "nen",  "nn",     "och ",                                       "och",    "or",      "schon",  "sich",   "sein",
    "sch",  "sie",    "st",                                         "tte",    "te ",     "te",     "und ",   "und",
    "ung",  "um",     "von",                                        "ver",    "vor",     "wird",   "zu ",    "Amulett",
    "Aber", "Deine",  "Dich ",                                      "Dir ",   "Dir",     "Der",    "Die",    "Das",
    "Du ",  "Du",     "Da",                                         "Ein",    "Hyrule",  "Hier",   "Ich ",   "Master-Schwert",
    "Mach", "Rubine", "Sch",                                        "Sie",    "Ver",     "Weisen", "Zelda",
};

const kCommandNames1 = [_][]const u8{
    "Selchg",  "Choose3", "Choose2", "Scroll", "1",      "2",      "3",        "Color",
    "Wait",    "Sound",   "Speed",   "Mark",   "Mark2",  "Clear",  "Waitkey",  "EndMessage",
    "NextPic", "Choose",  "Item",    "Name",   "Window", "Number", "Position", "ScrollSpd",
};

const kCommandLengths1 = [_]u8{ 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2 };

const kAlphabet2 = [_][]const u8{
    "A",         "B",       "C",         "D",         "E",         "F",         "G",         "H",
    "I",         "J",       "K",         "L",         "M",         "N",         "O",         "P",
    "Q",         "R",       "S",         "T",         "U",         "V",         "W",         "X",
    "Y",         "Z",       "a",         "b",         "c",         "d",         "e",         "f",
    "g",         "h",       "i",         "j",         "k",         "l",         "m",         "n",
    "o",         "p",       "q",         "r",         "s",         "t",         "u",         "v",
    "w",         "x",       "y",         "z",         "0",         "1",         "2",         "3",
    "4",         "5",       "6",         "7",         "8",         "9",         "!",         "?",
    "-",         ".",       ",",         "[...]",     ">",         "(",         ")",         "[Ankh]",
    "[Waves]",   "[Snake]", "[LinkL]",   "[LinkR]",   "\"",        "[UpL]",     "[UpR]",     "[LeftL]",
    "[LeftR]",   "'",       "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]", "[4HeartL]",
    "[4HeartR]", " ",
    "ö",
    "[A]",       "[B]",     "[X]",       "[Y]",
    "ü",
    "ô",
    ":",         "[DownL]", "[DownR]",   "[RightL]",  "[RightR]",
    "è",
    "é",
    "ê",
    "à",
    "ù",
    "ç",
    "â",
    "û",
    "î",
    "ä",
};

const kDictionary2 = [_][]const u8{
    "                                          ", " de ",                    " la ",  " le ",       " ! ",   " d",    " p",            " t",
    " !",                                         ", c'est moi, Sahasrahla", ", ",    "ais ",       "as ",   "an",    "ai",            "a ",
    "che",                                        "ce",                      "ch",    "dans ",      "des ",  "de ",   "de",            "est ",
    "ent",                                        "en ",                     "er ",   "es ",        "en",    "es",    "et",            "eu",
    "e,",                                         "e ",                      "ique",  "ien",        "is ",   "ie",    "in",            "ir",
    "is",                                         "i ",                      "les ",  "la ",        "le ",   "le",    "ll",            "maintenant",
    "magique",                                    "ment",                    "mon",   "mai",        "me",    "ne ",   "onne",          "oir",
    "our",                                        "ouv",                     "oi",    "on",         "ou",    "or",    "pouvoir",       "pour",
    "peux",                                       "pas",                     "que ",  "qu",         "rubis", "re ",   "ra",            "re",
    "r ",                                         "sorcier",                 "s l",   "s d",        "se",    "so",    "s ",            "tro",
    "te ",                                        "tu ",                     "te",    "t ",         "un",    "ur",    "u ",            "ver",
    "Ah ! Ah ! Ah !",                             "C'est",                   "Ganon", "Maintenant", "Merci", "Monde", "Perle de Lune",
    "Tu as trouvé ",
    "Ténèbres",
    "Tu peux",                                    "Tu ",
};

const kAlphabet3 = [_][]const u8{
    "A",         "B",         "C",         "D",         "E",         "F",      "G",         "H",
    "I",         "J",         "K",         "L",         "M",         "N",      "O",         "P",
    "Q",         "R",         "S",         "T",         "U",         "V",      "W",
    "é",
    "Y",         "Z",         "a",         "b",         "c",         "d",      "e",         "f",
    "g",         "h",         "i",         "j",         "k",         "l",      "m",         "n",
    "o",         "p",         "q",         "r",         "s",         "t",      "u",         "v",
    "ó",
    "x",         "y",         "z",         "0",         "1",         "2",      "3",         "4",
    "5",         "6",         "7",         "8",         "9",         "!",      "?",         "[Waves]",
    ".",         ",",         "[...]",     ">",         "(",         ")",
    "ñ",
    "ú",
    "á",
    "[LinkL]",   "[LinkR]",   "\"",        "[Up]",      "[Down]",    "[Left]", "[Right]",
    "í",
    "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]", "[Ankh]", "[4HeartR]", " ",
    "[Snake]",   "[A]",       "[B]",       "[X]",       "[Y]",       "[I]",
    "¡",
    "¿",
    "Ñ",
};

const kDictionary3 = [_][]const u8{
    "    ", "   ",  "  ",    " en",  " la ", " el ", " de ", "ien",
    "tra",  " de",  "te ",   "ar",   "a ",   "ada",  "es",   "as",
    "o ",   " con", "ero",   "ado",  "e ",   "que",  "en",   "al",
    "os ",  "ora",  "nte",   " al",  "lo ",  "or",   "os",   "er",
    "aci",  "res",  " que ", " es",  "el",   "los ", "tar",  " se",
    ", ",   "ro",   " de l", " est", "re",   "on",   "an",   "pued",
    " del",
    "ás ",
    "la",   "ti",   "la ",   "Es",   "to",   "ta",   "para", "uer",
    "ier",  " un ", " por",  "oder", "da",   "in",   "cu",   " ha",
    "per",  "ano",  " ve",   "cer",  "lo",   " no ", "ic",   "ra",
    "ab",   "ir",   " una",  "undo", "es ",  "as ",  "con",  "a, ",
    "te",   " m",   "gu",    " tu",  "ando", " p",   "de",   "le",
    "ol",   "o, ",  "ten",   "lle",  " a ",  "aba",  "com",
};

const kAlphabet4 = [_][]const u8{
    "A",         "B",         "C",         "D",         "E",         "F",       "G",       "H",
    "I",         "J",         "K",         "L",         "M",         "N",       "O",       "P",
    "Q",         "R",         "S",         "T",         "U",         "V",       "W",       "X",
    "Y",         "Z",         "a",         "b",         "c",         "d",       "e",       "f",
    "g",         "h",         "i",         "j",         "k",         "l",       "m",       "n",
    "o",         "p",         "q",         "r",         "s",         "t",       "u",       "v",
    "w",         "x",         "y",         "z",         "0",         "1",       "2",       "3",
    "4",         "5",         "6",         "7",         "8",         "9",       "!",       "?",
    "-",         ".",         ",",
    "ć",
    "[Right]",   "(",         ")",         "[Ankh]",    "[Waves]",   "[Snake]", "[LinkL]", "[LinkR]",
    "\"",        "[Up]",      "[Down]",
    "ę",
    "ł",
    "ń",
    "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]",
    "ą",
    "[4HeartR]", " ",         "[Left]",
    "ó",
    "ś",
    "ż",
    "ź",
    "Ł",
    "Ś",
    "Ż",
    "Ź",
};

const kDictionary4 = [_][]const u8{
    "Trój",
    "...",
    "ść",
    "Nie",
    " nie",
    " się",
    "może",
    " że",
    "and",
    "at ",
    " ty",
    "an",
    "at",
    "kus",
    "ba",
    "be",
    "bo",
    "chce",
    "che",
    "ki ",
    "za",
    "des",
    "di",
    "do",
    "en ",
    "er ",
    "sz ",
    "ent",
    "ed ",
    "en",
    "er",
    " w",
    "moc",
    "zię",
    "przez",
    "ale",
    "go",
    "dzie",
    "has",
    "rze",
    "hi",
    "ha",
    "który",
    "aby ",
    "in",
    "is",
    "it",
    "twoj",
    "Może",
    "łeś",
    "la",
    "lo",
    "czn",
    "ma",
    "me",
    "mu",
    "szcz",
    "ska",
    "śli",
    "przy",
    "znaj",
    "iecz",
    "of",
    "on",
    "or",
    "   ",
    "ple",
    "pow",
    "pro",
    "re ",
    "re",
    "mnie",
    "se",
    " z",
    "so",
    "st",
    "któr",
    " jak",
    "ksz",
    "sze",
    "coś",
    " je",
    "to",
    "tr",
    "up",
    "kie",
    "praw",
    "wa",
    "we",
    "mi",
    "wi",
    "szy",
    "chc",
    "pra",
    "cie",
    " i ",
    "esz",
};

const kAlphabet5 = [_][]const u8{
    "A",         "B",       "C",         "D",         "E",         "F",         "G",         "H",
    "I",         "J",       "K",         "L",         "M",         "N",         "O",         "P",
    "Q",         "R",       "S",         "T",         "U",         "V",         "W",         "X",
    "Y",         "Z",       "a",         "b",         "c",         "d",         "e",         "f",
    "g",         "h",       "i",         "j",         "k",         "l",         "m",         "n",
    "o",         "p",       "q",         "r",         "s",         "t",         "u",         "v",
    "w",         "x",       "y",         "z",         "0",         "1",         "2",         "3",
    "4",         "5",       "6",         "7",         "8",         "9",         "!",         "?",
    "-",         ".",       ",",         "[...]",     ">",         "(",         ")",         "[Ankh]",
    "[Waves]",   "[Snake]", "[LinkL]",   "[LinkR]",   "\"",        "[Up]",      "[Down]",    "[Left]",
    "[Right]",   "'",       "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]", "[4HeartL]",
    "[4HeartR]", " ",       "<",         "[A]",       "[B]",       "[X]",       "[Y]",       "[I]",
    "¡",
    "[!]",
    "Á",
    "À",
    "Â",
    "Ã",
    "É",
    "Ê",
    "Í",
    "Ó",
    "Ô",
    "Õ",
    "Ú",
    "á",
    "à",
    "â",
    "ã",
    "é",
    "ê",
    "í",
    "ó",
    "ô",
    "õ",
    "ú",
    "ç",
};

const kDictionary5 = [_][]const u8{
    "     ", "    ", "   ", "                                          ", "o ", "a ",  "e ", "..",
    "de",    "ar",   "s ",  "ra",                                         " d", "es",
    "ocê ",
    "do",    " a",   " p",  "er",                                         " e", "que", "r ", "os",
    "te",    ", ",   "as",  "or",                                         "m ", "en",  " o", "nt",
    "re",    " s",   "co",  "da",                                         "se", "st",  " c", " m",
    "em",    "ma",   "ta",  " n",                                         "ad", "on",  "al", "ro",
    "an",    "u ",   "nd",  " um",                                        "pa", "ca",  "el", " f",
    "to",    "in",   " t",  "ou",                                         "ei", "ss",  "ir", "no",
    "ri",    "tr",   "me",  "la",                                         "ia", "le",  "ve", "is",
    "sa",    "eu",   "pe",  "a.",                                         "na", "so",  "mo", "ga",
    "o.",
    "á ",
    "lo",    "ha",   "pr",  "ua",                                         " l", "! ",  "ui", "am",
    "ti",    "io",   "gu",  "i ",                                         "di", "nh",  " i", "id",
};

const kAlphabet6 = [_][]const u8{
    "A",         "B",         "C",         "D",         "E",         "F",         "G",         "H",
    "I",         "J",         "K",         "L",         "M",         "N",
    "Ö",
    "P",         "Q",         "R",         "S",         "T",         "U",         "V",         "W",
    "X",         "Y",         "Z",         "a",         "b",         "c",         "d",         "e",
    "f",         "g",         "h",         "i",         "j",         "k",         "l",         "m",
    "n",         "o",         "p",         "q",         "r",         "s",         "t",         "u",
    "v",         "w",         "x",         "y",         "z",         "0",         "1",         "2",
    "3",         "4",         "5",         "6",         "7",         "8",         "9",         "!",
    "?",
    "å",
    ".",         ",",
    "ä",
    ">",         "(",         ")",
    "ö",
    "Å",
    "Ä",
    "[LinkL]",   "[LinkR]",   "\"",        "[Up]",      "[Down]",    "[Left]",    "[Right]",   "'",
    "[1HeartL]", "[1HeartR]", "[2HeartL]", "[3HeartL]", "[3HeartR]", "[4HeartL]", "[4HeartR]", " ",
    "<",         "[Ankh]",    "[Waves]",   "[Snake]",   "-",         "[I]",       "[i]",
    "…",
    " ",
};

const kDictionary6 = [_][]const u8{
    "    ", "   ",  "  ",    "Du ",  "till", "vill", "bara", "det",
    "den",  "och",  "en ",   "r ",   "n ",   "ett",  "en",   " d",
    "a ",
    "Hjäl",
    "har",  "ter",  "t ",    "var",  " s",   "de",   "kan",  "med",
    "som",
    "för",
    "att",  "ar",   " h",    "er",   "jag",  "dig",
    "öppna",
    "mig",
    "är",
    "inte", "hit",
    "på ",
    "an",   "e ",   "rupie", "0kej", " m",   "et",   ", ",
    "gång",
    "måst",
    "ten",  " f",   "u ",    "men",  "te",   "tt",   "ka",   "vara",
    "ken",  "0m ",
    "från",
    "myck",
    "någo",
    "in",   " k",   " i",    "vil",  "bar",  "ond",
    "För",
    "Jag",  "ra",   "tack",  "ll",   "g ",   "ta",   "om",   "anna",
    "alla", "en,",  "ber",   "hem",  "han",  "st",   "ig",   " t",
    "tro",  "kraf",
    "ör",
    " v",   "ag",
    "… ",
    "får",
    "sin",  "mme",  "mma",   "en ",  "tat",
};
