//! C ABI declarations for the dungeon modules.
//!
//! These modules used to reach into src/*.h through @cImport while the rest of
//! the port was still C. Every function below is now defined by a Zig module
//! elsewhere in the tree, so these are declarations only and the linker
//! resolves them exactly as the C prototypes did.
//!
//! Signatures are taken from the Zig definitions rather than the headers on
//! purpose: translate-c produced naturally-aligned [*c]u16 prototypes that the
//! align(1) globals could not coerce to, which is why the dungeon modules
//! carried hand-written extern decls alongside the cImport.
const sprite = @import("sprite.zig");
const rtl = @import("zelda_rtl.zig");

pub const SpriteSpawnInfo = sprite.SpriteSpawnInfo;
pub const kUpperBitmasks = rtl.kUpperBitmasks;

// src/dungeon.h
pub const kDoorType_Regular = 0;
pub const kDoorType_Regular2 = 2;
pub const kDoorType_4 = 4;
pub const kDoorType_EntranceDoor = 6;
pub const kDoorType_WaterfallTunnel = 8;
pub const kDoorType_EntranceLarge = 10;
pub const kDoorType_EntranceLarge2 = 12;
pub const kDoorType_EntranceCave = 14;
pub const kDoorType_EntranceCave2 = 16;
pub const kDoorType_ExitToOw = 18;
pub const kDoorType_ThroneRoom = 20;
pub const kDoorType_PlayerBgChange = 22;
pub const kDoorType_ShuttersTwoWay = 24;
pub const kDoorType_InvisibleDoor = 26;
pub const kDoorType_SmallKeyDoor = 0x1c;
pub const kDoorType_1E = 0x1e;
pub const kDoorType_StairMaskLocked0 = 32;
pub const kDoorType_StairMaskLocked1 = 34;
pub const kDoorType_StairMaskLocked2 = 36;
pub const kDoorType_StairMaskLocked3 = 38;
pub const kDoorType_BreakableWall = 0x28;
pub const kDoorType_LgExplosion = 48;
pub const kDoorType_Slashable = 50;
pub const kDoorType_36 = 0x36;
pub const kDoorType_38 = 0x38;
pub const kDoorType_RegularDoor33 = 64;
pub const kDoorType_Shutter = 68;
pub const kDoorType_WarpRoomDoor = 70;
pub const kDoorType_ShutterTrapUR = 72;
pub const kDoorType_ShutterTrapDL = 74;

// src/player.h
pub const kPlayerState_Ground = 0;
pub const kPlayerState_FallingIntoHole = 1;
pub const kPlayerState_RecoilWall = 2;
pub const kPlayerState_SpinAttacking = 3;
pub const kPlayerState_Swimming = 4;
pub const kPlayerState_TurtleRock = 5;
pub const kPlayerState_RecoilOther = 6;
pub const kPlayerState_Electrocution = 7;
pub const kPlayerState_Ether = 8;
pub const kPlayerState_Bombos = 9;
pub const kPlayerState_Quake = 10;
pub const kPlayerState_FallOfLeftRightLedge = 12;
pub const kPlayerState_JumpOffLedgeDiag = 14;
pub const kPlayerState_StartDash = 17;
pub const kPlayerState_StopDash = 18;
pub const kPlayerState_Hookshot = 19;
pub const kPlayerState_Mirror = 20;
pub const kPlayerState_HoldUpItem = 21;
pub const kPlayerState_AsleepInBed = 22;
pub const kPlayerState_PermaBunny = 23;
pub const kPlayerState_ReceivingEther = 25;
pub const kPlayerState_ReceivingBombos = 26;
pub const kPlayerState_OpeningDesertPalace = 27;
pub const kPlayerState_TempBunny = 28;
pub const kPlayerState_PullForRupees = 29;
pub const kPlayerState_SpinAttackMotion = 30;

pub extern fn AdjustWaterHDMAWindow() callconv(.c) void;
pub extern fn AdjustWaterHDMAWindow_X(r10: u16) callconv(.c) void;
pub extern fn AncillaAdd_BlastWall() callconv(.c) void;
pub extern fn AncillaAdd_BushPoof(x: u16, y: u16) callconv(.c) void;
pub extern fn AncillaAdd_DoorDebris() callconv(.c) c_int;
pub extern fn Ancilla_Sfx2_Near(a: u8) callconv(.c) u8;
pub extern fn Ancilla_SpawnFallingPrize(item: u8) callconv(.c) c_int;
pub extern fn Ancilla_TerminateSelectInteractives(y_in: u8) callconv(.c) u8;
pub extern fn ApplyGrayscaleFixed_Incremental() callconv(.c) void;
pub extern fn ApplyLinksMovementToCamera() callconv(.c) void;
pub extern fn ApplyPaletteFilter_bounce() callconv(.c) void;
pub extern fn CacheCameraProperties() callconv(.c) void;
pub extern fn CalculateSfxPan_Arbitrary(a: u8) callconv(.c) u8;
pub extern fn ConditionalMosaicControl() callconv(.c) void;
pub extern fn CrystalCutscene_Initialize() void;
pub extern fn CrystalCutscene_InitializePolyhedral() callconv(.c) void;
pub extern fn DecompressAnimatedDungeonTiles(a: u8) callconv(.c) void;
pub extern fn DidPressButtonForMap() callconv(.c) bool;
pub extern fn DisplaySelectMenu() callconv(.c) void;
pub extern fn DoorDoorStep1_East(door: c_int, dma_ptr_: c_int) callconv(.c) c_int;
pub extern fn DoorDoorStep1_North(door: c_int, dma_ptr_: c_int) callconv(.c) c_int;
pub extern fn DoorDoorStep1_South(door: c_int, dma_ptr_: c_int) callconv(.c) c_int;
pub extern fn DoorDoorStep1_West(door: c_int, dma_ptr_: c_int) callconv(.c) c_int;
pub extern fn Door_Down_EntranceDoor(dsto: u16) void;
pub extern fn Door_Draw_Helper4(door_type: u8, dsto: u16) callconv(.c) void;
pub extern fn Door_Left_EntranceDoor(dsto: u16) void;
pub extern fn Door_LoadBlastWallAttr(k: c_int) callconv(.c) void;
pub extern fn Door_Right_EntranceDoor(dsto: u16) void;
pub extern fn Door_Up_EntranceDoor(dsto: u16) void;
pub extern fn DrawCompletelyOpenDoor() callconv(.c) void;
pub extern fn DrawDoorOpening_Step1(door: c_int, dma_ptr: c_int) callconv(.c) c_int;
pub extern fn DrawDoorToTileMap_East(door: c_int, r4_door: c_int) callconv(.c) void;
pub extern fn DrawDoorToTileMap_North(door: c_int, r4_door: c_int) callconv(.c) void;
pub extern fn DrawDoorToTileMap_South(door: c_int, r4_door: c_int) callconv(.c) void;
pub extern fn DrawDoorToTileMap_West(door: c_int, r4_door: c_int) callconv(.c) void;
pub extern fn DrawEyeWatchDoor(door: c_int) callconv(.c) void;
pub extern fn DrawObjects_LightableTorch(dsto_x2: u16, slot: u16) void;
pub extern fn DrawObjects_PushableBlock(dsto_x2: u16, slot: u16) void;
pub extern fn Dung_TagRoutine_0x00(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x1B(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x22_0x3B(k: c_int, j: u8) void;
pub extern fn Dung_TagRoutine_0x23(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x2A(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x2B(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x2C(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x2D(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x2E(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x2F(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x30(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x34(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x35(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x36(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x37(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x39(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x3A(k: c_int) callconv(.c) void;
pub extern fn Dung_TagRoutine_0x3B(k: c_int) callconv(.c) void;
pub extern fn DungeonTransition_FindSubtileLanding() void;
pub extern fn DungeonTransition_LoadSpriteGFX() callconv(.c) void;
pub extern fn DungeonTransition_ScrollRoom() void;
pub extern fn DungeonTransition_Subtile_ApplyFilter() callconv(.c) void;
pub extern fn DungeonTransition_Subtile_PrepTransition() callconv(.c) void;
pub extern fn DungeonTransition_Subtile_ResetShutters() callconv(.c) void;
pub extern fn DungeonTransition_Subtile_TriggerShutters() callconv(.c) void;
pub extern fn DungeonTransition_TriggerBGC34UpdateAndAdvance() callconv(.c) void;
pub extern fn DungeonTransition_TriggerBGC56UpdateAndAdvance() callconv(.c) void;
pub extern fn Dungeon_AdjustAfterSpiralStairs() void;
pub extern fn Dungeon_AdjustForRoomLayout() void;
pub extern fn Dungeon_AdvanceThenSetBossMusicUnorthodox() callconv(.c) void;
pub extern fn Dungeon_ClearAwayExplodingWall() callconv(.c) void;
pub extern fn Dungeon_DoubleApplyAndIncrementGrayscale() callconv(.c) void;
pub extern fn Dungeon_DrawRoomOverlay(src_: [*]const u8) callconv(.c) void;
pub extern fn Dungeon_ExtinguishTorch() callconv(.c) void;
pub extern fn Dungeon_FlagRoomData_Quadrants() void;
pub extern fn Dungeon_FlipCrystalPegAttribute() callconv(.c) void;
pub extern fn Dungeon_FloodSwampWater_PrepTileMap() callconv(.c) void;
pub extern fn Dungeon_HandleCamera() void;
pub extern fn Dungeon_HandleLayerEffect() void;
pub extern fn Dungeon_HandleRoomTags() callconv(.c) void;
pub extern fn Dungeon_HandleTranslucencyAndPalette() callconv(.c) void;
pub extern fn Dungeon_InitializeRoomFromSpecial() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State10() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State12() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State13() void;
pub extern fn Dungeon_InterRoomTrans_State15() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State3() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State4() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State7() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_State9() callconv(.c) void;
pub extern fn Dungeon_InterRoomTrans_notDarkRoom() callconv(.c) void;
pub extern fn Dungeon_IntraRoomTrans_State5() void;
pub extern fn Dungeon_LoadAndDrawRoom() callconv(.c) void;
pub extern fn Dungeon_LoadAttributeTable() callconv(.c) void;
pub extern fn Dungeon_LoadAttribute_Selectable() callconv(.c) void;
pub extern fn Dungeon_LoadCustomTileAttr() void;
pub extern fn Dungeon_LoadEntrance() callconv(.c) void;
pub extern fn Dungeon_LoadHeader() callconv(.c) void;
pub extern fn Dungeon_LoadPalettes() callconv(.c) void;
pub extern fn Dungeon_LoadRoom() callconv(.c) void;
pub extern fn Dungeon_LoadSingleDoorAttribute(k: c_int) callconv(.c) void;
pub extern fn Dungeon_LoadSingleDoorTileAttribute() callconv(.c) void;
pub extern fn Dungeon_LoadSongBankIfNeeded() callconv(.c) void;
pub extern fn Dungeon_LoadToggleDoorAttr_OtherEntry(door: c_int) callconv(.c) void;
pub extern fn Dungeon_MapVramAddr(pos: u16) u16;
pub extern fn Dungeon_MapVramAddrNoSwap(pos: u16) u16;
pub extern fn Dungeon_OpeningLockedDoor_Combined(skip_anim: bool) callconv(.c) void;
pub extern fn Dungeon_PlayBlipAndCacheQuadrantVisits() callconv(.c) void;
pub extern fn Dungeon_PrepOverlayDma_nextPrep(dst: c_int, r8: u16) callconv(.c) c_int;
pub extern fn Dungeon_PrepOverlayDma_watergate(dst_in: c_int, r8_in: u16, r6: u16, loops: c_int) callconv(.c) c_int;
pub extern fn Dungeon_PrepareNextRoomQuadrantUpload() void;
pub extern fn Dungeon_ProcessTorchesAndDoors() callconv(.c) void;
pub extern fn Dungeon_PushBlock_Handler() callconv(.c) void;
pub extern fn Dungeon_ResetSprites() callconv(.c) void;
pub extern fn Dungeon_ResetTorchBackgroundAndPlayer() callconv(.c) void;
pub extern fn Dungeon_ResetTorchBackgroundAndPlayerInner() callconv(.c) void;
pub extern fn Dungeon_RestoreStarTileChr() callconv(.c) void;
pub extern fn Dungeon_SetAttrForActivatedWater() callconv(.c) void;
pub extern fn Dungeon_SetAttrForActivatedWaterOff() callconv(.c) void;
pub extern fn Dungeon_SetBossMusicUnorthodox() callconv(.c) void;
pub extern fn Dungeon_SpiralStaircase11() callconv(.c) void;
pub extern fn Dungeon_SpiralStaircase12() callconv(.c) void;
pub extern fn Dungeon_SpiralStaircase17() callconv(.c) void;
pub extern fn Dungeon_SpiralStaircase18() callconv(.c) void;
pub extern fn Dungeon_Staircase14() callconv(.c) void;
pub extern fn Dungeon_StartInterRoomTrans_Down() void;
pub extern fn Dungeon_StartInterRoomTrans_Left() void;
pub extern fn Dungeon_StartInterRoomTrans_Right() void;
pub extern fn Dungeon_StartInterRoomTrans_Up() void;
pub extern fn Dungeon_Store2x2(pos: u16, t0: u16, t1: u16, t2: u16, t3: u16, attr: u8) void;
pub extern fn Dungeon_SyncBackgroundsFromSpiralStairs() callconv(.c) void;
pub extern fn Dungeon_UpdateTileMapWithCommonTile(x: c_int, y: c_int, val: u8) callconv(.c) void;
pub extern fn EnableForceBlank() callconv(.c) void;
pub extern fn FloodDam_Expand() callconv(.c) void;
pub extern fn FloodDam_Fill() callconv(.c) void;
pub extern fn FloodDam_PrepFloodHDMA() callconv(.c) void;
pub extern fn FloodDam_PrepTiles_init() callconv(.c) void;
pub extern fn Follower_Initialize() callconv(.c) void;
pub extern fn GetDefaultRoomLayout(i: c_int) [*]const u8;
pub extern fn GetDoorDrawDataIndex_East_clean_door_index(door: c_int) callconv(.c) void;
pub extern fn GetDoorDrawDataIndex_North_clean_door_index(door: c_int) callconv(.c) void;
pub extern fn GetDoorDrawDataIndex_South_clean_door_index(door: c_int) callconv(.c) void;
pub extern fn GetDoorDrawDataIndex_West_clean_door_index(door: c_int) callconv(.c) void;
pub extern fn GetDungeonRoomLayout(i: c_int) [*]const u8;
pub extern fn GetRandomNumber() callconv(.c) u8;
pub extern fn Graphics_IncrementalVRAMUpload() callconv(.c) void;
pub extern fn Graphics_LoadChrHalfSlot() callconv(.c) void;
pub extern fn HandleDungeonLandingFromPit() callconv(.c) void;
pub extern fn HandleIndoorCameraAndDoors() callconv(.c) void;
pub extern fn Hud_FloorIndicator() callconv(.c) void;
pub extern fn Hud_HandleItemSwitchInputs() callconv(.c) void;
pub extern fn Hud_Rebuild() callconv(.c) void;
pub extern fn Hud_RefillLogic() callconv(.c) void;
pub extern fn Hud_RemoveSuperBombIndicator() callconv(.c) void;
pub extern fn Hud_RestoreTorchBackground() callconv(.c) void;
pub extern fn InitializeTilesets() callconv(.c) void;
pub extern fn IrisSpotlight_ConfigureTable() callconv(.c) void;
pub extern fn IrisSpotlight_ResetTable() callconv(.c) void;
pub extern fn LayerEffect_Agahnim2() void;
pub extern fn LayerEffect_Ganon() void;
pub extern fn LayerEffect_InvisibleFloor() void;
pub extern fn LayerEffect_Nothing() void;
pub extern fn LayerEffect_Scroll() void;
pub extern fn LayerEffect_Trinexx() void;
pub extern fn LayerEffect_WaterRapids() void;
pub extern fn LinkOam_Main() callconv(.c) void;
pub extern fn Link_CheckBunnyStatus() void;
pub extern fn Link_CheckForEdgeScreenTransition() callconv(.c) bool;
pub extern fn Link_HandleMovingAnimation_FullLongEntry() callconv(.c) void;
pub extern fn Link_HandleMovingAnimation_StartWithDash() callconv(.c) void;
pub extern fn Link_HandleVelocity() callconv(.c) void;
pub extern fn Link_Main() callconv(.c) void;
pub extern fn Link_MovePosition() callconv(.c) void;
pub extern fn Link_TuckIntoBed() callconv(.c) void;
pub extern fn LoadDungeonSongs() callconv(.c) void;
pub extern fn LoadFollowerGraphics() callconv(.c) void;
pub extern fn LoadGearPalettes_bunny() callconv(.c) void;
pub extern fn LoadNewSpriteGFXSet() callconv(.c) void;
pub extern fn LoadOWMusicIfNeeded() callconv(.c) void;
pub extern fn LoadOverworldSongs() callconv(.c) void;
pub extern fn LoadTransAuxGFX() callconv(.c) void;
pub extern fn LoadTransAuxGFX_sprite() callconv(.c) void;
pub extern fn Main_ShowTextMessage() callconv(.c) void;
pub extern fn MirrorBg1Bg2Offs() void;
pub extern fn Module07_00_PlayerControl() callconv(.c) void;
pub extern fn Module07_01_SubtileTransition() callconv(.c) void;
pub extern fn Module07_02_00_InitializeTransition() callconv(.c) void;
pub extern fn Module07_02_01_LoadNextRoom() callconv(.c) void;
pub extern fn Module07_02_FadedFilter() callconv(.c) void;
pub extern fn Module07_02_SupertileTransition() callconv(.c) void;
pub extern fn Module07_03_OverlayChange() callconv(.c) void;
pub extern fn Module07_04_UnlockDoor() callconv(.c) void;
pub extern fn Module07_05_ControlShutters() callconv(.c) void;
pub extern fn Module07_06_FatInterRoomStairs() callconv(.c) void;
pub extern fn Module07_07_00_HandleMusicAndResetRoom() callconv(.c) void;
pub extern fn Module07_07_06_SyncBG1and2() callconv(.c) void;
pub extern fn Module07_07_0F_FallingFadeIn() callconv(.c) void;
pub extern fn Module07_07_10_LandLinkFromFalling() callconv(.c) void;
pub extern fn Module07_07_11_CacheRoomAndSetMusic() callconv(.c) void;
pub extern fn Module07_07_FallingTransition() callconv(.c) void;
pub extern fn Module07_08_00_InitStairs() callconv(.c) void;
pub extern fn Module07_08_01_ClimbStairs() callconv(.c) void;
pub extern fn Module07_08_NorthIntraRoomStairs() callconv(.c) void;
pub extern fn Module07_09_OpenCrackedDoor() callconv(.c) void;
pub extern fn Module07_0A_ChangeBrightness() callconv(.c) void;
pub extern fn Module07_0B_DrainSwampPool() callconv(.c) void;
pub extern fn Module07_0C_FloodSwampWater() callconv(.c) void;
pub extern fn Module07_0D_FloodDam() callconv(.c) void;
pub extern fn Module07_0E_00_InitPriorityAndScreens() callconv(.c) void;
pub extern fn Module07_0E_01_HandleMusicAndResetProps() callconv(.c) void;
pub extern fn Module07_0E_02_ApplyFilterIf() callconv(.c) void;
pub extern fn Module07_0E_13_SetRoomAndLayerAndCache() callconv(.c) void;
pub extern fn Module07_0E_SpiralStairs() callconv(.c) void;
pub extern fn Module07_0F_00_InitSpotlight() callconv(.c) void;
pub extern fn Module07_0F_01_OperateSpotlight() callconv(.c) void;
pub extern fn Module07_0F_LandingWipe() callconv(.c) void;
pub extern fn Module07_10_00_InitStairs() callconv(.c) void;
pub extern fn Module07_10_01_ClimbStairs() callconv(.c) void;
pub extern fn Module07_10_SouthIntraRoomStairs() callconv(.c) void;
pub extern fn Module07_11_00_PrepAndReset() callconv(.c) void;
pub extern fn Module07_11_01_FadeOut() callconv(.c) void;
pub extern fn Module07_11_02_LoadAndPrepRoom() callconv(.c) void;
pub extern fn Module07_11_03_FilterAndLoadBGChars() callconv(.c) void;
pub extern fn Module07_11_04_FilterDoBGAndResetSprites() callconv(.c) void;
pub extern fn Module07_11_09_LoadSpriteGraphics() callconv(.c) void;
pub extern fn Module07_11_0A_ScrollCamera() void;
pub extern fn Module07_11_0B_PrepDestination() callconv(.c) void;
pub extern fn Module07_11_11_KeepSliding() callconv(.c) void;
pub extern fn Module07_11_19_SetSongAndFilter() callconv(.c) void;
pub extern fn Module07_11_StraightInterroomStairs() callconv(.c) void;
pub extern fn Module07_14_RecoverFromFall() callconv(.c) void;
pub extern fn Module07_15_01_ApplyMosaicAndFilter() callconv(.c) void;
pub extern fn Module07_15_04_SyncRoomPropsAndBuildOverlay() callconv(.c) void;
pub extern fn Module07_15_0E_FadeInFromWarp() callconv(.c) void;
pub extern fn Module07_15_0F_FinalizeAndCacheEntry() callconv(.c) void;
pub extern fn Module07_15_WarpPad() callconv(.c) void;
pub extern fn Module07_16_UpdatePegs() callconv(.c) void;
pub extern fn Module07_16_UpdatePegs_Step1() callconv(.c) void;
pub extern fn Module07_16_UpdatePegs_Step2() callconv(.c) void;
pub extern fn Module07_17_PressurePlate() callconv(.c) void;
pub extern fn Module07_18_RescuedMaiden() callconv(.c) void;
pub extern fn Module07_19_MirrorFade() callconv(.c) void;
pub extern fn Module07_1A_RoomDraw_OpenTriforceDoor_bounce() callconv(.c) void;
pub extern fn Module_PreDungeon_setAmbientSfx() callconv(.c) void;
pub extern fn MovingWall_FillReplacementBuffer(dsto: c_int) void;
pub extern fn NMI_UploadTilemap() callconv(.c) void;
pub extern fn Oam_AllocateFromRegionB(num: u8) callconv(.c) u8;
pub extern fn Object_Draw_DoorLeft_3x4(src: u16, door: c_int) void;
pub extern fn Object_Draw_DoorRight_3x4(src: u16, door: c_int) void;
pub extern fn Object_SizeAtoAplus15(a: u8) void;
pub extern fn OpenCrackedDoor() callconv(.c) void;
pub extern fn OperateShutterDoors() callconv(.c) void;
pub extern fn OrientLampLightCone() void;
pub extern fn Overworld_BombTiles32x32(x_in: u16, y_in: u16) callconv(.c) void;
pub extern fn Overworld_CopyPalettesToCache() callconv(.c) void;
pub extern fn Overworld_ResetMosaic_alwaysIncrease() callconv(.c) void;
pub extern fn PaletteFilter_Crystal() callconv(.c) void;
pub extern fn PaletteFilter_RestoreBGSubstractiveStrict() callconv(.c) void;
pub extern fn Palette_AssertTranslucencySwap() callconv(.c) void;
pub extern fn Palette_RevertTranslucencySwap() callconv(.c) void;
pub extern fn Polyhedral_InitializeThread() callconv(.c) void;
pub extern fn PrepTransAuxGfx() callconv(.c) void;
pub extern fn PrepareDungeonExitFromBossFight() callconv(.c) void;
pub extern fn PushBlock_HandleFalling(y_: u8) callconv(.c) void;
pub extern fn PushBlock_Slide(j: u8) callconv(.c) void;
pub extern fn RecoverPegGFXFromMapping() callconv(.c) void;
pub extern fn RecoverPositionAfterDrowning() callconv(.c) void;
pub extern fn ResetStarTileGraphics() callconv(.c) void;
pub extern fn ResetThenCacheRoomEntryProperties() callconv(.c) void;
pub extern fn ResetTransitionPropsAndAdvance_ResetInterface() callconv(.c) void;
pub extern fn RoomDraw_AdjustTorchLightingChange(x_in: u16, y: u16, r8: u16) callconv(.c) void;
pub extern fn RoomDraw_AgahnimsWindows(dsto: u16) callconv(.c) void;
pub extern fn RoomDraw_CheckIfWallIsMoved() bool;
pub extern fn RoomDraw_FlagDoorsAndGetFinalType(direction: u8, door_type: u8, dsto: u16) callconv(.c) c_int;
pub extern fn RoomDraw_FortuneTellerRoom(dsto: u16) callconv(.c) void;
pub extern fn RoomDraw_GetObjectSize_1to15or26() void;
pub extern fn RoomDraw_GetObjectSize_1to15or32() void;
pub extern fn RoomDraw_GetObjectSize_1to16() void;
pub extern fn RoomDraw_MakeDoorPartsHighPriority_X(dsto: u16) void;
pub extern fn RoomDraw_MakeDoorPartsHighPriority_Y(dsto: u16) void;
pub extern fn RoomDraw_SingleLampCone(a: u16, y: u16) void;
pub extern fn RoomTag_Agahnim(k: c_int) callconv(.c) void;
pub extern fn RoomTag_BuildChestStripes(pos_: u16, y: u16) callconv(.c) u16;
pub extern fn RoomTag_ChestHoles0(k: c_int) callconv(.c) void;
pub extern fn RoomTag_GanonDoor(tagidx: c_int) callconv(.c) void;
pub extern fn RoomTag_GetHeartForPrize(k: c_int) callconv(.c) void;
pub extern fn RoomTag_Holes0(k: c_int) callconv(.c) void;
pub extern fn RoomTag_Holes2(k: c_int) callconv(.c) void;
pub extern fn RoomTag_KillRoomBlock(k: c_int) callconv(.c) void;
pub extern fn RoomTag_MovingWallTorchesCheck(k: c_int) callconv(.c) void;
pub extern fn RoomTag_MovingWall_East(k: c_int) callconv(.c) void;
pub extern fn RoomTag_MovingWall_West(k: c_int) callconv(.c) void;
pub extern fn RoomTag_NorthWestTrigger(k: c_int) callconv(.c) void;
pub extern fn RoomTag_OperateWaterFlooring() callconv(.c) void;
pub extern fn RoomTag_PrizeTriggerDoorDoor(k: c_int) callconv(.c) void;
pub extern fn RoomTag_PullSwitchExplodingWall(k: c_int) callconv(.c) void;
pub extern fn RoomTag_PushBlockForChest(k: c_int) callconv(.c) void;
pub extern fn RoomTag_QuadrantTrigger(k: c_int) callconv(.c) void;
pub extern fn RoomTag_RekillableBoss(k: c_int) callconv(.c) void;
pub extern fn RoomTag_RoomTrigger(k: c_int) callconv(.c) void;
pub extern fn RoomTag_RoomTrigger_BlockDoor(k: c_int) callconv(.c) void;
pub extern fn RoomTag_SwitchTrigger_HoldDoor(k: c_int) callconv(.c) void;
pub extern fn RoomTag_SwitchTrigger_ToggleDoor(k: c_int) callconv(.c) void;
pub extern fn RoomTag_Switch_ExplodingWall(k: c_int) callconv(.c) void;
pub extern fn RoomTag_TorchPuzzleChest(k: c_int) callconv(.c) void;
pub extern fn RoomTag_TorchPuzzleDoor(k: c_int) callconv(.c) void;
pub extern fn RoomTag_TriggerChest(k: c_int) callconv(.c) void;
pub extern fn RoomTag_WaterGate(k: c_int) callconv(.c) void;
pub extern fn RoomTag_WaterOff(k: c_int) callconv(.c) void;
pub extern fn RoomTag_WaterOn(k: c_int) callconv(.c) void;
pub extern fn SaveDungeonKeys() void;
pub extern fn SavePalaceDeaths() void;
pub extern fn SetAndSaveVisitedQuadrantFlags() void;
pub extern fn SpiralStairs_MakeNearbyWallsHighPriority_Entering() callconv(.c) void;
pub extern fn SpiralStairs_MakeNearbyWallsLowPriority() callconv(.c) void;
pub extern fn Spotlight_open() callconv(.c) void;
pub extern fn Sprite_CheckIfRoomIsClear() callconv(.c) bool;
pub extern fn Sprite_CheckIfScreenIsClear() callconv(.c) bool;
pub extern fn Sprite_Dungeon_DrawAllPushBlocks() callconv(.c) void;
pub extern fn Sprite_HandlePushedBlocks_One(i_: c_int) void;
pub extern fn Sprite_LoadGraphicsProperties_light_world_only() callconv(.c) void;
pub extern fn Sprite_Main() callconv(.c) void;
pub extern fn Sprite_RepelDash() callconv(.c) void;
pub extern fn Sprite_ResetAll() callconv(.c) void;
pub extern fn Sprite_SpawnDynamically(k: c_int, what: u8, info: *SpriteSpawnInfo) callconv(.c) c_int;
pub extern fn Sprite_SpawnImmediatelySmashedTerrain(what: u8, x: u16, y: u16) callconv(.c) void;
pub extern fn SubtileTransitionCalculateLanding() void;
pub extern fn TileMapPrep_NotWaterOnTag() void;
pub extern fn UsedForStraightInterRoomStaircase() callconv(.c) void;
pub extern fn WaterFlood_BuildOneQuadrantForVRAM() void;
pub extern fn Watergate_Main_State1() callconv(.c) void;
pub extern fn ZeldaGetEntranceMusicTrack(i: c_int) callconv(.c) u8;
pub extern fn ZeldaIsPlayingMusicTrack(track: u8) callconv(.c) bool;
