//! Data tables for player.c, generated by evaluating the C
//! initializers with clang -- macros and enums included. Do not edit by hand.

pub const kSpinAttackDelays = [18]u8{
    1, 0, 0, 0, 0, 3, 0, 0, 1, 0, 3, 3, 3, 3, 4, 4,
    1, 5,
};

pub const kFireBeamSounds = [8]u8{
    1, 2, 3, 4, 0, 9, 18, 27,
};

pub const kTagalongArr1 = [15]i8{
    -1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

pub const kTagalongArr2 = [15]i8{
    -1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
};

pub const kLinkSpinGraphicsByDir = [48]u8{
    10, 11, 10, 6, 7, 8, 9, 2, 3, 4, 5, 10, 0, 1, 0, 2,
    3, 4, 5, 6, 7, 8, 9, 0, 12, 13, 12, 4, 5, 6, 7, 8,
    9, 2, 3, 12, 14, 15, 14, 8, 9, 2, 3, 4, 5, 6, 7, 14,
};

pub const kLinkSpinDelays = [12]u8{
    1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5,
};

pub const kGrabWallDirs = [4]u8{
    4, 8, 1, 2,
};

pub const kGrabWall_AnimSteps = [7]u8{
    0, 1, 2, 3, 1, 2, 3,
};

pub const kGrabWall_AnimTimer = [7]u8{
    0, 5, 5, 12, 5, 5, 12,
};

pub const kCapeDepletionTimers = [3]u8{
    4, 8, 8,
};

pub const kAvoidJudder1 = [32]i8{
    0, 1, 2, 3, 4, 5, 6, 7, 7, 6, 5, 4, 3, 2, 1, 0,
    7, 6, 5, 4, 3, 2, 1, 0, 0, 1, 2, 3, 4, 5, 6, 7,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper2_y = [2]i8{
    -8, 8,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper2_y2 = [2]i8{
    -16, 16,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper2_velz = [8]u8{
    32, 32, 32, 40, 48, 56, 64, 72,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper2_velx = [8]u8{
    16, 28, 28, 28, 28, 28, 28, 28,
};

pub const kLink_Lift_tab = [9]u8{
    84, 82, 80, 255, 81, 83, 85, 86, 87,
};

pub const kLink_Move_Helper6_tab0 = [8]u8{
    8, 8, 23, 23, 8, 23, 8, 23,
};

pub const kLink_Move_Helper6_tab1 = [8]u8{
    0, 15, 0, 15, 0, 0, 15, 15,
};

pub const kLink_Move_Helper6_tab2 = [8]u8{
    23, 23, 8, 8, 8, 23, 8, 23,
};

pub const kLink_Move_Helper6_tab3 = [8]u8{
    0, 15, 0, 15, 15, 15, 0, 0,
};

pub const kSwimmingTab1 = [4]u8{
    2, 0, 1, 0,
};

pub const kSwimmingTab2 = [2]u8{
    32, 8,
};

pub const kLinkItem_MagicCosts = [27]u8{
    16, 8, 4, 32, 16, 8, 8, 4, 2, 8, 4, 2, 8, 4, 2, 16,
    8, 4, 4, 2, 2, 8, 4, 2, 16, 8, 4,
};

pub const kBombosAnimDelays = [20]u8{
    5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 7, 1, 1,
    1, 1, 1, 13,
};

pub const kBombosAnimStates = [20]u8{
    0, 1, 2, 3, 0, 1, 2, 3, 8, 9, 10, 11, 12, 10, 8, 13,
    14, 15, 16, 17,
};

pub const kEtherAnimDelays = [12]u8{
    5, 5, 5, 5, 5, 5, 5, 5, 7, 7, 3, 3,
};

pub const kEtherAnimDelaysNoFlash = [12]u8{
    5, 5, 5, 5, 5, 5, 5, 5, 7, 7, 24, 24,
};

pub const kEtherAnimStates = [12]u8{
    0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7,
};

pub const kQuakeAnimDelays = [12]u8{
    5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 19,
};

pub const kQuakeAnimStates = [12]u8{
    0, 1, 2, 3, 0, 1, 2, 3, 18, 19, 20, 22,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper1_tab1 = [2]i8{
    -8, 8,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper1_tab2 = [2]i8{
    -32, 32,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper1_tab3 = [2]i8{
    -16, 16,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper1_velx = [24]u8{
    20, 20, 20, 24, 24, 24, 24, 28, 28, 36, 36, 36, 36, 36, 36, 38,
    38, 38, 38, 38, 38, 38, 40, 40,
};

pub const kLink_DoMoveXCoord_Outdoors_Helper1_velz = [24]u8{
    20, 20, 20, 20, 20, 20, 20, 24, 24, 32, 32, 32, 36, 36, 36, 38,
    38, 38, 38, 38, 38, 38, 40, 40,
};

pub const kLedgeVelX = [24]u8{
    4, 4, 4, 10, 10, 10, 11, 18, 18, 18, 20, 20, 20, 20, 22, 22,
    26, 26, 26, 26, 28, 28, 28, 28,
};

pub const kLink_Ledge_Func1_dx = [2]i8{
    -8, 8,
};

pub const kLink_Ledge_Func1_dy = [2]i8{
    -9, 9,
};

pub const kLink_Ledge_Func1_bits = [2]u8{
    6, 3,
};

pub const kLink_Ledge_Func1_dy2 = [2]i8{
    -24, 24,
};

pub const kDashTab1 = [3]u8{
    7, 15, 15,
};

pub const kDashTab2 = [4]u8{
    8, 4, 2, 1,
};

pub const kDashCtrlsToDir = [16]u8{
    0, 1, 2, 0, 4, 4, 4, 0, 8, 8, 8, 0, 0, 0, 0, 0,
};

pub const kDashTab6Y = [4]i8{
    24, -24, 0, 0,
};

pub const kDashTab6X = [4]i8{
    0, 0, 24, -24,
};

pub const kDashTabSw11Y = [4]i8{
    1, 0, 0, 0,
};

pub const kDashTabSw11X = [4]i8{
    0, 0, 1, 0,
};

pub const kDashTabSw7Y = [8]u16{
    384, 384, 0, 0, 256, 256, 0, 0,
};

pub const kDashTabSw7X = [8]u16{
    0, 0, 384, 384, 0, 0, 256, 256,
};

pub const kDashTabDir = [4]u8{
    8, 4, 2, 1,
};

pub const kFallHolePitDirs = [4]u8{
    12, 3, 10, 5,
};

pub const kFallHoleDirs = [8]u8{
    5, 6, 9, 10, 4, 8, 1, 2,
};

pub const kFallHoleDirs2 = [8]u8{
    10, 9, 6, 5, 8, 4, 2, 1,
};

pub const kSwimmingTab3 = [9]u16{
    128, 160, 192, 224, 256, 288, 320, 352,
    384,
};

pub const kButtonIndexKeys = [4]u8{
    0, 64, 32, 16,
};

pub const kAbilityBitmasks = [8]u8{
    224, 64, 4, 224, 224, 224, 224, 224,
};

/// Item animation step delays, indexed by player_handler_timer.
///
/// The C item handlers (LinkItem_Rod, LinkItem_Hammer, LinkItem_Bow and
/// LinkItem_CaneOfSomaria) index these with the timer and then, in the very
/// next statement, compare that same timer against 3 - so on the final step
/// they read one byte past the end of a three-entry table. The read is
/// undefined behavior upstream but harmless there, because its result is
/// always dead: every one of those handlers goes on to store 0 into
/// link_delay_timer_spin_attack before anything can read it. The port skips
/// the read on that last step instead of reproducing it, which keeps the
/// behavior identical and keeps Zig's bounds check from firing.
pub const kRodAnimDelays = [3]u8{
    3, 3, 5,
};

pub const kHammerAnimDelays = [3]u8{
    3, 3, 16,
};

pub const kBowDelays = [3]u8{
    3, 3, 8,
};

pub const kMushroomTimer = [10]u8{
    2, 1, 1, 3, 2, 2, 2, 2, 6, 0,
};

pub const kShovelAnimDelay = [6]u8{
    7, 18, 16, 7, 18, 16,
};

pub const kShovelAnimDelay2 = [6]u8{
    0, 1, 2, 0, 1, 2,
};

pub const kHookshotArrA = [4]i8{
    -8, -16, 0, 0,
};

pub const kHookshotArrB = [4]i8{
    0, 0, 4, -12,
};

pub const kHookshotArrC = [4]i8{
    -64, 64, 0, 0,
};

pub const kHookshotArrD = [4]i8{
    0, 0, -64, 64,
};

pub const kByrnaDelays = [4]u8{
    19, 7, 13, 32,
};

pub const kBugNetTimers = [40]u8{
    11, 6, 7, 8, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6,
    7, 8, 1, 2, 9, 4, 5, 6, 7, 8, 1, 2, 3, 4, 10, 8,
    1, 2, 3, 4, 5, 6, 7, 8,
};

pub const kLiftTab0 = [10]u8{
    8, 24, 8, 24, 8, 32, 6, 8, 13, 13,
};

pub const kLiftTab1 = [10]u8{
    0, 1, 0, 1, 0, 1, 0, 1, 2, 3,
};

pub const kLiftTab2 = [29]u8{
    6, 7, 7, 5, 10, 0, 23, 0, 18, 0, 18, 0, 8, 0, 8, 0,
    254, 255, 17, 0, 84, 82, 80, 255, 81, 83, 85, 86, 87,
};

pub const kGrabWall_AnimSteps2 = [10]u8{
    0, 1, 2, 3, 4, 0, 1, 2, 3, 32,
};

pub const kReceiveItemAlternates = [76]u8{
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 68, 255, 255, 255,
    255, 255, 53, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 70, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
};

pub const kMasks = [4]u8{
    7, 11, 13, 14,
};

pub const kLink_DoMoveXCoord_Indoors_dx = [4]u8{
    8, 8, 0, 15,
};

pub const kLink_DoMoveXCoord_Indoors_dy = [4]u8{
    8, 24, 16, 16,
};

pub const kRecoilVelY = [3]u8{
    24, 16, 16,
};

pub const kRecoilVelZ__Link_HopInOrOutOfWater_Y = [3]u8{
    36, 24, 24,
};

pub const kRecoilVelZ__Link_HopInOrOutOfWater_X = [3]u8{
    32, 24, 24,
};

pub const kLink_MoveY_RecoilOther_dy = [32]u8{
    16, 16, 20, 20, 24, 24, 28, 28, 32, 32, 36, 36, 40, 40, 44, 44,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
};

pub const kLink_MoveY_RecoilOther_dz = [32]u8{
    24, 24, 24, 24, 28, 28, 28, 28, 32, 32, 32, 32, 36, 36, 36, 36,
    40, 40, 40, 40, 44, 44, 44, 44, 48, 48, 48, 48, 52, 52, 52, 52,
};

pub const kLink_MoveY_RecoilOther_timer = [32]u8{
    16, 16, 20, 20, 24, 24, 28, 28, 32, 32, 36, 36, 40, 40, 44, 44,
    48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48,
};

pub const kLink_JumpOffLedgeUpDown_dx = [32]u8{
    8, 8, 8, 8, 16, 16, 16, 16, 24, 24, 24, 24, 16, 16, 16, 16,
    8, 20, 20, 20, 24, 24, 24, 24, 28, 28, 28, 28, 32, 32, 32, 32,
};

pub const kLink_JumpOffLedgeUpDown_dy = [32]u8{
    8, 8, 8, 8, 16, 16, 20, 20, 24, 24, 24, 24, 32, 32, 32, 32,
    8, 20, 20, 20, 24, 24, 24, 24, 28, 28, 28, 28, 32, 32, 32, 32,
};

pub const kLink_JumpOffLedgeUpDown_dz = [32]u8{
    32, 32, 32, 32, 32, 32, 32, 32, 36, 36, 36, 36, 40, 40, 40, 40,
    32, 40, 40, 40, 44, 44, 44, 44, 48, 48, 48, 48, 52, 52, 52, 52,
};

pub const kRecoilVelX = [3]u8{
    28, 24, 16,
};

pub const kDoSwordInteractionWithTiles_o = [8]u8{
    10, 6, 14, 2, 12, 4, 8, 0,
};

pub const kDoSwordInteractionWithTiles_x = [40]i8{
    8, 8, 8, 8, 6, 8, -1, 22, 19, 19, 0, 19, 6, 8, -1, 22,
    8, 8, 8, 8, 8, 8, 0, 15, 6, 8, -10, 29, 6, 8, -6, 22,
    6, 8, -4, 22, -4, 22, -4, 22,
};

pub const kDoSwordInteractionWithTiles_y = [40]i8{
    20, 20, 20, 20, 4, 28, 16, 16, 22, 22, 22, 22, 4, 24, 16, 16,
    16, 16, 16, 16, 20, 20, 23, 23, -4, 36, 16, 16, 4, 28, 16, 16,
    4, 28, 16, 16, 4, 4, 28, 28,
};

pub const kChangableDungeonObj_Func1B_y0 = [4]i8{
    -4, 20, 4, 4,
};

pub const kChangableDungeonObj_Func1B_y1 = [4]i8{
    -4, 20, 12, 12,
};

pub const kChangableDungeonObj_Func1B_x0 = [4]i8{
    4, 4, -4, 20,
};

pub const kChangableDungeonObj_Func1B_x1 = [4]i8{
    12, 12, -4, 20,
};

pub const kGetBestActionToPerformOnTile_a = [7]u8{
    0, 1, 0, 0, 2, 1, 2,
};

pub const kGetBestActionToPerformOnTile_b = [7]u8{
    2, 3, 1, 4, 0, 5, 6,
};

pub const kSpeedMod = [27]u8{
    24, 16, 10, 24, 16, 8, 8, 4, 12, 16, 9, 25, 20, 13, 16, 8,
    64, 42, 16, 8, 4, 2, 48, 24, 32, 21, 0,
};

pub const kSwimmingTab4 = [12]i8{
    8, -12, -8, -16, 4, -6, -12, -6, 10, -16, -12, -6,
};

pub const kSwimmingTab5 = [2]u8{
    243, 252,
};

pub const kSwimmingTab6 = [4]u8{
    8, 4, 2, 1,
};

pub const kMovePosDirFlag = [4]u8{
    8, 4, 2, 1,
};

pub const kMovingBeltY = [4]i8{
    -8, 8, 0, 0,
};

pub const kMovingBeltX = [4]i8{
    0, 0, -8, 8,
};

pub const kTab = [4]u8{
    8, 4, 2, 1,
};

pub const kDashTab3 = [7]u8{
    48, 36, 24, 16, 12, 8, 4,
};

pub const kDashTab4 = [56]u8{
    3, 3, 5, 3, 3, 3, 5, 3, 2, 2, 4, 2, 2, 2, 4, 2,
    2, 2, 3, 2, 2, 2, 3, 2, 1, 1, 2, 1, 1, 1, 2, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0,
};

pub const kDashTab5 = [7]u8{
    1, 2, 2, 2, 2, 2, 2,
};

pub const kPushedBlock_Tab1 = [9]u8{
    0, 1, 2, 3, 4, 0, 0, 0, 0,
};

pub const kPushedblock_Char = [4]u8{
    12, 12, 12, 255,
};

pub const kSomarianBlock_Yvel = [4]i8{
    -40, 40, 0, 0,
};

pub const kSomarianBlock_Xvel = [4]i8{
    0, 0, -40, 40,
};

pub const kSomarianBlock_Zvel = [4]i8{
    48, 24, 16, 8,
};

pub const kHookshot_Yvel = [4]i8{
    -64, 64, 0, 0,
};

pub const kHookshot_Xvel = [4]i8{
    0, 0, -64, 64,
};

pub const kHookshot_Yd = [4]i8{
    4, 20, 8, 8,
};

pub const kHookshot_Xd = [4]i8{
    0, 0, -4, 11,
};

pub const kItem_Hammer_SpawnWater_X = [4]i8{
    0, 12, -8, 24,
};

pub const kItem_Hammer_SpawnWater_Y = [4]i8{
    8, 32, 24, 24,
};

pub const kDiggingGameGuy_Xvel = [2]i8{
    -16, 16,
};

pub const kDiggingGameGuy_X = [2]i8{
    0, 19,
};

pub const kDiggingGameGuy_Items = [4]u8{
    219, 218, 217, 223,
};
