//! Memory maps for spc_player, generated from src/spc_player.c -- do not edit by hand.
//! They describe where each SpcPlayer/Channel field lives in the emulated SPC ram.
const audio = @import("audio.zig");
const Channel = audio.Channel;
const SpcPlayer = audio.SpcPlayer;

pub const MemMap = struct { off: usize, org_off: u16 };
pub const MemMapSized = struct { off: usize, org_off: u16, size: usize };

pub const kChannel_Maps = [52]MemMap{
    .{ .off = @offsetOf(Channel, "pattern_order_ptr_for_chan"), .org_off = 0x8030 },
    .{ .off = @offsetOf(Channel, "note_ticks_left"), .org_off = 0x70 },
    .{ .off = @offsetOf(Channel, "note_keyoff_ticks_left"), .org_off = 0x71 },
    .{ .off = @offsetOf(Channel, "subroutine_num_loops"), .org_off = 0x80 },
    .{ .off = @offsetOf(Channel, "volume_fade_ticks"), .org_off = 0x90 },
    .{ .off = @offsetOf(Channel, "pan_num_ticks"), .org_off = 0x91 },
    .{ .off = @offsetOf(Channel, "pitch_slide_length"), .org_off = 0xa0 },
    .{ .off = @offsetOf(Channel, "pitch_slide_delay_left"), .org_off = 0xa1 },
    .{ .off = @offsetOf(Channel, "vibrato_hold_count"), .org_off = 0xb0 },
    .{ .off = @offsetOf(Channel, "vib_depth"), .org_off = 0xb1 },
    .{ .off = @offsetOf(Channel, "tremolo_hold_count"), .org_off = 0xc0 },
    .{ .off = @offsetOf(Channel, "tremolo_depth"), .org_off = 0xc1 },
    .{ .off = @offsetOf(Channel, "vibrato_change_count"), .org_off = 0x100 },
    .{ .off = @offsetOf(Channel, "note_length"), .org_off = 0x200 },
    .{ .off = @offsetOf(Channel, "note_gate_off_fixedpt"), .org_off = 0x201 },
    .{ .off = @offsetOf(Channel, "channel_volume_master"), .org_off = 0x210 },
    .{ .off = @offsetOf(Channel, "instrument_id"), .org_off = 0x211 },
    .{ .off = @offsetOf(Channel, "instrument_pitch_base"), .org_off = 0x8220 },
    .{ .off = @offsetOf(Channel, "saved_pattern_ptr"), .org_off = 0x8230 },
    .{ .off = @offsetOf(Channel, "pattern_start_ptr"), .org_off = 0x8240 },
    .{ .off = @offsetOf(Channel, "pitch_envelope_num_ticks"), .org_off = 0x280 },
    .{ .off = @offsetOf(Channel, "pitch_envelope_delay"), .org_off = 0x281 },
    .{ .off = @offsetOf(Channel, "pitch_envelope_direction"), .org_off = 0x290 },
    .{ .off = @offsetOf(Channel, "pitch_envelope_slide_value"), .org_off = 0x291 },
    .{ .off = @offsetOf(Channel, "vibrato_count"), .org_off = 0x2a0 },
    .{ .off = @offsetOf(Channel, "vibrato_rate"), .org_off = 0x2a1 },
    .{ .off = @offsetOf(Channel, "vibrato_delay_ticks"), .org_off = 0x2b0 },
    .{ .off = @offsetOf(Channel, "vibrato_fade_num_ticks"), .org_off = 0x2b1 },
    .{ .off = @offsetOf(Channel, "vibrato_fade_add_per_tick"), .org_off = 0x2c0 },
    .{ .off = @offsetOf(Channel, "vibrato_depth_target"), .org_off = 0x2c1 },
    .{ .off = @offsetOf(Channel, "tremolo_count"), .org_off = 0x2d0 },
    .{ .off = @offsetOf(Channel, "tremolo_rate"), .org_off = 0x2d1 },
    .{ .off = @offsetOf(Channel, "tremolo_delay_ticks"), .org_off = 0x2e0 },
    .{ .off = @offsetOf(Channel, "channel_transposition"), .org_off = 0x2f0 },
    .{ .off = @offsetOf(Channel, "channel_volume"), .org_off = 0x8300 },
    .{ .off = @offsetOf(Channel, "volume_fade_addpertick"), .org_off = 0x8310 },
    .{ .off = @offsetOf(Channel, "volume_fade_target"), .org_off = 0x320 },
    .{ .off = @offsetOf(Channel, "final_volume"), .org_off = 0x321 },
    .{ .off = @offsetOf(Channel, "pan_value"), .org_off = 0x8330 },
    .{ .off = @offsetOf(Channel, "pan_add_per_tick"), .org_off = 0x8340 },
    .{ .off = @offsetOf(Channel, "pan_target_value"), .org_off = 0x350 },
    .{ .off = @offsetOf(Channel, "pan_flag_with_phase_invert"), .org_off = 0x351 },
    .{ .off = @offsetOf(Channel, "pitch"), .org_off = 0x8360 },
    .{ .off = @offsetOf(Channel, "pitch_add_per_tick"), .org_off = 0x8370 },
    .{ .off = @offsetOf(Channel, "pitch_target"), .org_off = 0x380 },
    .{ .off = @offsetOf(Channel, "fine_tune"), .org_off = 0x381 },
    .{ .off = @offsetOf(Channel, "sfx_sound_ptr"), .org_off = 0x8390 },
    .{ .off = @offsetOf(Channel, "sfx_which_sound"), .org_off = 0x3a0 },
    .{ .off = @offsetOf(Channel, "sfx_arr_countdown"), .org_off = 0x3a1 },
    .{ .off = @offsetOf(Channel, "sfx_note_length_left"), .org_off = 0x3b0 },
    .{ .off = @offsetOf(Channel, "sfx_note_length"), .org_off = 0x3b1 },
    .{ .off = @offsetOf(Channel, "sfx_pan"), .org_off = 0x3d0 },
};

pub const kSpcPlayer_Maps = [70]MemMapSized{
    .{ .off = @offsetOf(SpcPlayer, "new_value_from_snes"), .org_off = 0x0, .size = 4 },
    .{ .off = @offsetOf(SpcPlayer, "port_to_snes"), .org_off = 0x4, .size = 4 },
    .{ .off = @offsetOf(SpcPlayer, "last_value_from_snes"), .org_off = 0x8, .size = 4 },
    .{ .off = @offsetOf(SpcPlayer, "counter_sf0c"), .org_off = 0xc, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "_always_zero"), .org_off = 0xe, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "temp_accum"), .org_off = 0x10, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "ttt"), .org_off = 0x12, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "did_affect_volumepitch_flag"), .org_off = 0x13, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "addr0"), .org_off = 0x14, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "addr1"), .org_off = 0x16, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "lfsr_value"), .org_off = 0x18, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "is_chan_on"), .org_off = 0x1a, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "fast_forward"), .org_off = 0x1b, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_start_arg_pan"), .org_off = 0x20, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_sound_ptr_cur"), .org_off = 0x2c, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "music_ptr_toplevel"), .org_off = 0x40, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "block_count"), .org_off = 0x42, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_timer_accum"), .org_off = 0x43, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "chn"), .org_off = 0x44, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "key_ON"), .org_off = 0x45, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "key_OFF"), .org_off = 0x46, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "cur_chan_bit"), .org_off = 0x47, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "reg_FLG"), .org_off = 0x48, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "reg_NON"), .org_off = 0x49, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "reg_EON"), .org_off = 0x4a, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "reg_PMON"), .org_off = 0x4b, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_stored_time"), .org_off = 0x4c, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_parameter_EDL"), .org_off = 0x4d, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "reg_EFB"), .org_off = 0x4e, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "global_transposition"), .org_off = 0x50, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "main_tempo_accum"), .org_off = 0x51, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "tempo"), .org_off = 0x52, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "tempo_fade_num_ticks"), .org_off = 0x54, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "tempo_fade_final"), .org_off = 0x55, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "tempo_fade_add"), .org_off = 0x56, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "master_volume"), .org_off = 0x58, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "master_volume_fade_ticks"), .org_off = 0x5a, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "master_volume_fade_target"), .org_off = 0x5b, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "master_volume_fade_add_per_tick"), .org_off = 0x5c, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "vol_dirty"), .org_off = 0x5e, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "percussion_base_id"), .org_off = 0x5f, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_left"), .org_off = 0x60, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_right"), .org_off = 0x62, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_fade_add_left"), .org_off = 0x64, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_fade_add_right"), .org_off = 0x66, .size = 2 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_fade_ticks"), .org_off = 0x68, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_fade_target_left"), .org_off = 0x69, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_volume_fade_target_right"), .org_off = 0x6a, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_channel_index"), .org_off = 0x3c0, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "current_bit"), .org_off = 0x3c1, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "dsp_register_index"), .org_off = 0x3c2, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_channels"), .org_off = 0x3c3, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "byte_3C4"), .org_off = 0x3c4, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "byte_3C5"), .org_off = 0x3c5, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "echo_fract_incr"), .org_off = 0x3c7, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_channel_index2"), .org_off = 0x3c8, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_channel_bit"), .org_off = 0x3c9, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "pause_music_ctr"), .org_off = 0x3ca, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port2_active"), .org_off = 0x3cb, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port2_current_bit"), .org_off = 0x3cc, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port3_active"), .org_off = 0x3cd, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port3_current_bit"), .org_off = 0x3ce, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port1_active"), .org_off = 0x3cf, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port1_current_bit"), .org_off = 0x3e0, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "byte_3E1"), .org_off = 0x3e1, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_play_echo_flag"), .org_off = 0x3e2, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "sfx_channels_echo_mask2"), .org_off = 0x3e3, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "port1_counter"), .org_off = 0x3e4, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "channel_67_volume"), .org_off = 0x3e5, .size = 1 },
    .{ .off = @offsetOf(SpcPlayer, "cutk_always_zero"), .org_off = 0x3ff, .size = 1 },
};
